// Code generated by counterfeiter. DO NOT EDIT.
package eventsfakes

import (
	"context"
	"sync"

	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/events"
)

type FakeEventHandler struct {
	HandleEventBatchStub        func(context.Context, logr.Logger, events.EventBatch)
	handleEventBatchMutex       sync.RWMutex
	handleEventBatchArgsForCall []FakeEventHandlerHandleEventBatchArgs
	invocations                 map[string][][]interface{}
	callOrder                   []string
	invocationsMutex            sync.RWMutex
}

// FakeEventHandlerHandleEventBatchArgs holds the arguments of one call to HandleEventBatch.
type FakeEventHandlerHandleEventBatchArgs struct {
	Arg1 context.Context
	Arg2 logr.Logger
	Arg3 events.EventBatch
}

func (fake *FakeEventHandler) HandleEventBatch(arg1 context.Context, arg2 logr.Logger, arg3 events.EventBatch) {
	var arg3Copy events.EventBatch
	if arg3 != nil {
		arg3Copy = make(events.EventBatch, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.handleEventBatchMutex.Lock()
	fake.handleEventBatchArgsForCall = append(fake.handleEventBatchArgsForCall, FakeEventHandlerHandleEventBatchArgs{arg1, arg2, arg3Copy})
	stub := fake.HandleEventBatchStub
	fake.recordInvocation("HandleEventBatch", []interface{}{arg1, arg2, arg3Copy})
	fake.handleEventBatchMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2, arg3)
	}
}

func (fake *FakeEventHandler) HandleEventBatchCallCount() int {
	fake.handleEventBatchMutex.RLock()
	defer fake.handleEventBatchMutex.RUnlock()
	return len(fake.handleEventBatchArgsForCall)
}

func (fake *FakeEventHandler) HandleEventBatchCalls(stub func(context.Context, logr.Logger, events.EventBatch)) {
	fake.handleEventBatchMutex.Lock()
	defer fake.handleEventBatchMutex.Unlock()
	fake.HandleEventBatchStub = stub
}

func (fake *FakeEventHandler) HandleEventBatchArgsForCall(i int) (context.Context, logr.Logger, events.EventBatch) {
	fake.handleEventBatchMutex.RLock()
	defer fake.handleEventBatchMutex.RUnlock()
	argsForCall := fake.handleEventBatchArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeEventHandler) HandleEventBatchArgs() []FakeEventHandlerHandleEventBatchArgs {
	fake.handleEventBatchMutex.RLock()
	defer fake.handleEventBatchMutex.RUnlock()
	args := make([]FakeEventHandlerHandleEventBatchArgs, len(fake.handleEventBatchArgsForCall))
	copy(args, fake.handleEventBatchArgsForCall)
	return args
}

func (fake *FakeEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEventHandler) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ events.EventHandler = new(FakeEventHandler)
