// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package eventsfakes

import (
	"context"
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/events"
	"sync"
)

// EventHandlerMock is a mock implementation of events.EventHandler.
//
//	func TestSomethingThatUsesEventHandler(t *testing.T) {
//
//		// make and configure a mocked events.EventHandler
//		mockedEventHandler := &EventHandlerMock{
//			HandleEventBatchFunc: func(ctx context.Context, logger logr.Logger, batch events.EventBatch)  {
//				panic("mock out the HandleEventBatch method")
//			},
//		}
//
//		// use mockedEventHandler in code that requires events.EventHandler
//		// and then make assertions.
//
//	}
type EventHandlerMock struct {
	// HandleEventBatchFunc mocks the HandleEventBatch method.
	HandleEventBatchFunc func(ctx context.Context, logger logr.Logger, batch events.EventBatch)

	// calls tracks calls to the methods.
	calls struct {
		// HandleEventBatch holds details about calls to the HandleEventBatch method.
		HandleEventBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Logger is the logger argument value.
			Logger logr.Logger
			// Batch is the batch argument value.
			Batch events.EventBatch
		}
	}
	lockHandleEventBatch sync.RWMutex
}

// HandleEventBatch calls HandleEventBatchFunc.
func (mock *EventHandlerMock) HandleEventBatch(ctx context.Context, logger logr.Logger, batch events.EventBatch) {
	if mock.HandleEventBatchFunc == nil {
		panic("EventHandlerMock.HandleEventBatchFunc: method is nil but EventHandler.HandleEventBatch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Logger logr.Logger
		Batch  events.EventBatch
	}{
		Ctx:    ctx,
		Logger: logger,
		Batch:  batch,
	}
	mock.lockHandleEventBatch.Lock()
	mock.calls.HandleEventBatch = append(mock.calls.HandleEventBatch, callInfo)
	mock.lockHandleEventBatch.Unlock()
	mock.HandleEventBatchFunc(ctx, logger, batch)
}

// HandleEventBatchCalls gets all the calls that were made to HandleEventBatch.
// Check the length with:
//
//	len(mockedEventHandler.HandleEventBatchCalls())
func (mock *EventHandlerMock) HandleEventBatchCalls() []struct {
	Ctx    context.Context
	Logger logr.Logger
	Batch  events.EventBatch
} {
	var calls []struct {
		Ctx    context.Context
		Logger logr.Logger
		Batch  events.EventBatch
	}
	mock.lockHandleEventBatch.RLock()
	calls = mock.calls.HandleEventBatch
	mock.lockHandleEventBatch.RUnlock()
	return calls
}
