// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package eventsfakes

import (
	"context"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/events"
	"sync"
)

// FirstEventBatchPreparerMock is a mock implementation of events.FirstEventBatchPreparer.
//
//	func TestSomethingThatUsesFirstEventBatchPreparer(t *testing.T) {
//
//		// make and configure a mocked events.FirstEventBatchPreparer
//		mockedFirstEventBatchPreparer := &FirstEventBatchPreparerMock{
//			PrepareFunc: func(ctx context.Context) (events.EventBatch, error) {
//				panic("mock out the Prepare method")
//			},
//		}
//
//		// use mockedFirstEventBatchPreparer in code that requires events.FirstEventBatchPreparer
//		// and then make assertions.
//
//	}
type FirstEventBatchPreparerMock struct {
	// PrepareFunc mocks the Prepare method.
	PrepareFunc func(ctx context.Context) (events.EventBatch, error)

	// calls tracks calls to the methods.
	calls struct {
		// Prepare holds details about calls to the Prepare method.
		Prepare []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPrepare sync.RWMutex
}

// Prepare calls PrepareFunc.
func (mock *FirstEventBatchPreparerMock) Prepare(ctx context.Context) (events.EventBatch, error) {
	if mock.PrepareFunc == nil {
		panic("FirstEventBatchPreparerMock.PrepareFunc: method is nil but FirstEventBatchPreparer.Prepare was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPrepare.Lock()
	mock.calls.Prepare = append(mock.calls.Prepare, callInfo)
	mock.lockPrepare.Unlock()
	return mock.PrepareFunc(ctx)
}

// PrepareCalls gets all the calls that were made to Prepare.
// Check the length with:
//
//	len(mockedFirstEventBatchPreparer.PrepareCalls())
func (mock *FirstEventBatchPreparerMock) PrepareCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPrepare.RLock()
	calls = mock.calls.Prepare
	mock.lockPrepare.RUnlock()
	return calls
}
