apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-gateway
rules:
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - gatewayconfigs
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - gateways/status
  - gatewayclasses/status
  verbs:
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-gateway
subjects:
- kind: ServiceAccount
  name: nginx-gateway
  namespace: nginx-gateway
roleRef:
  kind: ClusterRole
  name: nginx-gateway
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-gateway
data:
  nginx.conf: |
    load_module /usr/lib/nginx/modules/ngx_http_js_module.so;

    events {}

    pid /etc/nginx/nginx.pid;
    error_log stderr debug;

    http {
      include /etc/nginx/conf.d/*.conf;
      js_import /usr/lib/nginx/modules/njs/httpmatches.js;
      server_names_hash_bucket_size 256;
      server_names_hash_max_size 1024;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      shareProcessNamespace: true
      serviceAccountName: nginx-gateway
      volumes:
      - name: nginx
        emptyDir: { }
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: var-lib-nginx
        emptyDir: { }
      - name: njs-modules
        configMap:
          name: njs-modules
      initContainers:
      - image: busybox:1.36
        name: set-permissions
        command: [ 'sh', '-c', 'rm -r /etc/nginx/conf.d /etc/nginx/secrets; mkdir /etc/nginx/conf.d /etc/nginx/secrets && chown 1001:0 /etc/nginx/conf.d /etc/nginx/secrets' ]
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
      containers:
      - image: ghcr.io/nginxinc/nginx-kubernetes-gateway:edge
        imagePullPolicy: Always
        name: nginx-gateway
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
        securityContext:
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
            add:
            - KILL
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - static-mode
        - --gateway-ctlr-name=k8s-gateway.nginx.org/nginx-gateway-controller
        - --gatewayclass=nginx
      - image: nginx:1.25
        imagePullPolicy: Always
        name: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: var-lib-nginx
          mountPath: /var/lib/nginx
        - name: njs-modules
          mountPath: /usr/lib/nginx/modules/njs
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
