# Create SCC for Gateway resources
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: nginx-ngf-admin
allowPrivilegedContainer: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPorts: false
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 101
  uidRangeMax: 102
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
seLinuxContext:
  type: MustRunAs
volumes:
  - emptyDir
  - secret
users:
  - 'system:serviceaccount:*:ngf-nginx-gateway-fabric'
allowedCapabilities:
  - NET_BIND_SERVICE
  - KILL
requiredDropCapabilities:
  - ALL
