// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolverfakes

import (
	"context"
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/resolver"
	v1 "k8s.io/api/core/v1"
	discoveryV1 "k8s.io/api/discovery/v1"
	"k8s.io/apimachinery/pkg/types"
	"sync"
)

// ServiceResolverMock is a mock implementation of resolver.ServiceResolver.
//
//	func TestSomethingThatUsesServiceResolver(t *testing.T) {
//
//		// make and configure a mocked resolver.ServiceResolver
//		mockedServiceResolver := &ServiceResolverMock{
//			ResolveFunc: func(ctx context.Context, logger logr.Logger, svcNsName types.NamespacedName, svcPort v1.ServicePort, allowedAddressType []discoveryV1.AddressType) ([]resolver.Endpoint, error) {
//				panic("mock out the Resolve method")
//			},
//		}
//
//		// use mockedServiceResolver in code that requires resolver.ServiceResolver
//		// and then make assertions.
//
//	}
type ServiceResolverMock struct {
	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, logger logr.Logger, svcNsName types.NamespacedName, svcPort v1.ServicePort, allowedAddressType []discoveryV1.AddressType) ([]resolver.Endpoint, error)

	// calls tracks calls to the methods.
	calls struct {
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Logger is the logger argument value.
			Logger logr.Logger
			// SvcNsName is the svcNsName argument value.
			SvcNsName types.NamespacedName
			// SvcPort is the svcPort argument value.
			SvcPort v1.ServicePort
			// AllowedAddressType is the allowedAddressType argument value.
			AllowedAddressType []discoveryV1.AddressType
		}
	}
	lockResolve sync.RWMutex
}

// Resolve calls ResolveFunc.
func (mock *ServiceResolverMock) Resolve(ctx context.Context, logger logr.Logger, svcNsName types.NamespacedName, svcPort v1.ServicePort, allowedAddressType []discoveryV1.AddressType) ([]resolver.Endpoint, error) {
	if mock.ResolveFunc == nil {
		panic("ServiceResolverMock.ResolveFunc: method is nil but ServiceResolver.Resolve was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		Logger             logr.Logger
		SvcNsName          types.NamespacedName
		SvcPort            v1.ServicePort
		AllowedAddressType []discoveryV1.AddressType
	}{
		Ctx:                ctx,
		Logger:             logger,
		SvcNsName:          svcNsName,
		SvcPort:            svcPort,
		AllowedAddressType: allowedAddressType,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(ctx, logger, svcNsName, svcPort, allowedAddressType)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedServiceResolver.ResolveCalls())
func (mock *ServiceResolverMock) ResolveCalls() []struct {
	Ctx                context.Context
	Logger             logr.Logger
	SvcNsName          types.NamespacedName
	SvcPort            v1.ServicePort
	AllowedAddressType []discoveryV1.AddressType
} {
	var calls []struct {
		Ctx                context.Context
		Logger             logr.Logger
		SvcNsName          types.NamespacedName
		SvcPort            v1.ServicePort
		AllowedAddressType []discoveryV1.AddressType
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}
