// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolverfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph/shared/configmaps"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph/shared/secrets"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/resolver"
	"k8s.io/apimachinery/pkg/types"
	"sync"
)

// ResolverMock is a mock implementation of resolver.Resolver.
//
//	func TestSomethingThatUsesResolver(t *testing.T) {
//
//		// make and configure a mocked resolver.Resolver
//		mockedResolver := &ResolverMock{
//			GetConfigMapsFunc: func() map[types.NamespacedName]*configmaps.CaCertConfigMap {
//				panic("mock out the GetConfigMaps method")
//			},
//			GetSecretsFunc: func() map[types.NamespacedName]*secrets.Secret {
//				panic("mock out the GetSecrets method")
//			},
//			ResolveFunc: func(resourceType resolver.ResourceType, namespacedName types.NamespacedName, resolveOptions ...resolver.ResolveOption) error {
//				panic("mock out the Resolve method")
//			},
//		}
//
//		// use mockedResolver in code that requires resolver.Resolver
//		// and then make assertions.
//
//	}
type ResolverMock struct {
	// GetConfigMapsFunc mocks the GetConfigMaps method.
	GetConfigMapsFunc func() map[types.NamespacedName]*configmaps.CaCertConfigMap

	// GetSecretsFunc mocks the GetSecrets method.
	GetSecretsFunc func() map[types.NamespacedName]*secrets.Secret

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(resourceType resolver.ResourceType, namespacedName types.NamespacedName, resolveOptions ...resolver.ResolveOption) error

	// calls tracks calls to the methods.
	calls struct {
		// GetConfigMaps holds details about calls to the GetConfigMaps method.
		GetConfigMaps []struct {
		}
		// GetSecrets holds details about calls to the GetSecrets method.
		GetSecrets []struct {
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// ResourceType is the resourceType argument value.
			ResourceType resolver.ResourceType
			// NamespacedName is the namespacedName argument value.
			NamespacedName types.NamespacedName
			// ResolveOptions is the resolveOptions argument value.
			ResolveOptions []resolver.ResolveOption
		}
	}
	lockGetConfigMaps sync.RWMutex
	lockGetSecrets    sync.RWMutex
	lockResolve       sync.RWMutex
}

// GetConfigMaps calls GetConfigMapsFunc.
func (mock *ResolverMock) GetConfigMaps() map[types.NamespacedName]*configmaps.CaCertConfigMap {
	if mock.GetConfigMapsFunc == nil {
		panic("ResolverMock.GetConfigMapsFunc: method is nil but Resolver.GetConfigMaps was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfigMaps.Lock()
	mock.calls.GetConfigMaps = append(mock.calls.GetConfigMaps, callInfo)
	mock.lockGetConfigMaps.Unlock()
	return mock.GetConfigMapsFunc()
}

// GetConfigMapsCalls gets all the calls that were made to GetConfigMaps.
// Check the length with:
//
//	len(mockedResolver.GetConfigMapsCalls())
func (mock *ResolverMock) GetConfigMapsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfigMaps.RLock()
	calls = mock.calls.GetConfigMaps
	mock.lockGetConfigMaps.RUnlock()
	return calls
}

// GetSecrets calls GetSecretsFunc.
func (mock *ResolverMock) GetSecrets() map[types.NamespacedName]*secrets.Secret {
	if mock.GetSecretsFunc == nil {
		panic("ResolverMock.GetSecretsFunc: method is nil but Resolver.GetSecrets was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSecrets.Lock()
	mock.calls.GetSecrets = append(mock.calls.GetSecrets, callInfo)
	mock.lockGetSecrets.Unlock()
	return mock.GetSecretsFunc()
}

// GetSecretsCalls gets all the calls that were made to GetSecrets.
// Check the length with:
//
//	len(mockedResolver.GetSecretsCalls())
func (mock *ResolverMock) GetSecretsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSecrets.RLock()
	calls = mock.calls.GetSecrets
	mock.lockGetSecrets.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *ResolverMock) Resolve(resourceType resolver.ResourceType, namespacedName types.NamespacedName, resolveOptions ...resolver.ResolveOption) error {
	if mock.ResolveFunc == nil {
		panic("ResolverMock.ResolveFunc: method is nil but Resolver.Resolve was just called")
	}
	callInfo := struct {
		ResourceType   resolver.ResourceType
		NamespacedName types.NamespacedName
		ResolveOptions []resolver.ResolveOption
	}{
		ResourceType:   resourceType,
		NamespacedName: namespacedName,
		ResolveOptions: resolveOptions,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(resourceType, namespacedName, resolveOptions...)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedResolver.ResolveCalls())
func (mock *ResolverMock) ResolveCalls() []struct {
	ResourceType   resolver.ResourceType
	NamespacedName types.NamespacedName
	ResolveOptions []resolver.ResolveOption
} {
	var calls []struct {
		ResourceType   resolver.ResourceType
		NamespacedName types.NamespacedName
		ResolveOptions []resolver.ResolveOption
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}
