apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: f5-waf-seaweedfs-issuer
  namespace: nap5-helm-policy
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: f5-waf-seaweedfs-ca-cert
  namespace: nap5-helm-policy
spec:
  secretName: f5-waf-seaweedfs-ca-cert
  commonName: "seaweedfs-root-ca"
  isCA: true
  issuerRef:
    name: f5-waf-seaweedfs-issuer
    kind: Issuer
  duration: 87600h  # 10 years
  renewBefore: 720h  # 30 days
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: f5-waf-seaweedfs-ca-issuer
  namespace: nap5-helm-policy
spec:
  ca:
    secretName: f5-waf-seaweedfs-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: f5-waf-seaweedfs-master-cert
  namespace: nap5-helm-policy
spec:
  secretName: f5-waf-seaweedfs-master-cert
  issuerRef:
    name: f5-waf-seaweedfs-ca-issuer
    kind: Issuer
  commonName: "SeaweedFS CA"
  dnsNames:
    - '*.nap5-helm-policy'
    - '*.nap5-helm-policy.svc'
    - '*.nap5-helm-policy.svc.cluster.local'
    - '*.seaweedfs-master'
    - '*.seaweedfs-master.nap5-helm-policy'
    - '*.seaweedfs-master.nap5-helm-policy.svc'
    - '*.seaweedfs-master.nap5-helm-policy.svc.cluster.local'
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: f5-waf-seaweedfs-volume-cert
  namespace: nap5-helm-policy
spec:
  secretName: f5-waf-seaweedfs-volume-cert
  issuerRef:
    name: f5-waf-seaweedfs-ca-issuer
    kind: Issuer
  commonName: "SeaweedFS CA"
  dnsNames:
    - '*.nap5-helm-policy'
    - '*.nap5-helm-policy.svc'
    - '*.nap5-helm-policy.svc.cluster.local'
    - '*.seaweedfs-volume'
    - '*.seaweedfs-volume.nap5-helm-policy'
    - '*.seaweedfs-volume.nap5-helm-policy.svc'
    - '*.seaweedfs-volume.nap5-helm-policy.svc.cluster.local'
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h
  renewBefore: 360h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: f5-waf-seaweedfs-filer-cert
  namespace: nap5-helm-policy
spec:
  secretName: f5-waf-seaweedfs-filer-cert
  issuerRef:
    name: f5-waf-seaweedfs-ca-issuer
    kind: Issuer
  commonName: "SeaweedFS CA"
  dnsNames:
    - '*.nap5-helm-policy'
    - '*.nap5-helm-policy.svc'
    - '*.nap5-helm-policy.svc.cluster.local'
    - '*.seaweedfs-filer'
    - '*.seaweedfs-filer.nap5-helm-policy'
    - '*.seaweedfs-filer.nap5-helm-policy.svc'
    - '*.seaweedfs-filer.nap5-helm-policy.svc.cluster.local'
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h
  renewBefore: 360h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: f5-waf-seaweedfs-client-cert
  namespace: nap5-helm-policy
spec:
  secretName: f5-waf-seaweedfs-client-cert
  issuerRef:
    name: f5-waf-seaweedfs-ca-issuer
    kind: Issuer
  commonName: "SeaweedFS CA"
  dnsNames:
    - '*.nap5-helm-policy'
    - '*.nap5-helm-policy.svc'
    - '*.nap5-helm-policy.svc.cluster.local'
    - client
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h
  renewBefore: 360h
