apiVersion: gateway.nginx.org/v1alpha1
kind: WAFGatewayBindingPolicy
metadata:
  name: route-protection-http
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: coffee
  type: HTTP
  policySource:
    url: http://bundle-server.default.svc.cluster.local/dataguard-blocking.tgz
  securityLogs:
    - destination:
        type: stderr
      logSource:
        defaultProfile: log_illegal
