apiVersion: gateway.nginx.org/v1alpha1
kind: WAFGatewayBindingPolicy
metadata:
  name: gateway-base-protection
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  type: NIM
  policySource:
    nimSource:
      url: https://apigw.nim.svc.cluster.local
      policyName: ngfBlocking
      # Optional - use policyUID instead for version pinning
      # policyUID: ""
      # Optional - add checksum for integrity verification of the bundle
    # validation:
    #   expectedChecksum: "abc123..." # 64 hex characters, e.g. output of: sha256sum policy.tgz | awk '{print $1}'
    auth:
      secretRef:
        name: nim-credentials
    insecureSkipVerify: true # testing only - do not use in production
  securityLogs:
    - destination:
        type: syslog
        syslog:
          server: syslog-svc.default.svc.cluster.local:514
      logSource:
        # Use one of the built-in log profiles:
        defaultProfile: log_illegal
