apiVersion: gateway.nginx.org/v1alpha1
kind: WAFGatewayBindingPolicy
metadata:
  name: gateway-base-protection
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  type: N1C
  policySource:
    n1cSource:
      url: https://<tenant>.volterra.us
      namespace: default  # N1C namespace the policy belongs to
      policyName: "ngfExample"
      policyObjectID: pol_-IUuEUN7ST63oRC7AlQPLw
      policyVersion: "2026-04-02 20:55:06"
    auth:
      secretRef:
        name: n1c-credentials
  securityLogs:
    - destination:
        type: syslog
        syslog:
          server: syslog-svc.default.svc.cluster.local:514
      logSource:
        # Use one of the built-in log profiles:
        defaultProfile: log_illegal
