apiVersion: gateway.nginx.org/v1alpha1
kind: WAFGatewayBindingPolicy
metadata:
  name: gateway-base-protection
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  apPolicySource:
    name: dataguard-blocking
  securityLogs:
    - apLogConfSource:
        name: logconf
      destination:
        type: syslog
        syslog:
          server: syslog-svc.default.svc.cluster.local:514
