// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controllerfakes

import (
	"sync"
)

// LogLevelSetterMock is a mock implementation of controller.logLevelSetter.
//
//	func TestSomethingThatUseslogLevelSetter(t *testing.T) {
//
//		// make and configure a mocked controller.logLevelSetter
//		mockedlogLevelSetter := &LogLevelSetterMock{
//			SetLevelFunc: func(s string) error {
//				panic("mock out the SetLevel method")
//			},
//		}
//
//		// use mockedlogLevelSetter in code that requires controller.logLevelSetter
//		// and then make assertions.
//
//	}
type LogLevelSetterMock struct {
	// SetLevelFunc mocks the SetLevel method.
	SetLevelFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// SetLevel holds details about calls to the SetLevel method.
		SetLevel []struct {
			// S is the s argument value.
			S string
		}
	}
	lockSetLevel sync.RWMutex
}

// SetLevel calls SetLevelFunc.
func (mock *LogLevelSetterMock) SetLevel(s string) error {
	if mock.SetLevelFunc == nil {
		panic("LogLevelSetterMock.SetLevelFunc: method is nil but logLevelSetter.SetLevel was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockSetLevel.Lock()
	mock.calls.SetLevel = append(mock.calls.SetLevel, callInfo)
	mock.lockSetLevel.Unlock()
	return mock.SetLevelFunc(s)
}

// SetLevelCalls gets all the calls that were made to SetLevel.
// Check the length with:
//
//	len(mockedlogLevelSetter.SetLevelCalls())
func (mock *LogLevelSetterMock) SetLevelCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockSetLevel.RLock()
	calls = mock.calls.SetLevel
	mock.lockSetLevel.RUnlock()
	return calls
}
