version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "ciarams87"
      - "f5yacobucci"
      - "pleshakov"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "f5yacobucci"
      - "pleshakov"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: daily
    reviewers:
      - "f5yacobucci"
      - "pleshakov"
