version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directories:
      - /
      - /tests
    schedule:
      interval: daily

  - package-ecosystem: docker
    directories:
      - /build
      - /conformance/tests
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /internal/mode/static/nginx/modules
    schedule:
      interval: daily
