version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/kubernetes-gateway"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/kubernetes-gateway"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/kubernetes-gateway"
  - package-ecosystem: "npm"
    directory: "/internal/nginx/modules"
    schedule:
      interval: "daily"
    reviewers:
      - "nginxinc/kubernetes-gateway"
