env:
  - CGO_ENABLED=0

builds:
  - id: gateway
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    main: ./cmd/gateway/
    binary: gateway

changelog:
  skip: true

archives:
  - id: gateway

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

blobs:
  - provider: azblob
    bucket: '{{.Env.AZURE_BUCKET_NAME}}'

announce:
  slack:
    enabled: true
    channel: '#announcements'
    message_template: 'NGINX Kubernetes Gateway {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'

milestones:
  - close: true

snapshot:
  name_template: 'edge'
