version: 2
env:
  - CGO_ENABLED=0

builds:
  - id: gateway
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.telemetryReportPeriod=24h
      - -X main.telemetryEndpoint={{.Env.TELEMETRY_ENDPOINT}}
      - -X main.telemetryEndpointInsecure={{.Env.TELEMETRY_ENDPOINT_INSECURE}}
    main: ./cmd/gateway/
    binary: gateway

changelog:
  disable: true

archives:
  - id: gateway

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    signature: "${artifact}.sig.bundle"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"

milestones:
  - close: true

snapshot:
  version_template: "edge"
