version: 2
env:
  - CGO_ENABLED=0

builds:
  - id: gateway
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.telemetryReportPeriod=24h
      - -X main.telemetryEndpoint={{.Env.TELEMETRY_ENDPOINT}}
      - -X main.telemetryEndpointInsecure={{.Env.TELEMETRY_ENDPOINT_INSECURE}}
    main: ./cmd/gateway/
    binary: gateway

changelog:
  disable: true

archives:
  - id: gateway

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

blobs:
  - provider: azblob
    bucket: "{{.Env.AZURE_BUCKET_NAME}}"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

announce:
  slack:
    enabled: true
    channel: "#announcements"
    message_template: "NGINX Gateway Fabric {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}"

milestones:
  - close: true

snapshot:
  name_template: "edge"
