# Use kubectl edit to update the existing global config, or you can also
# configure these options on install using Helm.
# This resource configures the global options for all Gateways attached to
# GatewayClass.
# Any Gateways attached to this GatewayClass will automatically inherit this configuration.
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: nginx-gateway-proxy-config
  namespace: nginx-gateway
spec:
  gatewayLink:
    enabled: true
    # If IPAM integration is enabled, F5 IPAM Controller will allocate
    # an IP from the pool associated with this label
    ipamLabel: "production"
    # Define IRules (must use full path format: /partition/irule_name)
    iRules:
      - "/Common/Proxy_Protocol_iRule"
    tls:
      clientSSLs:
        - "/Common/clientssl"
      serverSSLs:
        - "/Common/serverssl"
      reference: bigip
    # Multi-cluster configuration: CIS will load balance across clusters.
    # Cluster names must match the names defined in the CIS deployment configmap.
    # Unless overridden per Gateway, the namespace and service will default to
    # matching the local namepscae and service.
    multiCluster:
      localClusterName: "cluster-1"
      remoteClusters:
        - clusterName: "cluster-2"

  # Configure Proxy Protocol to preserve client IPs from BIG-IP
  rewriteClientIP:
    mode: ProxyProtocol
    trustedAddresses:
      - type: CIDR
        value: 10.8.0.0/14

  kubernetes:
    # Use ClusterIP since BIG-IP handles external traffic routing
    # Use NodePort if CIS is deployed with --pool-member-type=nodeport
    service:
      type: NodePort
    deployment:
      container:
        # Configure readiness probe
        readinessProbe:
          path: "/nginx-ready"  # ← Compatibility with CIS/BIG-IP
          port: 8081
          expose: true
