apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: {{ .Values.nginxGateway.gatewayClassName }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.nginxGateway.gatewayControllerName }}
  parametersRef:
    group: gateway.nginx.org
    kind: NginxProxy
    name: {{ include "nginx-gateway.proxy-config-name" . }}
    namespace: {{ .Release.Namespace }}
