{{- if .Values.gateway.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
{{- if .Values.gateway.service.extraLabels }}
{{ toYaml .Values.gateway.service.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.gateway.service.annotations }}
  annotations:
{{ toYaml .Values.gateway.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if or (eq .Values.gateway.service.type "LoadBalancer") (eq .Values.gateway.service.type "NodePort") }}
  {{- if .Values.gateway.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.gateway.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
  type: {{ .Values.gateway.service.type }}
  ports:
{{- if .Values.gateway.service.ports }}
{{ toYaml .Values.gateway.service.ports | indent 2 }}
{{ end }}
  selector:
    {{- include "nginx-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
