package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Info relating to each policy.
type PolicyData struct {
	Name      string
	SingleRef bool // false if TargetRefs is used, else true as using TargetRef
}

// Data template to gather the package and what policies belong to it.
type TemplateData struct {
	PackageName string
	Policies    []PolicyData
}

const policyMethodsTemplate = `// Code generated by policygen.go. DO NOT EDIT.

package {{ .PackageName }}

import (
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

{{ range .Policies }}

func (p *{{ .Name }}) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	{{- if .SingleRef }}
	return []gatewayv1.LocalPolicyTargetReference{p.Spec.TargetRef}
	{{- else }}
	return p.Spec.TargetRefs
	{{- end }}
}

func (p *{{ .Name }}) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

func (p *{{ .Name }}) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}

{{- end}}

`

// resourceStemFromFilename derives the lowercase comparison key for a policy.
func resourceStemFromFilename(fileName string) string {
	base := strings.TrimSuffix(fileName, filepath.Ext(fileName))
	return strings.ToLower(strings.TrimSuffix(base, "_types"))
}

// structTypes returns every top-level struct declared in f, keyed by name.
func structTypes(f *ast.File) map[string]*ast.StructType {
	types := make(map[string]*ast.StructType)

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			types[typeSpec.Name.Name] = structType
		}
	}

	return types
}

// resolveResourceName finds the top-level struct with the same name as the file.
func resolveResourceName(filePath string, allTypes map[string]*ast.StructType) (string, error) {
	stem := resourceStemFromFilename(filepath.Base(filePath))

	for name := range allTypes {
		if strings.ToLower(name) == stem {
			return name, nil
		}
	}

	return "", fmt.Errorf("no struct matching filename %q found after expanding the stem: %q)",
		filepath.Base(filePath), stem)
}

// targetRefField determines if a policy uses "TargetRef" or
// "TargetRefs". Found is false if neither is present.
func targetRefField(structType *ast.StructType) (singleRef, found bool) {
	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			switch name.Name {
			case "TargetRef":
				return true, true
			case "TargetRefs":
				return false, true
			}
		}
	}
	return false, false
}

// extractPolicies parses each file in filePaths and returns the PolicyData for found resources.
func extractPolicies(fset *token.FileSet, filePaths []string) ([]PolicyData, error) {
	var policies []PolicyData

	for _, filePath := range filePaths {
		f, err := parser.ParseFile(fset, filePath, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("failed to parse file %s: %w", filePath, err)
		}

		allTypes := structTypes(f)

		name, err := resolveResourceName(filePath, allTypes)
		if err != nil {
			return nil, err
		}

		specName := name + "Spec"
		specType, ok := allTypes[specName]
		if !ok {
			return nil, fmt.Errorf("could not find struct %s in %s", specName, filePath)
		}

		singleRef, found := targetRefField(specType)
		if !found {
			return nil, fmt.Errorf("could not find TargetRef or TargetRefs in struct %s in %s", specName, filePath)
		}

		policies = append(policies, PolicyData{Name: name, SingleRef: singleRef})
	}

	return policies, nil
}

// findPolicyFiles scans dir for non test go files containing
// the policy marker comment : `gateway.networking.k8s.io/policy`.
func findPolicyFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to read the %s directory: %w", dir, err)
	}

	var policyFiles []string
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue // filter to use only the `.go` files in directory
		}
		if entry.Name() == "externalloadbalancer_types.go" {
			continue // explicitly exclude ExternalLoadBalancer as this does not use the standard policy methods
		}
		filePath := filepath.Join(dir, entry.Name())

		content, err := os.ReadFile(filePath)
		if err != nil {
			return nil, fmt.Errorf("failed to read the file %s: %w", filePath, err)
		}

		if !strings.Contains(string(content), "gateway.networking.k8s.io/policy") {
			continue // Not a policy
		}
		policyFiles = append(policyFiles, filePath)
	}

	return policyFiles, nil
}

func main() {
	// Flags to be included in the Makefile under generate-policies.
	pkg := flag.String("package", "", "Target package name (eg: v1alpha1 or v1alpha2)")
	outputFile := flag.String("output", "",
		"name of the generated output file (eg: ~/v1alpha1/policy_methods.go)")
	flag.Parse()

	if *pkg == "" || *outputFile == "" {
		log.Fatal("Error: both -package and -output flags are required")
	}

	targetDir := filepath.Dir(*outputFile)

	fset := token.NewFileSet()

	policyFiles, err := findPolicyFiles(targetDir)
	if err != nil {
		log.Fatalf("Error: failed to find the policy files %v", err)
	}

	policies, err := extractPolicies(fset, policyFiles)
	if err != nil {
		log.Fatalf("Error: failed to extract the policy names %v", err)
	}

	if len(policies) == 0 {
		fmt.Printf("failed to find policies in the %s directory", targetDir)
		return
	}

	// Render the template.
	templ := template.Must(template.New("policyMethods").Parse(policyMethodsTemplate))

	var buf bytes.Buffer
	data := TemplateData{
		PackageName: *pkg,
		Policies:    policies,
	}
	if err := templ.Execute(&buf, data); err != nil {
		log.Fatalf("Error: failed to execute template %v", err)
	}

	// format the output
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, print the raw output so you can debug the template syntax
		fmt.Println(buf.String())
		log.Fatalf("Error: Failed to format generated Go code: %v", err)
	}

	// write out to file
	if err := os.WriteFile(*outputFile, formattedCode, 0o600); err != nil {
		log.Fatalf("Error: Failed to write output file %s: %v", *outputFile, err)
	}

	fmt.Printf("Successfully generated boilerplate code for policies %v in %s\n", policies, *outputFile)
}
