package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Info relating to each policy.
type PolicyData struct {
	Name      string
	SingleRef bool // false if TargetRefs is used, else true as using TargetRef
}

// Data template to gather the package and what policies belong to it.
type TemplateData struct {
	PackageName string
	Policies    []PolicyData
}

const policyMethodsTemplate = `// Code generated by policygen.go; DO NOT EDIT

package {{ .PackageName }}

import (
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

{{ range .Policies }}

func (p *{{ .Name }}) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	{{- if .SingleRef }}
	return []gatewayv1.LocalPolicyTargetReference{p.Spec.TargetRef}
	{{- else }}
	return p.Spec.TargetRefs
	{{- end }}
}

func (p *{{ .Name }}) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

func (p *{{ .Name }}) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}

{{- end}}

`

// hasSingleTargetRef parses the Go files in the given directory to determine
// if the struct for a given policy uses TargetRef (true) or TargetRefs (false).
func hasSingleTargetRef(dir, policyName string) (bool, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("failed to read directory %s: %w", dir, err)
	}

	specName := policyName + "Spec"

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue // filter to use only the `.go` files in directory
		}

		filePath := filepath.Join(dir, entry.Name())

		// helper function to reduce cyclomatic complexity
		isSingular, found, err := checkFileForTargetRef(fset, filePath, specName)
		if err != nil {
			return false, err
		}
		if found {
			return isSingular, nil
		}
	}

	return false, fmt.Errorf("could not find TargetRef or TargetRefs in struct %s in directory %s", specName, dir)
}

// checkFileForTargetRef inspects a single Go file for the specified struct and field.
// Returns (isSingular, found, error).
func checkFileForTargetRef(fset *token.FileSet, filePath, specName string) (bool, bool, error) {
	f, err := parser.ParseFile(fset, filePath, nil, 0)
	if err != nil {
		return false, false, fmt.Errorf("failed to parse file %s: %w", filePath, err)
	}

	// Iterate over the declarations in the file.
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != specName {
				continue // not the required spec
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			for _, field := range structType.Fields.List {
				for _, name := range field.Names {
					if name.Name == "TargetRef" {
						return true, true, nil
					}
					if name.Name == "TargetRefs" {
						return false, true, nil
					}
				}
			}
		}
	}

	// Not found in this file, but no errors occurred.
	return false, false, nil
}

func main() {
	// Flags to be included in the Makefile under generate-policies.
	pkg := flag.String("package", "", "Target package name (eg: v1alpha1 or v1alpha2)")
	outputFile := flag.String("output", "policy_methods.go",
		"name of the generated output file (eg: ~/v1alpha1/policy_methods.go)")
	flag.Parse()

	if *pkg == "" || *outputFile == "" {
		log.Fatal("Error: Both -package and -output flags are required")
	}

	// Remaining non-flags are interpreted as the policies.
	rawPolicies := flag.Args()
	if len(rawPolicies) == 0 {
		log.Fatal("Error: At least one policy type must be specified")
	}

	targetDir := filepath.Dir(*outputFile)

	// Parse arguments from Makefile into PolicyData.
	var policies []PolicyData

	for _, name := range rawPolicies {
		isSingular, err := hasSingleTargetRef(targetDir, name)
		if err != nil {
			log.Fatalf("Error: Error parsing policy %s: %v", name, err)
		}
		policies = append(policies, PolicyData{
			Name:      name,
			SingleRef: isSingular,
		})
	}

	// Render the template.
	templ := template.Must(template.New("policyMethods").Parse(policyMethodsTemplate))

	var buf bytes.Buffer
	data := TemplateData{
		PackageName: *pkg,
		Policies:    policies,
	}
	if err := templ.Execute(&buf, data); err != nil {
		log.Fatalf("Error: failed to execute template %v", err)
	}

	// format the output
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, print the raw output so you can debug the template syntax
		fmt.Println(buf.String())
		log.Fatalf("Error: Failed to format generated Go code: %v", err)
	}

	// write out to file
	if err := os.WriteFile(*outputFile, formattedCode, 0o600); err != nil {
		log.Fatalf("Error: Failed to write output file %s: %v", *outputFile, err)
	}

	fmt.Printf("Successfully generated boilerplate code for policies %v in %s\n", policies, *outputFile)
}
