// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package configfakes

import (
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	"sync"
)

// GeneratorMock is a mock implementation of config.Generator.
//
//	func TestSomethingThatUsesGenerator(t *testing.T) {
//
//		// make and configure a mocked config.Generator
//		mockedGenerator := &GeneratorMock{
//			GenerateFunc: func(logger logr.Logger, configuration dataplane.Configuration) []agent.File {
//				panic("mock out the Generate method")
//			},
//			GenerateDeploymentContextFunc: func(depCtx dataplane.DeploymentContext) (agent.File, error) {
//				panic("mock out the GenerateDeploymentContext method")
//			},
//		}
//
//		// use mockedGenerator in code that requires config.Generator
//		// and then make assertions.
//
//	}
type GeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(logger logr.Logger, configuration dataplane.Configuration) []agent.File

	// GenerateDeploymentContextFunc mocks the GenerateDeploymentContext method.
	GenerateDeploymentContextFunc func(depCtx dataplane.DeploymentContext) (agent.File, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Logger is the logger argument value.
			Logger logr.Logger
			// Configuration is the configuration argument value.
			Configuration dataplane.Configuration
		}
		// GenerateDeploymentContext holds details about calls to the GenerateDeploymentContext method.
		GenerateDeploymentContext []struct {
			// DepCtx is the depCtx argument value.
			DepCtx dataplane.DeploymentContext
		}
	}
	lockGenerate                  sync.RWMutex
	lockGenerateDeploymentContext sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *GeneratorMock) Generate(logger logr.Logger, configuration dataplane.Configuration) []agent.File {
	if mock.GenerateFunc == nil {
		panic("GeneratorMock.GenerateFunc: method is nil but Generator.Generate was just called")
	}
	callInfo := struct {
		Logger        logr.Logger
		Configuration dataplane.Configuration
	}{
		Logger:        logger,
		Configuration: configuration,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(logger, configuration)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedGenerator.GenerateCalls())
func (mock *GeneratorMock) GenerateCalls() []struct {
	Logger        logr.Logger
	Configuration dataplane.Configuration
} {
	var calls []struct {
		Logger        logr.Logger
		Configuration dataplane.Configuration
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// GenerateDeploymentContext calls GenerateDeploymentContextFunc.
func (mock *GeneratorMock) GenerateDeploymentContext(depCtx dataplane.DeploymentContext) (agent.File, error) {
	if mock.GenerateDeploymentContextFunc == nil {
		panic("GeneratorMock.GenerateDeploymentContextFunc: method is nil but Generator.GenerateDeploymentContext was just called")
	}
	callInfo := struct {
		DepCtx dataplane.DeploymentContext
	}{
		DepCtx: depCtx,
	}
	mock.lockGenerateDeploymentContext.Lock()
	mock.calls.GenerateDeploymentContext = append(mock.calls.GenerateDeploymentContext, callInfo)
	mock.lockGenerateDeploymentContext.Unlock()
	return mock.GenerateDeploymentContextFunc(depCtx)
}

// GenerateDeploymentContextCalls gets all the calls that were made to GenerateDeploymentContext.
// Check the length with:
//
//	len(mockedGenerator.GenerateDeploymentContextCalls())
func (mock *GeneratorMock) GenerateDeploymentContextCalls() []struct {
	DepCtx dataplane.DeploymentContext
} {
	var calls []struct {
		DepCtx dataplane.DeploymentContext
	}
	mock.lockGenerateDeploymentContext.RLock()
	calls = mock.calls.GenerateDeploymentContext
	mock.lockGenerateDeploymentContext.RUnlock()
	return calls
}
