// Code generated by counterfeiter. DO NOT EDIT.
package configfakes

import (
	"sync"

	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/config"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
)

type FakeGenerator struct {
	GenerateStub        func(logr.Logger, dataplane.Configuration) []agent.File
	generateMutex       sync.RWMutex
	generateArgsForCall []FakeGeneratorGenerateArgs
	generateReturns     struct {
		result1 []agent.File
	}
	generateReturnsOnCall map[int]struct {
		result1 []agent.File
	}
	GenerateDeploymentContextStub        func(dataplane.DeploymentContext) (agent.File, error)
	generateDeploymentContextMutex       sync.RWMutex
	generateDeploymentContextArgsForCall []FakeGeneratorGenerateDeploymentContextArgs
	generateDeploymentContextReturns     struct {
		result1 agent.File
		result2 error
	}
	generateDeploymentContextReturnsOnCall map[int]struct {
		result1 agent.File
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeGeneratorGenerateArgs holds the arguments of one call to Generate.
type FakeGeneratorGenerateArgs struct {
	Arg1 logr.Logger
	Arg2 dataplane.Configuration
}

// FakeGeneratorGenerateDeploymentContextArgs holds the arguments of one call to GenerateDeploymentContext.
type FakeGeneratorGenerateDeploymentContextArgs struct {
	Arg1 dataplane.DeploymentContext
}

func (fake *FakeGenerator) Generate(arg1 logr.Logger, arg2 dataplane.Configuration) []agent.File {
	fake.generateMutex.Lock()
	ret, specificReturn := fake.generateReturnsOnCall[len(fake.generateArgsForCall)]
	fake.generateArgsForCall = append(fake.generateArgsForCall, FakeGeneratorGenerateArgs{arg1, arg2})
	stub := fake.GenerateStub
	fakeReturns := fake.generateReturns
	fake.recordInvocation("Generate", []interface{}{arg1, arg2})
	fake.generateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGenerator) GenerateCallCount() int {
	fake.generateMutex.RLock()
	defer fake.generateMutex.RUnlock()
	return len(fake.generateArgsForCall)
}

func (fake *FakeGenerator) GenerateCalls(stub func(logr.Logger, dataplane.Configuration) []agent.File) {
	fake.generateMutex.Lock()
	defer fake.generateMutex.Unlock()
	fake.GenerateStub = stub
}

func (fake *FakeGenerator) GenerateArgsForCall(i int) (logr.Logger, dataplane.Configuration) {
	fake.generateMutex.RLock()
	defer fake.generateMutex.RUnlock()
	argsForCall := fake.generateArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeGenerator) GenerateArgs() []FakeGeneratorGenerateArgs {
	fake.generateMutex.RLock()
	defer fake.generateMutex.RUnlock()
	args := make([]FakeGeneratorGenerateArgs, len(fake.generateArgsForCall))
	copy(args, fake.generateArgsForCall)
	return args
}

func (fake *FakeGenerator) GenerateReturns(result1 []agent.File) {
	fake.generateMutex.Lock()
	defer fake.generateMutex.Unlock()
	fake.GenerateStub = nil
	fake.generateReturns = struct {
		result1 []agent.File
	}{result1}
}

func (fake *FakeGenerator) GenerateReturnsOnCall(i int, result1 []agent.File) {
	fake.generateMutex.Lock()
	defer fake.generateMutex.Unlock()
	fake.GenerateStub = nil
	if fake.generateReturnsOnCall == nil {
		fake.generateReturnsOnCall = make(map[int]struct {
			result1 []agent.File
		})
	}
	fake.generateReturnsOnCall[i] = struct {
		result1 []agent.File
	}{result1}
}

func (fake *FakeGenerator) GenerateDeploymentContext(arg1 dataplane.DeploymentContext) (agent.File, error) {
	fake.generateDeploymentContextMutex.Lock()
	ret, specificReturn := fake.generateDeploymentContextReturnsOnCall[len(fake.generateDeploymentContextArgsForCall)]
	fake.generateDeploymentContextArgsForCall = append(fake.generateDeploymentContextArgsForCall, FakeGeneratorGenerateDeploymentContextArgs{arg1})
	stub := fake.GenerateDeploymentContextStub
	fakeReturns := fake.generateDeploymentContextReturns
	fake.recordInvocation("GenerateDeploymentContext", []interface{}{arg1})
	fake.generateDeploymentContextMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGenerator) GenerateDeploymentContextCallCount() int {
	fake.generateDeploymentContextMutex.RLock()
	defer fake.generateDeploymentContextMutex.RUnlock()
	return len(fake.generateDeploymentContextArgsForCall)
}

func (fake *FakeGenerator) GenerateDeploymentContextCalls(stub func(dataplane.DeploymentContext) (agent.File, error)) {
	fake.generateDeploymentContextMutex.Lock()
	defer fake.generateDeploymentContextMutex.Unlock()
	fake.GenerateDeploymentContextStub = stub
}

func (fake *FakeGenerator) GenerateDeploymentContextArgsForCall(i int) dataplane.DeploymentContext {
	fake.generateDeploymentContextMutex.RLock()
	defer fake.generateDeploymentContextMutex.RUnlock()
	argsForCall := fake.generateDeploymentContextArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeGenerator) GenerateDeploymentContextArgs() []FakeGeneratorGenerateDeploymentContextArgs {
	fake.generateDeploymentContextMutex.RLock()
	defer fake.generateDeploymentContextMutex.RUnlock()
	args := make([]FakeGeneratorGenerateDeploymentContextArgs, len(fake.generateDeploymentContextArgsForCall))
	copy(args, fake.generateDeploymentContextArgsForCall)
	return args
}

func (fake *FakeGenerator) GenerateDeploymentContextReturns(result1 agent.File, result2 error) {
	fake.generateDeploymentContextMutex.Lock()
	defer fake.generateDeploymentContextMutex.Unlock()
	fake.GenerateDeploymentContextStub = nil
	fake.generateDeploymentContextReturns = struct {
		result1 agent.File
		result2 error
	}{result1, result2}
}

func (fake *FakeGenerator) GenerateDeploymentContextReturnsOnCall(i int, result1 agent.File, result2 error) {
	fake.generateDeploymentContextMutex.Lock()
	defer fake.generateDeploymentContextMutex.Unlock()
	fake.GenerateDeploymentContextStub = nil
	if fake.generateDeploymentContextReturnsOnCall == nil {
		fake.generateDeploymentContextReturnsOnCall = make(map[int]struct {
			result1 agent.File
			result2 error
		})
	}
	fake.generateDeploymentContextReturnsOnCall[i] = struct {
		result1 agent.File
		result2 error
	}{result1, result2}
}

func (fake *FakeGenerator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGenerator) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeGenerator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.Generator = new(FakeGenerator)
