[build]
  base = "site/"
  publish = "public"

[context.production]
  command = "make all"   

[context.docs-development]
  command = "make all-dev"

[context.docs-staging]
  command = "make all-staging"

[context.branch-deploy]
  command = "make deploy-preview"

[context.deploy-preview]
  command = "make deploy-preview"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"