apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: nginx-proxy-gatewaylink-ipam
spec:
  # GatewayLink configuration with IPAM integration
  # F5 IPAM Controller will allocate an IP from the pool
  # associated with this label
  gatewayLink:
    enabled: true
    ipamLabel: "production"

  # Use ClusterIP since BIG-IP handles external traffic routing
  kubernetes:
    service:
      type: ClusterIP

  # Configure Proxy Protocol to preserve client IPs from BIG-IP
  rewriteClientIP:
    mode: ProxyProtocol
    trustedAddresses:
      - type: CIDR
        value: "10.1.0.0/16"  # Adjust to your BIG-IP network
    setIPRecursively: false
