// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messengerfakes

import (
	"context"
	pb "github.com/nginx/agent/v3/api/grpc/mpi/v1"
	"sync"
)

// MessengerMock is a mock implementation of messenger.Messenger.
//
//	func TestSomethingThatUsesMessenger(t *testing.T) {
//
//		// make and configure a mocked messenger.Messenger
//		mockedMessenger := &MessengerMock{
//			ErrorsFunc: func() <-chan error {
//				panic("mock out the Errors method")
//			},
//			MessagesFunc: func() <-chan *pb.DataPlaneResponse {
//				panic("mock out the Messages method")
//			},
//			RunFunc: func(contextMoqParam context.Context)  {
//				panic("mock out the Run method")
//			},
//			SendFunc: func(contextMoqParam context.Context, managementPlaneRequest *pb.ManagementPlaneRequest) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedMessenger in code that requires messenger.Messenger
//		// and then make assertions.
//
//	}
type MessengerMock struct {
	// ErrorsFunc mocks the Errors method.
	ErrorsFunc func() <-chan error

	// MessagesFunc mocks the Messages method.
	MessagesFunc func() <-chan *pb.DataPlaneResponse

	// RunFunc mocks the Run method.
	RunFunc func(contextMoqParam context.Context)

	// SendFunc mocks the Send method.
	SendFunc func(contextMoqParam context.Context, managementPlaneRequest *pb.ManagementPlaneRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// Errors holds details about calls to the Errors method.
		Errors []struct {
		}
		// Messages holds details about calls to the Messages method.
		Messages []struct {
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ManagementPlaneRequest is the managementPlaneRequest argument value.
			ManagementPlaneRequest *pb.ManagementPlaneRequest
		}
	}
	lockErrors   sync.RWMutex
	lockMessages sync.RWMutex
	lockRun      sync.RWMutex
	lockSend     sync.RWMutex
}

// Errors calls ErrorsFunc.
func (mock *MessengerMock) Errors() <-chan error {
	if mock.ErrorsFunc == nil {
		panic("MessengerMock.ErrorsFunc: method is nil but Messenger.Errors was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErrors.Lock()
	mock.calls.Errors = append(mock.calls.Errors, callInfo)
	mock.lockErrors.Unlock()
	return mock.ErrorsFunc()
}

// ErrorsCalls gets all the calls that were made to Errors.
// Check the length with:
//
//	len(mockedMessenger.ErrorsCalls())
func (mock *MessengerMock) ErrorsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErrors.RLock()
	calls = mock.calls.Errors
	mock.lockErrors.RUnlock()
	return calls
}

// Messages calls MessagesFunc.
func (mock *MessengerMock) Messages() <-chan *pb.DataPlaneResponse {
	if mock.MessagesFunc == nil {
		panic("MessengerMock.MessagesFunc: method is nil but Messenger.Messages was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMessages.Lock()
	mock.calls.Messages = append(mock.calls.Messages, callInfo)
	mock.lockMessages.Unlock()
	return mock.MessagesFunc()
}

// MessagesCalls gets all the calls that were made to Messages.
// Check the length with:
//
//	len(mockedMessenger.MessagesCalls())
func (mock *MessengerMock) MessagesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMessages.RLock()
	calls = mock.calls.Messages
	mock.lockMessages.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *MessengerMock) Run(contextMoqParam context.Context) {
	if mock.RunFunc == nil {
		panic("MessengerMock.RunFunc: method is nil but Messenger.Run was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	mock.RunFunc(contextMoqParam)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedMessenger.RunCalls())
func (mock *MessengerMock) RunCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *MessengerMock) Send(contextMoqParam context.Context, managementPlaneRequest *pb.ManagementPlaneRequest) error {
	if mock.SendFunc == nil {
		panic("MessengerMock.SendFunc: method is nil but Messenger.Send was just called")
	}
	callInfo := struct {
		ContextMoqParam        context.Context
		ManagementPlaneRequest *pb.ManagementPlaneRequest
	}{
		ContextMoqParam:        contextMoqParam,
		ManagementPlaneRequest: managementPlaneRequest,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(contextMoqParam, managementPlaneRequest)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedMessenger.SendCalls())
func (mock *MessengerMock) SendCalls() []struct {
	ContextMoqParam        context.Context
	ManagementPlaneRequest *pb.ManagementPlaneRequest
} {
	var calls []struct {
		ContextMoqParam        context.Context
		ManagementPlaneRequest *pb.ManagementPlaneRequest
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
