nginxGateway:
  name: nginx-gateway

nginx:
  plus: true
  image:
    repository: private-registry.nginx.com/nginx-gateway-fabric/nginx-plus

serviceAccount:
  imagePullSecret: nginx-plus-registry-secret
