// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package telemetryfakes

import (
	"context"
	ngxTelemetry "github.com/nginx/telemetry-exporter/pkg/telemetry"
	"sync"
)

// ExporterMock is a mock implementation of telemetry.Exporter.
//
//	func TestSomethingThatUsesExporter(t *testing.T) {
//
//		// make and configure a mocked telemetry.Exporter
//		mockedExporter := &ExporterMock{
//			ExportFunc: func(ctx context.Context, data ngxTelemetry.Exportable) error {
//				panic("mock out the Export method")
//			},
//		}
//
//		// use mockedExporter in code that requires telemetry.Exporter
//		// and then make assertions.
//
//	}
type ExporterMock struct {
	// ExportFunc mocks the Export method.
	ExportFunc func(ctx context.Context, data ngxTelemetry.Exportable) error

	// calls tracks calls to the methods.
	calls struct {
		// Export holds details about calls to the Export method.
		Export []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data ngxTelemetry.Exportable
		}
	}
	lockExport sync.RWMutex
}

// Export calls ExportFunc.
func (mock *ExporterMock) Export(ctx context.Context, data ngxTelemetry.Exportable) error {
	if mock.ExportFunc == nil {
		panic("ExporterMock.ExportFunc: method is nil but Exporter.Export was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data ngxTelemetry.Exportable
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockExport.Lock()
	mock.calls.Export = append(mock.calls.Export, callInfo)
	mock.lockExport.Unlock()
	return mock.ExportFunc(ctx, data)
}

// ExportCalls gets all the calls that were made to Export.
// Check the length with:
//
//	len(mockedExporter.ExportCalls())
func (mock *ExporterMock) ExportCalls() []struct {
	Ctx  context.Context
	Data ngxTelemetry.Exportable
} {
	var calls []struct {
		Ctx  context.Context
		Data ngxTelemetry.Exportable
	}
	mock.lockExport.RLock()
	calls = mock.calls.Export
	mock.lockExport.RUnlock()
	return calls
}
