// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package telemetryfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	"sync"
)

// ConfigurationGetterMock is a mock implementation of telemetry.ConfigurationGetter.
//
//	func TestSomethingThatUsesConfigurationGetter(t *testing.T) {
//
//		// make and configure a mocked telemetry.ConfigurationGetter
//		mockedConfigurationGetter := &ConfigurationGetterMock{
//			GetLatestConfigurationFunc: func() []*dataplane.Configuration {
//				panic("mock out the GetLatestConfiguration method")
//			},
//		}
//
//		// use mockedConfigurationGetter in code that requires telemetry.ConfigurationGetter
//		// and then make assertions.
//
//	}
type ConfigurationGetterMock struct {
	// GetLatestConfigurationFunc mocks the GetLatestConfiguration method.
	GetLatestConfigurationFunc func() []*dataplane.Configuration

	// calls tracks calls to the methods.
	calls struct {
		// GetLatestConfiguration holds details about calls to the GetLatestConfiguration method.
		GetLatestConfiguration []struct {
		}
	}
	lockGetLatestConfiguration sync.RWMutex
}

// GetLatestConfiguration calls GetLatestConfigurationFunc.
func (mock *ConfigurationGetterMock) GetLatestConfiguration() []*dataplane.Configuration {
	if mock.GetLatestConfigurationFunc == nil {
		panic("ConfigurationGetterMock.GetLatestConfigurationFunc: method is nil but ConfigurationGetter.GetLatestConfiguration was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLatestConfiguration.Lock()
	mock.calls.GetLatestConfiguration = append(mock.calls.GetLatestConfiguration, callInfo)
	mock.lockGetLatestConfiguration.Unlock()
	return mock.GetLatestConfigurationFunc()
}

// GetLatestConfigurationCalls gets all the calls that were made to GetLatestConfiguration.
// Check the length with:
//
//	len(mockedConfigurationGetter.GetLatestConfigurationCalls())
func (mock *ConfigurationGetterMock) GetLatestConfigurationCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLatestConfiguration.RLock()
	calls = mock.calls.GetLatestConfiguration
	mock.lockGetLatestConfiguration.RUnlock()
	return calls
}
