// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package telemetryfakes

import (
	"context"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/telemetry"
	"sync"
)

// DataCollectorMock is a mock implementation of telemetry.DataCollector.
//
//	func TestSomethingThatUsesDataCollector(t *testing.T) {
//
//		// make and configure a mocked telemetry.DataCollector
//		mockedDataCollector := &DataCollectorMock{
//			CollectFunc: func(ctx context.Context) (telemetry.Data, error) {
//				panic("mock out the Collect method")
//			},
//		}
//
//		// use mockedDataCollector in code that requires telemetry.DataCollector
//		// and then make assertions.
//
//	}
type DataCollectorMock struct {
	// CollectFunc mocks the Collect method.
	CollectFunc func(ctx context.Context) (telemetry.Data, error)

	// calls tracks calls to the methods.
	calls struct {
		// Collect holds details about calls to the Collect method.
		Collect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCollect sync.RWMutex
}

// Collect calls CollectFunc.
func (mock *DataCollectorMock) Collect(ctx context.Context) (telemetry.Data, error) {
	if mock.CollectFunc == nil {
		panic("DataCollectorMock.CollectFunc: method is nil but DataCollector.Collect was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCollect.Lock()
	mock.calls.Collect = append(mock.calls.Collect, callInfo)
	mock.lockCollect.Unlock()
	return mock.CollectFunc(ctx)
}

// CollectCalls gets all the calls that were made to Collect.
// Check the length with:
//
//	len(mockedDataCollector.CollectCalls())
func (mock *DataCollectorMock) CollectCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCollect.RLock()
	calls = mock.calls.Collect
	mock.lockCollect.RUnlock()
	return calls
}
