// Code generated by counterfeiter. DO NOT EDIT.
package telemetryfakes

import (
	"context"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/telemetry"
)

type FakeDataCollector struct {
	CollectStub        func(context.Context) (telemetry.Data, error)
	collectMutex       sync.RWMutex
	collectArgsForCall []FakeDataCollectorCollectArgs
	collectReturns     struct {
		result1 telemetry.Data
		result2 error
	}
	collectReturnsOnCall map[int]struct {
		result1 telemetry.Data
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeDataCollectorCollectArgs holds the arguments of one call to Collect.
type FakeDataCollectorCollectArgs struct {
	Arg1 context.Context
}

func (fake *FakeDataCollector) Collect(arg1 context.Context) (telemetry.Data, error) {
	fake.collectMutex.Lock()
	ret, specificReturn := fake.collectReturnsOnCall[len(fake.collectArgsForCall)]
	fake.collectArgsForCall = append(fake.collectArgsForCall, FakeDataCollectorCollectArgs{arg1})
	stub := fake.CollectStub
	fakeReturns := fake.collectReturns
	fake.recordInvocation("Collect", []interface{}{arg1})
	fake.collectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDataCollector) CollectCallCount() int {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	return len(fake.collectArgsForCall)
}

func (fake *FakeDataCollector) CollectCalls(stub func(context.Context) (telemetry.Data, error)) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = stub
}

func (fake *FakeDataCollector) CollectArgsForCall(i int) context.Context {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	argsForCall := fake.collectArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeDataCollector) CollectArgs() []FakeDataCollectorCollectArgs {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	args := make([]FakeDataCollectorCollectArgs, len(fake.collectArgsForCall))
	copy(args, fake.collectArgsForCall)
	return args
}

func (fake *FakeDataCollector) CollectReturns(result1 telemetry.Data, result2 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	fake.collectReturns = struct {
		result1 telemetry.Data
		result2 error
	}{result1, result2}
}

func (fake *FakeDataCollector) CollectReturnsOnCall(i int, result1 telemetry.Data, result2 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	if fake.collectReturnsOnCall == nil {
		fake.collectReturnsOnCall = make(map[int]struct {
			result1 telemetry.Data
			result2 error
		})
	}
	fake.collectReturnsOnCall[i] = struct {
		result1 telemetry.Data
		result2 error
	}{result1, result2}
}

func (fake *FakeDataCollector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDataCollector) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeDataCollector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ telemetry.DataCollector = new(FakeDataCollector)
