// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"context"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"k8s.io/apimachinery/pkg/types"
)

type FakeDeploymentStorer struct {
	GetStub        func(types.NamespacedName) *agent.Deployment
	getMutex       sync.RWMutex
	getArgsForCall []FakeDeploymentStorerGetArgs
	getReturns     struct {
		result1 *agent.Deployment
	}
	getReturnsOnCall map[int]struct {
		result1 *agent.Deployment
	}
	LoadOrStoreStub        func(context.Context, types.NamespacedName, string) *agent.Deployment
	loadOrStoreMutex       sync.RWMutex
	loadOrStoreArgsForCall []FakeDeploymentStorerLoadOrStoreArgs
	loadOrStoreReturns     struct {
		result1 *agent.Deployment
	}
	loadOrStoreReturnsOnCall map[int]struct {
		result1 *agent.Deployment
	}
	RemoveStub        func(types.NamespacedName)
	removeMutex       sync.RWMutex
	removeArgsForCall []FakeDeploymentStorerRemoveArgs
	invocations       map[string][][]interface{}
	callOrder         []string
	invocationsMutex  sync.RWMutex
}

// FakeDeploymentStorerGetArgs holds the arguments of one call to Get.
type FakeDeploymentStorerGetArgs struct {
	Arg1 types.NamespacedName
}

// FakeDeploymentStorerLoadOrStoreArgs holds the arguments of one call to LoadOrStore.
type FakeDeploymentStorerLoadOrStoreArgs struct {
	Arg1 context.Context
	Arg2 types.NamespacedName
	Arg3 string
}

// FakeDeploymentStorerRemoveArgs holds the arguments of one call to Remove.
type FakeDeploymentStorerRemoveArgs struct {
	Arg1 types.NamespacedName
}

func (fake *FakeDeploymentStorer) Get(arg1 types.NamespacedName) *agent.Deployment {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, FakeDeploymentStorerGetArgs{arg1})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDeploymentStorer) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeDeploymentStorer) GetCalls(stub func(types.NamespacedName) *agent.Deployment) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeDeploymentStorer) GetArgsForCall(i int) types.NamespacedName {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeDeploymentStorer) GetArgs() []FakeDeploymentStorerGetArgs {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	args := make([]FakeDeploymentStorerGetArgs, len(fake.getArgsForCall))
	copy(args, fake.getArgsForCall)
	return args
}

func (fake *FakeDeploymentStorer) GetReturns(result1 *agent.Deployment) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *agent.Deployment
	}{result1}
}

func (fake *FakeDeploymentStorer) GetReturnsOnCall(i int, result1 *agent.Deployment) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *agent.Deployment
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *agent.Deployment
	}{result1}
}

func (fake *FakeDeploymentStorer) LoadOrStore(arg1 context.Context, arg2 types.NamespacedName, arg3 string) *agent.Deployment {
	fake.loadOrStoreMutex.Lock()
	ret, specificReturn := fake.loadOrStoreReturnsOnCall[len(fake.loadOrStoreArgsForCall)]
	fake.loadOrStoreArgsForCall = append(fake.loadOrStoreArgsForCall, FakeDeploymentStorerLoadOrStoreArgs{arg1, arg2, arg3})
	stub := fake.LoadOrStoreStub
	fakeReturns := fake.loadOrStoreReturns
	fake.recordInvocation("LoadOrStore", []interface{}{arg1, arg2, arg3})
	fake.loadOrStoreMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDeploymentStorer) LoadOrStoreCallCount() int {
	fake.loadOrStoreMutex.RLock()
	defer fake.loadOrStoreMutex.RUnlock()
	return len(fake.loadOrStoreArgsForCall)
}

func (fake *FakeDeploymentStorer) LoadOrStoreCalls(stub func(context.Context, types.NamespacedName, string) *agent.Deployment) {
	fake.loadOrStoreMutex.Lock()
	defer fake.loadOrStoreMutex.Unlock()
	fake.LoadOrStoreStub = stub
}

func (fake *FakeDeploymentStorer) LoadOrStoreArgsForCall(i int) (context.Context, types.NamespacedName, string) {
	fake.loadOrStoreMutex.RLock()
	defer fake.loadOrStoreMutex.RUnlock()
	argsForCall := fake.loadOrStoreArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeDeploymentStorer) LoadOrStoreArgs() []FakeDeploymentStorerLoadOrStoreArgs {
	fake.loadOrStoreMutex.RLock()
	defer fake.loadOrStoreMutex.RUnlock()
	args := make([]FakeDeploymentStorerLoadOrStoreArgs, len(fake.loadOrStoreArgsForCall))
	copy(args, fake.loadOrStoreArgsForCall)
	return args
}

func (fake *FakeDeploymentStorer) LoadOrStoreReturns(result1 *agent.Deployment) {
	fake.loadOrStoreMutex.Lock()
	defer fake.loadOrStoreMutex.Unlock()
	fake.LoadOrStoreStub = nil
	fake.loadOrStoreReturns = struct {
		result1 *agent.Deployment
	}{result1}
}

func (fake *FakeDeploymentStorer) LoadOrStoreReturnsOnCall(i int, result1 *agent.Deployment) {
	fake.loadOrStoreMutex.Lock()
	defer fake.loadOrStoreMutex.Unlock()
	fake.LoadOrStoreStub = nil
	if fake.loadOrStoreReturnsOnCall == nil {
		fake.loadOrStoreReturnsOnCall = make(map[int]struct {
			result1 *agent.Deployment
		})
	}
	fake.loadOrStoreReturnsOnCall[i] = struct {
		result1 *agent.Deployment
	}{result1}
}

func (fake *FakeDeploymentStorer) Remove(arg1 types.NamespacedName) {
	fake.removeMutex.Lock()
	fake.removeArgsForCall = append(fake.removeArgsForCall, FakeDeploymentStorerRemoveArgs{arg1})
	stub := fake.RemoveStub
	fake.recordInvocation("Remove", []interface{}{arg1})
	fake.removeMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *FakeDeploymentStorer) RemoveCallCount() int {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return len(fake.removeArgsForCall)
}

func (fake *FakeDeploymentStorer) RemoveCalls(stub func(types.NamespacedName)) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = stub
}

func (fake *FakeDeploymentStorer) RemoveArgsForCall(i int) types.NamespacedName {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	argsForCall := fake.removeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeDeploymentStorer) RemoveArgs() []FakeDeploymentStorerRemoveArgs {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	args := make([]FakeDeploymentStorerRemoveArgs, len(fake.removeArgsForCall))
	copy(args, fake.removeArgsForCall)
	return args
}

func (fake *FakeDeploymentStorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeploymentStorer) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeDeploymentStorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.DeploymentStorer = new(FakeDeploymentStorer)
