// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	v1 "k8s.io/api/core/v1"
)

type FakeNginxUpdater struct {
	UpdateConfigStub        func(*agent.Deployment, []agent.File, []v1.VolumeMount) bool
	updateConfigMutex       sync.RWMutex
	updateConfigArgsForCall []struct {
		arg1 *agent.Deployment
		arg2 []agent.File
		arg3 []v1.VolumeMount
	}
	updateConfigReturns struct {
		result1 bool
	}
	updateConfigReturnsOnCall map[int]struct {
		result1 bool
	}
	UpdateUpstreamServersStub        func(*agent.Deployment, dataplane.Configuration)
	updateUpstreamServersMutex       sync.RWMutex
	updateUpstreamServersArgsForCall []struct {
		arg1 *agent.Deployment
		arg2 dataplane.Configuration
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNginxUpdater) UpdateConfig(arg1 *agent.Deployment, arg2 []agent.File, arg3 []v1.VolumeMount) bool {
	var arg2Copy []agent.File
	if arg2 != nil {
		arg2Copy = make([]agent.File, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg3Copy []v1.VolumeMount
	if arg3 != nil {
		arg3Copy = make([]v1.VolumeMount, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.updateConfigMutex.Lock()
	ret, specificReturn := fake.updateConfigReturnsOnCall[len(fake.updateConfigArgsForCall)]
	fake.updateConfigArgsForCall = append(fake.updateConfigArgsForCall, struct {
		arg1 *agent.Deployment
		arg2 []agent.File
		arg3 []v1.VolumeMount
	}{arg1, arg2Copy, arg3Copy})
	stub := fake.UpdateConfigStub
	fakeReturns := fake.updateConfigReturns
	fake.recordInvocation("UpdateConfig", []interface{}{arg1, arg2Copy, arg3Copy})
	fake.updateConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNginxUpdater) UpdateConfigCallCount() int {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	return len(fake.updateConfigArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateConfigCalls(stub func(*agent.Deployment, []agent.File, []v1.VolumeMount) bool) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = stub
}

func (fake *FakeNginxUpdater) UpdateConfigArgsForCall(i int) (*agent.Deployment, []agent.File, []v1.VolumeMount) {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	argsForCall := fake.updateConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeNginxUpdater) UpdateConfigReturns(result1 bool) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = nil
	fake.updateConfigReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeNginxUpdater) UpdateConfigReturnsOnCall(i int, result1 bool) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = nil
	if fake.updateConfigReturnsOnCall == nil {
		fake.updateConfigReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.updateConfigReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeNginxUpdater) UpdateUpstreamServers(arg1 *agent.Deployment, arg2 dataplane.Configuration) {
	fake.updateUpstreamServersMutex.Lock()
	fake.updateUpstreamServersArgsForCall = append(fake.updateUpstreamServersArgsForCall, struct {
		arg1 *agent.Deployment
		arg2 dataplane.Configuration
	}{arg1, arg2})
	stub := fake.UpdateUpstreamServersStub
	fake.recordInvocation("UpdateUpstreamServers", []interface{}{arg1, arg2})
	fake.updateUpstreamServersMutex.Unlock()
	if stub != nil {
		fake.UpdateUpstreamServersStub(arg1, arg2)
	}
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCallCount() int {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	return len(fake.updateUpstreamServersArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCalls(stub func(*agent.Deployment, dataplane.Configuration)) {
	fake.updateUpstreamServersMutex.Lock()
	defer fake.updateUpstreamServersMutex.Unlock()
	fake.UpdateUpstreamServersStub = stub
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersArgsForCall(i int) (*agent.Deployment, dataplane.Configuration) {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	argsForCall := fake.updateUpstreamServersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNginxUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNginxUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.NginxUpdater = new(FakeNginxUpdater)
