// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	v1 "k8s.io/api/core/v1"
)

type FakeNginxUpdater struct {
	UpdateConfigStub                 func(*agent.Deployment, []agent.File, []v1.VolumeMount)
	updateConfigMutex                sync.RWMutex
	updateConfigArgsForCall          []FakeNginxUpdaterUpdateConfigArgs
	UpdateUpstreamServersStub        func(*agent.Deployment, dataplane.Configuration)
	updateUpstreamServersMutex       sync.RWMutex
	updateUpstreamServersArgsForCall []FakeNginxUpdaterUpdateUpstreamServersArgs
	invocations                      map[string][][]interface{}
	callOrder                        []string
	invocationsMutex                 sync.RWMutex
}

// FakeNginxUpdaterUpdateConfigArgs holds the arguments of one call to UpdateConfig.
type FakeNginxUpdaterUpdateConfigArgs struct {
	Arg1 *agent.Deployment
	Arg2 []agent.File
	Arg3 []v1.VolumeMount
}

// FakeNginxUpdaterUpdateUpstreamServersArgs holds the arguments of one call to UpdateUpstreamServers.
type FakeNginxUpdaterUpdateUpstreamServersArgs struct {
	Arg1 *agent.Deployment
	Arg2 dataplane.Configuration
}

func (fake *FakeNginxUpdater) UpdateConfig(arg1 *agent.Deployment, arg2 []agent.File, arg3 []v1.VolumeMount) {
	var arg2Copy []agent.File
	if arg2 != nil {
		arg2Copy = make([]agent.File, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg3Copy []v1.VolumeMount
	if arg3 != nil {
		arg3Copy = make([]v1.VolumeMount, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.updateConfigMutex.Lock()
	fake.updateConfigArgsForCall = append(fake.updateConfigArgsForCall, FakeNginxUpdaterUpdateConfigArgs{arg1, arg2Copy, arg3Copy})
	stub := fake.UpdateConfigStub
	fake.recordInvocation("UpdateConfig", []interface{}{arg1, arg2Copy, arg3Copy})
	fake.updateConfigMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2, arg3)
	}
}

func (fake *FakeNginxUpdater) UpdateConfigCallCount() int {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	return len(fake.updateConfigArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateConfigCalls(stub func(*agent.Deployment, []agent.File, []v1.VolumeMount)) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = stub
}

func (fake *FakeNginxUpdater) UpdateConfigArgsForCall(i int) (*agent.Deployment, []agent.File, []v1.VolumeMount) {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	argsForCall := fake.updateConfigArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeNginxUpdater) UpdateConfigArgs() []FakeNginxUpdaterUpdateConfigArgs {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	args := make([]FakeNginxUpdaterUpdateConfigArgs, len(fake.updateConfigArgsForCall))
	copy(args, fake.updateConfigArgsForCall)
	return args
}

func (fake *FakeNginxUpdater) UpdateUpstreamServers(arg1 *agent.Deployment, arg2 dataplane.Configuration) {
	fake.updateUpstreamServersMutex.Lock()
	fake.updateUpstreamServersArgsForCall = append(fake.updateUpstreamServersArgsForCall, FakeNginxUpdaterUpdateUpstreamServersArgs{arg1, arg2})
	stub := fake.UpdateUpstreamServersStub
	fake.recordInvocation("UpdateUpstreamServers", []interface{}{arg1, arg2})
	fake.updateUpstreamServersMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCallCount() int {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	return len(fake.updateUpstreamServersArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCalls(stub func(*agent.Deployment, dataplane.Configuration)) {
	fake.updateUpstreamServersMutex.Lock()
	defer fake.updateUpstreamServersMutex.Unlock()
	fake.UpdateUpstreamServersStub = stub
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersArgsForCall(i int) (*agent.Deployment, dataplane.Configuration) {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	argsForCall := fake.updateUpstreamServersArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersArgs() []FakeNginxUpdaterUpdateUpstreamServersArgs {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	args := make([]FakeNginxUpdaterUpdateUpstreamServersArgs, len(fake.updateUpstreamServersArgsForCall))
	copy(args, fake.updateUpstreamServersArgsForCall)
	return args
}

func (fake *FakeNginxUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNginxUpdater) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeNginxUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.NginxUpdater = new(FakeNginxUpdater)
