// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package agentfakes

import (
	"context"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"k8s.io/apimachinery/pkg/types"
	"sync"
)

// DeploymentStorerMock is a mock implementation of agent.DeploymentStorer.
//
//	func TestSomethingThatUsesDeploymentStorer(t *testing.T) {
//
//		// make and configure a mocked agent.DeploymentStorer
//		mockedDeploymentStorer := &DeploymentStorerMock{
//			GetFunc: func(namespacedName types.NamespacedName) *agent.Deployment {
//				panic("mock out the Get method")
//			},
//			LoadOrStoreFunc: func(contextMoqParam context.Context, namespacedName types.NamespacedName, s string) *agent.Deployment {
//				panic("mock out the LoadOrStore method")
//			},
//			RemoveFunc: func(namespacedName types.NamespacedName)  {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedDeploymentStorer in code that requires agent.DeploymentStorer
//		// and then make assertions.
//
//	}
type DeploymentStorerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespacedName types.NamespacedName) *agent.Deployment

	// LoadOrStoreFunc mocks the LoadOrStore method.
	LoadOrStoreFunc func(contextMoqParam context.Context, namespacedName types.NamespacedName, s string) *agent.Deployment

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(namespacedName types.NamespacedName)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// NamespacedName is the namespacedName argument value.
			NamespacedName types.NamespacedName
		}
		// LoadOrStore holds details about calls to the LoadOrStore method.
		LoadOrStore []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// NamespacedName is the namespacedName argument value.
			NamespacedName types.NamespacedName
			// S is the s argument value.
			S string
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// NamespacedName is the namespacedName argument value.
			NamespacedName types.NamespacedName
		}
	}
	lockGet         sync.RWMutex
	lockLoadOrStore sync.RWMutex
	lockRemove      sync.RWMutex
}

// Get calls GetFunc.
func (mock *DeploymentStorerMock) Get(namespacedName types.NamespacedName) *agent.Deployment {
	if mock.GetFunc == nil {
		panic("DeploymentStorerMock.GetFunc: method is nil but DeploymentStorer.Get was just called")
	}
	callInfo := struct {
		NamespacedName types.NamespacedName
	}{
		NamespacedName: namespacedName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(namespacedName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedDeploymentStorer.GetCalls())
func (mock *DeploymentStorerMock) GetCalls() []struct {
	NamespacedName types.NamespacedName
} {
	var calls []struct {
		NamespacedName types.NamespacedName
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// LoadOrStore calls LoadOrStoreFunc.
func (mock *DeploymentStorerMock) LoadOrStore(contextMoqParam context.Context, namespacedName types.NamespacedName, s string) *agent.Deployment {
	if mock.LoadOrStoreFunc == nil {
		panic("DeploymentStorerMock.LoadOrStoreFunc: method is nil but DeploymentStorer.LoadOrStore was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		NamespacedName  types.NamespacedName
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		NamespacedName:  namespacedName,
		S:               s,
	}
	mock.lockLoadOrStore.Lock()
	mock.calls.LoadOrStore = append(mock.calls.LoadOrStore, callInfo)
	mock.lockLoadOrStore.Unlock()
	return mock.LoadOrStoreFunc(contextMoqParam, namespacedName, s)
}

// LoadOrStoreCalls gets all the calls that were made to LoadOrStore.
// Check the length with:
//
//	len(mockedDeploymentStorer.LoadOrStoreCalls())
func (mock *DeploymentStorerMock) LoadOrStoreCalls() []struct {
	ContextMoqParam context.Context
	NamespacedName  types.NamespacedName
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		NamespacedName  types.NamespacedName
		S               string
	}
	mock.lockLoadOrStore.RLock()
	calls = mock.calls.LoadOrStore
	mock.lockLoadOrStore.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *DeploymentStorerMock) Remove(namespacedName types.NamespacedName) {
	if mock.RemoveFunc == nil {
		panic("DeploymentStorerMock.RemoveFunc: method is nil but DeploymentStorer.Remove was just called")
	}
	callInfo := struct {
		NamespacedName types.NamespacedName
	}{
		NamespacedName: namespacedName,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	mock.RemoveFunc(namespacedName)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedDeploymentStorer.RemoveCalls())
func (mock *DeploymentStorerMock) RemoveCalls() []struct {
	NamespacedName types.NamespacedName
} {
	var calls []struct {
		NamespacedName types.NamespacedName
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
