// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package agentfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	v1 "k8s.io/api/core/v1"
	"sync"
)

// NginxUpdaterMock is a mock implementation of agent.NginxUpdater.
//
//	func TestSomethingThatUsesNginxUpdater(t *testing.T) {
//
//		// make and configure a mocked agent.NginxUpdater
//		mockedNginxUpdater := &NginxUpdaterMock{
//			UpdateConfigFunc: func(deployment *agent.Deployment, files []agent.File, volumeMounts []v1.VolumeMount)  {
//				panic("mock out the UpdateConfig method")
//			},
//			UpdateUpstreamServersFunc: func(deployment *agent.Deployment, conf dataplane.Configuration)  {
//				panic("mock out the UpdateUpstreamServers method")
//			},
//		}
//
//		// use mockedNginxUpdater in code that requires agent.NginxUpdater
//		// and then make assertions.
//
//	}
type NginxUpdaterMock struct {
	// UpdateConfigFunc mocks the UpdateConfig method.
	UpdateConfigFunc func(deployment *agent.Deployment, files []agent.File, volumeMounts []v1.VolumeMount)

	// UpdateUpstreamServersFunc mocks the UpdateUpstreamServers method.
	UpdateUpstreamServersFunc func(deployment *agent.Deployment, conf dataplane.Configuration)

	// calls tracks calls to the methods.
	calls struct {
		// UpdateConfig holds details about calls to the UpdateConfig method.
		UpdateConfig []struct {
			// Deployment is the deployment argument value.
			Deployment *agent.Deployment
			// Files is the files argument value.
			Files []agent.File
			// VolumeMounts is the volumeMounts argument value.
			VolumeMounts []v1.VolumeMount
		}
		// UpdateUpstreamServers holds details about calls to the UpdateUpstreamServers method.
		UpdateUpstreamServers []struct {
			// Deployment is the deployment argument value.
			Deployment *agent.Deployment
			// Conf is the conf argument value.
			Conf dataplane.Configuration
		}
	}
	lockUpdateConfig          sync.RWMutex
	lockUpdateUpstreamServers sync.RWMutex
}

// UpdateConfig calls UpdateConfigFunc.
func (mock *NginxUpdaterMock) UpdateConfig(deployment *agent.Deployment, files []agent.File, volumeMounts []v1.VolumeMount) {
	if mock.UpdateConfigFunc == nil {
		panic("NginxUpdaterMock.UpdateConfigFunc: method is nil but NginxUpdater.UpdateConfig was just called")
	}
	callInfo := struct {
		Deployment   *agent.Deployment
		Files        []agent.File
		VolumeMounts []v1.VolumeMount
	}{
		Deployment:   deployment,
		Files:        files,
		VolumeMounts: volumeMounts,
	}
	mock.lockUpdateConfig.Lock()
	mock.calls.UpdateConfig = append(mock.calls.UpdateConfig, callInfo)
	mock.lockUpdateConfig.Unlock()
	mock.UpdateConfigFunc(deployment, files, volumeMounts)
}

// UpdateConfigCalls gets all the calls that were made to UpdateConfig.
// Check the length with:
//
//	len(mockedNginxUpdater.UpdateConfigCalls())
func (mock *NginxUpdaterMock) UpdateConfigCalls() []struct {
	Deployment   *agent.Deployment
	Files        []agent.File
	VolumeMounts []v1.VolumeMount
} {
	var calls []struct {
		Deployment   *agent.Deployment
		Files        []agent.File
		VolumeMounts []v1.VolumeMount
	}
	mock.lockUpdateConfig.RLock()
	calls = mock.calls.UpdateConfig
	mock.lockUpdateConfig.RUnlock()
	return calls
}

// UpdateUpstreamServers calls UpdateUpstreamServersFunc.
func (mock *NginxUpdaterMock) UpdateUpstreamServers(deployment *agent.Deployment, conf dataplane.Configuration) {
	if mock.UpdateUpstreamServersFunc == nil {
		panic("NginxUpdaterMock.UpdateUpstreamServersFunc: method is nil but NginxUpdater.UpdateUpstreamServers was just called")
	}
	callInfo := struct {
		Deployment *agent.Deployment
		Conf       dataplane.Configuration
	}{
		Deployment: deployment,
		Conf:       conf,
	}
	mock.lockUpdateUpstreamServers.Lock()
	mock.calls.UpdateUpstreamServers = append(mock.calls.UpdateUpstreamServers, callInfo)
	mock.lockUpdateUpstreamServers.Unlock()
	mock.UpdateUpstreamServersFunc(deployment, conf)
}

// UpdateUpstreamServersCalls gets all the calls that were made to UpdateUpstreamServers.
// Check the length with:
//
//	len(mockedNginxUpdater.UpdateUpstreamServersCalls())
func (mock *NginxUpdaterMock) UpdateUpstreamServersCalls() []struct {
	Deployment *agent.Deployment
	Conf       dataplane.Configuration
} {
	var calls []struct {
		Deployment *agent.Deployment
		Conf       dataplane.Configuration
	}
	mock.lockUpdateUpstreamServers.RLock()
	calls = mock.calls.UpdateUpstreamServers
	mock.lockUpdateUpstreamServers.RUnlock()
	return calls
}
