// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package broadcastfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent/broadcast"
	"sync"
)

// BroadcasterMock is a mock implementation of broadcast.Broadcaster.
//
//	func TestSomethingThatUsesBroadcaster(t *testing.T) {
//
//		// make and configure a mocked broadcast.Broadcaster
//		mockedBroadcaster := &BroadcasterMock{
//			CancelSubscriptionFunc: func(s string)  {
//				panic("mock out the CancelSubscription method")
//			},
//			SendFunc: func(nginxAgentMessage broadcast.NginxAgentMessage) bool {
//				panic("mock out the Send method")
//			},
//			SubscribeFunc: func() broadcast.SubscriberChannels {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedBroadcaster in code that requires broadcast.Broadcaster
//		// and then make assertions.
//
//	}
type BroadcasterMock struct {
	// CancelSubscriptionFunc mocks the CancelSubscription method.
	CancelSubscriptionFunc func(s string)

	// SendFunc mocks the Send method.
	SendFunc func(nginxAgentMessage broadcast.NginxAgentMessage) bool

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func() broadcast.SubscriberChannels

	// calls tracks calls to the methods.
	calls struct {
		// CancelSubscription holds details about calls to the CancelSubscription method.
		CancelSubscription []struct {
			// S is the s argument value.
			S string
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// NginxAgentMessage is the nginxAgentMessage argument value.
			NginxAgentMessage broadcast.NginxAgentMessage
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
		}
	}
	lockCancelSubscription sync.RWMutex
	lockSend               sync.RWMutex
	lockSubscribe          sync.RWMutex
}

// CancelSubscription calls CancelSubscriptionFunc.
func (mock *BroadcasterMock) CancelSubscription(s string) {
	if mock.CancelSubscriptionFunc == nil {
		panic("BroadcasterMock.CancelSubscriptionFunc: method is nil but Broadcaster.CancelSubscription was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockCancelSubscription.Lock()
	mock.calls.CancelSubscription = append(mock.calls.CancelSubscription, callInfo)
	mock.lockCancelSubscription.Unlock()
	mock.CancelSubscriptionFunc(s)
}

// CancelSubscriptionCalls gets all the calls that were made to CancelSubscription.
// Check the length with:
//
//	len(mockedBroadcaster.CancelSubscriptionCalls())
func (mock *BroadcasterMock) CancelSubscriptionCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockCancelSubscription.RLock()
	calls = mock.calls.CancelSubscription
	mock.lockCancelSubscription.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *BroadcasterMock) Send(nginxAgentMessage broadcast.NginxAgentMessage) bool {
	if mock.SendFunc == nil {
		panic("BroadcasterMock.SendFunc: method is nil but Broadcaster.Send was just called")
	}
	callInfo := struct {
		NginxAgentMessage broadcast.NginxAgentMessage
	}{
		NginxAgentMessage: nginxAgentMessage,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(nginxAgentMessage)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedBroadcaster.SendCalls())
func (mock *BroadcasterMock) SendCalls() []struct {
	NginxAgentMessage broadcast.NginxAgentMessage
} {
	var calls []struct {
		NginxAgentMessage broadcast.NginxAgentMessage
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *BroadcasterMock) Subscribe() broadcast.SubscriberChannels {
	if mock.SubscribeFunc == nil {
		panic("BroadcasterMock.SubscribeFunc: method is nil but Broadcaster.Subscribe was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc()
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedBroadcaster.SubscribeCalls())
func (mock *BroadcasterMock) SubscribeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
