// Code generated by counterfeiter. DO NOT EDIT.
package grpcfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent/grpc"
)

type FakeConnectionsTracker struct {
	GetConnectionStub        func(string) grpc.Connection
	getConnectionMutex       sync.RWMutex
	getConnectionArgsForCall []FakeConnectionsTrackerGetConnectionArgs
	getConnectionReturns     struct {
		result1 grpc.Connection
	}
	getConnectionReturnsOnCall map[int]struct {
		result1 grpc.Connection
	}
	RemoveConnectionStub        func(string)
	removeConnectionMutex       sync.RWMutex
	removeConnectionArgsForCall []FakeConnectionsTrackerRemoveConnectionArgs
	SetInstanceIDStub           func(string, string)
	setInstanceIDMutex          sync.RWMutex
	setInstanceIDArgsForCall    []FakeConnectionsTrackerSetInstanceIDArgs
	TrackStub                   func(string, grpc.Connection)
	trackMutex                  sync.RWMutex
	trackArgsForCall            []FakeConnectionsTrackerTrackArgs
	invocations                 map[string][][]interface{}
	callOrder                   []string
	invocationsMutex            sync.RWMutex
}

// FakeConnectionsTrackerGetConnectionArgs holds the arguments of one call to GetConnection.
type FakeConnectionsTrackerGetConnectionArgs struct {
	Arg1 string
}

// FakeConnectionsTrackerRemoveConnectionArgs holds the arguments of one call to RemoveConnection.
type FakeConnectionsTrackerRemoveConnectionArgs struct {
	Arg1 string
}

// FakeConnectionsTrackerSetInstanceIDArgs holds the arguments of one call to SetInstanceID.
type FakeConnectionsTrackerSetInstanceIDArgs struct {
	Arg1 string
	Arg2 string
}

// FakeConnectionsTrackerTrackArgs holds the arguments of one call to Track.
type FakeConnectionsTrackerTrackArgs struct {
	Arg1 string
	Arg2 grpc.Connection
}

func (fake *FakeConnectionsTracker) GetConnection(arg1 string) grpc.Connection {
	fake.getConnectionMutex.Lock()
	ret, specificReturn := fake.getConnectionReturnsOnCall[len(fake.getConnectionArgsForCall)]
	fake.getConnectionArgsForCall = append(fake.getConnectionArgsForCall, FakeConnectionsTrackerGetConnectionArgs{arg1})
	stub := fake.GetConnectionStub
	fakeReturns := fake.getConnectionReturns
	fake.recordInvocation("GetConnection", []interface{}{arg1})
	fake.getConnectionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConnectionsTracker) GetConnectionCallCount() int {
	fake.getConnectionMutex.RLock()
	defer fake.getConnectionMutex.RUnlock()
	return len(fake.getConnectionArgsForCall)
}

func (fake *FakeConnectionsTracker) GetConnectionCalls(stub func(string) grpc.Connection) {
	fake.getConnectionMutex.Lock()
	defer fake.getConnectionMutex.Unlock()
	fake.GetConnectionStub = stub
}

func (fake *FakeConnectionsTracker) GetConnectionArgsForCall(i int) string {
	fake.getConnectionMutex.RLock()
	defer fake.getConnectionMutex.RUnlock()
	argsForCall := fake.getConnectionArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeConnectionsTracker) GetConnectionArgs() []FakeConnectionsTrackerGetConnectionArgs {
	fake.getConnectionMutex.RLock()
	defer fake.getConnectionMutex.RUnlock()
	args := make([]FakeConnectionsTrackerGetConnectionArgs, len(fake.getConnectionArgsForCall))
	copy(args, fake.getConnectionArgsForCall)
	return args
}

func (fake *FakeConnectionsTracker) GetConnectionReturns(result1 grpc.Connection) {
	fake.getConnectionMutex.Lock()
	defer fake.getConnectionMutex.Unlock()
	fake.GetConnectionStub = nil
	fake.getConnectionReturns = struct {
		result1 grpc.Connection
	}{result1}
}

func (fake *FakeConnectionsTracker) GetConnectionReturnsOnCall(i int, result1 grpc.Connection) {
	fake.getConnectionMutex.Lock()
	defer fake.getConnectionMutex.Unlock()
	fake.GetConnectionStub = nil
	if fake.getConnectionReturnsOnCall == nil {
		fake.getConnectionReturnsOnCall = make(map[int]struct {
			result1 grpc.Connection
		})
	}
	fake.getConnectionReturnsOnCall[i] = struct {
		result1 grpc.Connection
	}{result1}
}

func (fake *FakeConnectionsTracker) RemoveConnection(arg1 string) {
	fake.removeConnectionMutex.Lock()
	fake.removeConnectionArgsForCall = append(fake.removeConnectionArgsForCall, FakeConnectionsTrackerRemoveConnectionArgs{arg1})
	stub := fake.RemoveConnectionStub
	fake.recordInvocation("RemoveConnection", []interface{}{arg1})
	fake.removeConnectionMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *FakeConnectionsTracker) RemoveConnectionCallCount() int {
	fake.removeConnectionMutex.RLock()
	defer fake.removeConnectionMutex.RUnlock()
	return len(fake.removeConnectionArgsForCall)
}

func (fake *FakeConnectionsTracker) RemoveConnectionCalls(stub func(string)) {
	fake.removeConnectionMutex.Lock()
	defer fake.removeConnectionMutex.Unlock()
	fake.RemoveConnectionStub = stub
}

func (fake *FakeConnectionsTracker) RemoveConnectionArgsForCall(i int) string {
	fake.removeConnectionMutex.RLock()
	defer fake.removeConnectionMutex.RUnlock()
	argsForCall := fake.removeConnectionArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeConnectionsTracker) RemoveConnectionArgs() []FakeConnectionsTrackerRemoveConnectionArgs {
	fake.removeConnectionMutex.RLock()
	defer fake.removeConnectionMutex.RUnlock()
	args := make([]FakeConnectionsTrackerRemoveConnectionArgs, len(fake.removeConnectionArgsForCall))
	copy(args, fake.removeConnectionArgsForCall)
	return args
}

func (fake *FakeConnectionsTracker) SetInstanceID(arg1 string, arg2 string) {
	fake.setInstanceIDMutex.Lock()
	fake.setInstanceIDArgsForCall = append(fake.setInstanceIDArgsForCall, FakeConnectionsTrackerSetInstanceIDArgs{arg1, arg2})
	stub := fake.SetInstanceIDStub
	fake.recordInvocation("SetInstanceID", []interface{}{arg1, arg2})
	fake.setInstanceIDMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *FakeConnectionsTracker) SetInstanceIDCallCount() int {
	fake.setInstanceIDMutex.RLock()
	defer fake.setInstanceIDMutex.RUnlock()
	return len(fake.setInstanceIDArgsForCall)
}

func (fake *FakeConnectionsTracker) SetInstanceIDCalls(stub func(string, string)) {
	fake.setInstanceIDMutex.Lock()
	defer fake.setInstanceIDMutex.Unlock()
	fake.SetInstanceIDStub = stub
}

func (fake *FakeConnectionsTracker) SetInstanceIDArgsForCall(i int) (string, string) {
	fake.setInstanceIDMutex.RLock()
	defer fake.setInstanceIDMutex.RUnlock()
	argsForCall := fake.setInstanceIDArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeConnectionsTracker) SetInstanceIDArgs() []FakeConnectionsTrackerSetInstanceIDArgs {
	fake.setInstanceIDMutex.RLock()
	defer fake.setInstanceIDMutex.RUnlock()
	args := make([]FakeConnectionsTrackerSetInstanceIDArgs, len(fake.setInstanceIDArgsForCall))
	copy(args, fake.setInstanceIDArgsForCall)
	return args
}

func (fake *FakeConnectionsTracker) Track(arg1 string, arg2 grpc.Connection) {
	fake.trackMutex.Lock()
	fake.trackArgsForCall = append(fake.trackArgsForCall, FakeConnectionsTrackerTrackArgs{arg1, arg2})
	stub := fake.TrackStub
	fake.recordInvocation("Track", []interface{}{arg1, arg2})
	fake.trackMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *FakeConnectionsTracker) TrackCallCount() int {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	return len(fake.trackArgsForCall)
}

func (fake *FakeConnectionsTracker) TrackCalls(stub func(string, grpc.Connection)) {
	fake.trackMutex.Lock()
	defer fake.trackMutex.Unlock()
	fake.TrackStub = stub
}

func (fake *FakeConnectionsTracker) TrackArgsForCall(i int) (string, grpc.Connection) {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	argsForCall := fake.trackArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeConnectionsTracker) TrackArgs() []FakeConnectionsTrackerTrackArgs {
	fake.trackMutex.RLock()
	defer fake.trackMutex.RUnlock()
	args := make([]FakeConnectionsTrackerTrackArgs, len(fake.trackArgsForCall))
	copy(args, fake.trackArgsForCall)
	return args
}

func (fake *FakeConnectionsTracker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConnectionsTracker) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeConnectionsTracker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ grpc.ConnectionsTracker = new(FakeConnectionsTracker)
