// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpcfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/agent/grpc"
	"sync"
)

// ConnectionsTrackerMock is a mock implementation of grpc.ConnectionsTracker.
//
//	func TestSomethingThatUsesConnectionsTracker(t *testing.T) {
//
//		// make and configure a mocked grpc.ConnectionsTracker
//		mockedConnectionsTracker := &ConnectionsTrackerMock{
//			GenerationFunc: func(key string) uint64 {
//				panic("mock out the Generation method")
//			},
//			GetConnectionFunc: func(key string) grpc.Connection {
//				panic("mock out the GetConnection method")
//			},
//			RemoveConnectionFunc: func(key string, generation uint64)  {
//				panic("mock out the RemoveConnection method")
//			},
//			SetInstanceIDFunc: func(key string, id string)  {
//				panic("mock out the SetInstanceID method")
//			},
//			TrackFunc: func(key string, conn grpc.Connection) uint64 {
//				panic("mock out the Track method")
//			},
//		}
//
//		// use mockedConnectionsTracker in code that requires grpc.ConnectionsTracker
//		// and then make assertions.
//
//	}
type ConnectionsTrackerMock struct {
	// GenerationFunc mocks the Generation method.
	GenerationFunc func(key string) uint64

	// GetConnectionFunc mocks the GetConnection method.
	GetConnectionFunc func(key string) grpc.Connection

	// RemoveConnectionFunc mocks the RemoveConnection method.
	RemoveConnectionFunc func(key string, generation uint64)

	// SetInstanceIDFunc mocks the SetInstanceID method.
	SetInstanceIDFunc func(key string, id string)

	// TrackFunc mocks the Track method.
	TrackFunc func(key string, conn grpc.Connection) uint64

	// calls tracks calls to the methods.
	calls struct {
		// Generation holds details about calls to the Generation method.
		Generation []struct {
			// Key is the key argument value.
			Key string
		}
		// GetConnection holds details about calls to the GetConnection method.
		GetConnection []struct {
			// Key is the key argument value.
			Key string
		}
		// RemoveConnection holds details about calls to the RemoveConnection method.
		RemoveConnection []struct {
			// Key is the key argument value.
			Key string
			// Generation is the generation argument value.
			Generation uint64
		}
		// SetInstanceID holds details about calls to the SetInstanceID method.
		SetInstanceID []struct {
			// Key is the key argument value.
			Key string
			// ID is the id argument value.
			ID string
		}
		// Track holds details about calls to the Track method.
		Track []struct {
			// Key is the key argument value.
			Key string
			// Conn is the conn argument value.
			Conn grpc.Connection
		}
	}
	lockGeneration       sync.RWMutex
	lockGetConnection    sync.RWMutex
	lockRemoveConnection sync.RWMutex
	lockSetInstanceID    sync.RWMutex
	lockTrack            sync.RWMutex
}

// Generation calls GenerationFunc.
func (mock *ConnectionsTrackerMock) Generation(key string) uint64 {
	if mock.GenerationFunc == nil {
		panic("ConnectionsTrackerMock.GenerationFunc: method is nil but ConnectionsTracker.Generation was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGeneration.Lock()
	mock.calls.Generation = append(mock.calls.Generation, callInfo)
	mock.lockGeneration.Unlock()
	return mock.GenerationFunc(key)
}

// GenerationCalls gets all the calls that were made to Generation.
// Check the length with:
//
//	len(mockedConnectionsTracker.GenerationCalls())
func (mock *ConnectionsTrackerMock) GenerationCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGeneration.RLock()
	calls = mock.calls.Generation
	mock.lockGeneration.RUnlock()
	return calls
}

// GetConnection calls GetConnectionFunc.
func (mock *ConnectionsTrackerMock) GetConnection(key string) grpc.Connection {
	if mock.GetConnectionFunc == nil {
		panic("ConnectionsTrackerMock.GetConnectionFunc: method is nil but ConnectionsTracker.GetConnection was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGetConnection.Lock()
	mock.calls.GetConnection = append(mock.calls.GetConnection, callInfo)
	mock.lockGetConnection.Unlock()
	return mock.GetConnectionFunc(key)
}

// GetConnectionCalls gets all the calls that were made to GetConnection.
// Check the length with:
//
//	len(mockedConnectionsTracker.GetConnectionCalls())
func (mock *ConnectionsTrackerMock) GetConnectionCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGetConnection.RLock()
	calls = mock.calls.GetConnection
	mock.lockGetConnection.RUnlock()
	return calls
}

// RemoveConnection calls RemoveConnectionFunc.
func (mock *ConnectionsTrackerMock) RemoveConnection(key string, generation uint64) {
	if mock.RemoveConnectionFunc == nil {
		panic("ConnectionsTrackerMock.RemoveConnectionFunc: method is nil but ConnectionsTracker.RemoveConnection was just called")
	}
	callInfo := struct {
		Key        string
		Generation uint64
	}{
		Key:        key,
		Generation: generation,
	}
	mock.lockRemoveConnection.Lock()
	mock.calls.RemoveConnection = append(mock.calls.RemoveConnection, callInfo)
	mock.lockRemoveConnection.Unlock()
	mock.RemoveConnectionFunc(key, generation)
}

// RemoveConnectionCalls gets all the calls that were made to RemoveConnection.
// Check the length with:
//
//	len(mockedConnectionsTracker.RemoveConnectionCalls())
func (mock *ConnectionsTrackerMock) RemoveConnectionCalls() []struct {
	Key        string
	Generation uint64
} {
	var calls []struct {
		Key        string
		Generation uint64
	}
	mock.lockRemoveConnection.RLock()
	calls = mock.calls.RemoveConnection
	mock.lockRemoveConnection.RUnlock()
	return calls
}

// SetInstanceID calls SetInstanceIDFunc.
func (mock *ConnectionsTrackerMock) SetInstanceID(key string, id string) {
	if mock.SetInstanceIDFunc == nil {
		panic("ConnectionsTrackerMock.SetInstanceIDFunc: method is nil but ConnectionsTracker.SetInstanceID was just called")
	}
	callInfo := struct {
		Key string
		ID  string
	}{
		Key: key,
		ID:  id,
	}
	mock.lockSetInstanceID.Lock()
	mock.calls.SetInstanceID = append(mock.calls.SetInstanceID, callInfo)
	mock.lockSetInstanceID.Unlock()
	mock.SetInstanceIDFunc(key, id)
}

// SetInstanceIDCalls gets all the calls that were made to SetInstanceID.
// Check the length with:
//
//	len(mockedConnectionsTracker.SetInstanceIDCalls())
func (mock *ConnectionsTrackerMock) SetInstanceIDCalls() []struct {
	Key string
	ID  string
} {
	var calls []struct {
		Key string
		ID  string
	}
	mock.lockSetInstanceID.RLock()
	calls = mock.calls.SetInstanceID
	mock.lockSetInstanceID.RUnlock()
	return calls
}

// Track calls TrackFunc.
func (mock *ConnectionsTrackerMock) Track(key string, conn grpc.Connection) uint64 {
	if mock.TrackFunc == nil {
		panic("ConnectionsTrackerMock.TrackFunc: method is nil but ConnectionsTracker.Track was just called")
	}
	callInfo := struct {
		Key  string
		Conn grpc.Connection
	}{
		Key:  key,
		Conn: conn,
	}
	mock.lockTrack.Lock()
	mock.calls.Track = append(mock.calls.Track, callInfo)
	mock.lockTrack.Unlock()
	return mock.TrackFunc(key, conn)
}

// TrackCalls gets all the calls that were made to Track.
// Check the length with:
//
//	len(mockedConnectionsTracker.TrackCalls())
func (mock *ConnectionsTrackerMock) TrackCalls() []struct {
	Key  string
	Conn grpc.Connection
} {
	var calls []struct {
		Key  string
		Conn grpc.Connection
	}
	mock.lockTrack.RLock()
	calls = mock.calls.Track
	mock.lockTrack.RUnlock()
	return calls
}
