apiVersion: gateway.nginx.org/v1alpha1
kind: UpstreamSettingsPolicy
metadata:
  name: upstream-keepalives
spec:
  targetRefs:
    - group: core
      kind: Service
      name: coffee
  keepAlive:
    connections: 32
