// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package filefakes

import (
	"io"
	"os"
	"sync"
)

// OSFileManagerMock is a mock implementation of file.OSFileManager.
//
//	func TestSomethingThatUsesOSFileManager(t *testing.T) {
//
//		// make and configure a mocked file.OSFileManager
//		mockedOSFileManager := &OSFileManagerMock{
//			ChmodFunc: func(file *os.File, mode os.FileMode) error {
//				panic("mock out the Chmod method")
//			},
//			CopyFunc: func(dst io.Writer, src io.Reader) error {
//				panic("mock out the Copy method")
//			},
//			CreateFunc: func(name string) (*os.File, error) {
//				panic("mock out the Create method")
//			},
//			OpenFunc: func(name string) (*os.File, error) {
//				panic("mock out the Open method")
//			},
//			WriteFunc: func(file *os.File, contents []byte) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedOSFileManager in code that requires file.OSFileManager
//		// and then make assertions.
//
//	}
type OSFileManagerMock struct {
	// ChmodFunc mocks the Chmod method.
	ChmodFunc func(file *os.File, mode os.FileMode) error

	// CopyFunc mocks the Copy method.
	CopyFunc func(dst io.Writer, src io.Reader) error

	// CreateFunc mocks the Create method.
	CreateFunc func(name string) (*os.File, error)

	// OpenFunc mocks the Open method.
	OpenFunc func(name string) (*os.File, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(file *os.File, contents []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Chmod holds details about calls to the Chmod method.
		Chmod []struct {
			// File is the file argument value.
			File *os.File
			// Mode is the mode argument value.
			Mode os.FileMode
		}
		// Copy holds details about calls to the Copy method.
		Copy []struct {
			// Dst is the dst argument value.
			Dst io.Writer
			// Src is the src argument value.
			Src io.Reader
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Name is the name argument value.
			Name string
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Name is the name argument value.
			Name string
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// File is the file argument value.
			File *os.File
			// Contents is the contents argument value.
			Contents []byte
		}
	}
	lockChmod  sync.RWMutex
	lockCopy   sync.RWMutex
	lockCreate sync.RWMutex
	lockOpen   sync.RWMutex
	lockWrite  sync.RWMutex
}

// Chmod calls ChmodFunc.
func (mock *OSFileManagerMock) Chmod(file *os.File, mode os.FileMode) error {
	if mock.ChmodFunc == nil {
		panic("OSFileManagerMock.ChmodFunc: method is nil but OSFileManager.Chmod was just called")
	}
	callInfo := struct {
		File *os.File
		Mode os.FileMode
	}{
		File: file,
		Mode: mode,
	}
	mock.lockChmod.Lock()
	mock.calls.Chmod = append(mock.calls.Chmod, callInfo)
	mock.lockChmod.Unlock()
	return mock.ChmodFunc(file, mode)
}

// ChmodCalls gets all the calls that were made to Chmod.
// Check the length with:
//
//	len(mockedOSFileManager.ChmodCalls())
func (mock *OSFileManagerMock) ChmodCalls() []struct {
	File *os.File
	Mode os.FileMode
} {
	var calls []struct {
		File *os.File
		Mode os.FileMode
	}
	mock.lockChmod.RLock()
	calls = mock.calls.Chmod
	mock.lockChmod.RUnlock()
	return calls
}

// Copy calls CopyFunc.
func (mock *OSFileManagerMock) Copy(dst io.Writer, src io.Reader) error {
	if mock.CopyFunc == nil {
		panic("OSFileManagerMock.CopyFunc: method is nil but OSFileManager.Copy was just called")
	}
	callInfo := struct {
		Dst io.Writer
		Src io.Reader
	}{
		Dst: dst,
		Src: src,
	}
	mock.lockCopy.Lock()
	mock.calls.Copy = append(mock.calls.Copy, callInfo)
	mock.lockCopy.Unlock()
	return mock.CopyFunc(dst, src)
}

// CopyCalls gets all the calls that were made to Copy.
// Check the length with:
//
//	len(mockedOSFileManager.CopyCalls())
func (mock *OSFileManagerMock) CopyCalls() []struct {
	Dst io.Writer
	Src io.Reader
} {
	var calls []struct {
		Dst io.Writer
		Src io.Reader
	}
	mock.lockCopy.RLock()
	calls = mock.calls.Copy
	mock.lockCopy.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *OSFileManagerMock) Create(name string) (*os.File, error) {
	if mock.CreateFunc == nil {
		panic("OSFileManagerMock.CreateFunc: method is nil but OSFileManager.Create was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(name)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedOSFileManager.CreateCalls())
func (mock *OSFileManagerMock) CreateCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *OSFileManagerMock) Open(name string) (*os.File, error) {
	if mock.OpenFunc == nil {
		panic("OSFileManagerMock.OpenFunc: method is nil but OSFileManager.Open was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(name)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedOSFileManager.OpenCalls())
func (mock *OSFileManagerMock) OpenCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *OSFileManagerMock) Write(file *os.File, contents []byte) error {
	if mock.WriteFunc == nil {
		panic("OSFileManagerMock.WriteFunc: method is nil but OSFileManager.Write was just called")
	}
	callInfo := struct {
		File     *os.File
		Contents []byte
	}{
		File:     file,
		Contents: contents,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(file, contents)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedOSFileManager.WriteCalls())
func (mock *OSFileManagerMock) WriteCalls() []struct {
	File     *os.File
	Contents []byte
} {
	var calls []struct {
		File     *os.File
		Contents []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
