apiVersion: gateway.nginx.org/v1alpha1
kind: PayloadProcessor
metadata:
  name: llm-guardrails
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: llm-route
  processors:
  - type: ExtProcess
    timeout: 2s
    extProcess:
      backendRef:
        group: ""
        kind: Service
        name: guardrails-api
        port: 443
      authTokenRef:
        name: guardrails-token
