apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
{{- if or .Values.nginxGateway.serviceAccount.imagePullSecret .Values.nginxGateway.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- if .Values.nginxGateway.serviceAccount.imagePullSecret }}
  - name: {{ .Values.nginxGateway.serviceAccount.imagePullSecret }}
  {{- end }}
  {{- if .Values.nginxGateway.serviceAccount.imagePullSecrets }}
  {{- range .Values.nginxGateway.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-cert-generator
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.certGenerator.annotations -}}
  {{ toYaml . | nindent 4 }}
  {{- end }}
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.certGenerator.annotations -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - args:
        - generate-certs
        - --service={{ include "nginx-gateway.fullname" . }}
        - --cluster-domain={{ .Values.clusterDomain }}
        - --server-tls-secret={{ .Values.certGenerator.serverTLSSecretName }}
        - --agent-tls-secret={{ .Values.certGenerator.agentTLSSecretName }}
        {{- if .Values.certGenerator.overwrite }}
        - --overwrite
        {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.nginxGateway.image.repository }}:{{ default .Chart.AppVersion .Values.nginxGateway.image.tag }}
        imagePullPolicy: {{ .Values.nginxGateway.image.pullPolicy }}
        name: cert-generator
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
      restartPolicy: Never
      serviceAccountName: {{ include "nginx-gateway.fullname" . }}-cert-generator
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
  ttlSecondsAfterFinished: 0
