apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.nginxGateway.gatewayClassName }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  {{- if .Values.nginxGateway.gatewayClassCustomAnnotations }}
  annotations:
    {{- range $key, $value := .Values.nginxGateway.gatewayClassCustomAnnotations }}
    {{ printf "%s: %s" $key $value }}
    {{- end }}
  {{- end }}
spec:
  controllerName: {{ .Values.nginxGateway.gatewayControllerName }}
