apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-includes
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
data:
  main.conf: |
    {{- if and .Values.nginx.config .Values.nginx.config.logging .Values.nginx.config.logging.errorLevel }}
    error_log stderr {{ .Values.nginx.config.logging.errorLevel }};
    {{ else }}
    error_log stderr info;
    {{- end }}
