apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- if or .Values.serviceAccount.imagePullSecret .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- if .Values.serviceAccount.imagePullSecret }}
  - name: {{ .Values.serviceAccount.imagePullSecret }}
  {{- end }}
  {{- if .Values.serviceAccount.imagePullSecrets }}
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - secrets
{{- if .Values.nginxGateway.gwAPIExperimentalFeatures.enable }}
  - configmaps
{{- end }}
  verbs:
  - get
  - list
  - watch
{{- if .Values.nginxGateway.productTelemetry.enable }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
{{- end }}
{{- if .Values.nginx.plus }}
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
{{- end }}
{{- if or .Values.nginxGateway.productTelemetry.enable .Values.nginx.plus }}
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
{{- end }}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - grpcroutes
{{- if .Values.nginxGateway.gwAPIExperimentalFeatures.enable }}
  - backendtlspolicies
{{- end }}
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - gateways/status
  - gatewayclasses/status
  - grpcroutes/status
{{- if .Values.nginxGateway.gwAPIExperimentalFeatures.enable }}
  - backendtlspolicies/status
{{- end }}
  verbs:
  - update
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxproxies
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways/status
  verbs:
  - update
{{- if .Values.nginxGateway.leaderElection.enable }}
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
{{- end }}
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nginx-gateway.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
