// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package statusfakes

import (
	"context"
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/status"
	"sync"
)

// GroupUpdaterMock is a mock implementation of status.GroupUpdater.
//
//	func TestSomethingThatUsesGroupUpdater(t *testing.T) {
//
//		// make and configure a mocked status.GroupUpdater
//		mockedGroupUpdater := &GroupUpdaterMock{
//			UpdateGroupFunc: func(ctx context.Context, logger logr.Logger, name string, reqs ...status.UpdateRequest)  {
//				panic("mock out the UpdateGroup method")
//			},
//		}
//
//		// use mockedGroupUpdater in code that requires status.GroupUpdater
//		// and then make assertions.
//
//	}
type GroupUpdaterMock struct {
	// UpdateGroupFunc mocks the UpdateGroup method.
	UpdateGroupFunc func(ctx context.Context, logger logr.Logger, name string, reqs ...status.UpdateRequest)

	// calls tracks calls to the methods.
	calls struct {
		// UpdateGroup holds details about calls to the UpdateGroup method.
		UpdateGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Logger is the logger argument value.
			Logger logr.Logger
			// Name is the name argument value.
			Name string
			// Reqs is the reqs argument value.
			Reqs []status.UpdateRequest
		}
	}
	lockUpdateGroup sync.RWMutex
}

// UpdateGroup calls UpdateGroupFunc.
func (mock *GroupUpdaterMock) UpdateGroup(ctx context.Context, logger logr.Logger, name string, reqs ...status.UpdateRequest) {
	if mock.UpdateGroupFunc == nil {
		panic("GroupUpdaterMock.UpdateGroupFunc: method is nil but GroupUpdater.UpdateGroup was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Logger logr.Logger
		Name   string
		Reqs   []status.UpdateRequest
	}{
		Ctx:    ctx,
		Logger: logger,
		Name:   name,
		Reqs:   reqs,
	}
	mock.lockUpdateGroup.Lock()
	mock.calls.UpdateGroup = append(mock.calls.UpdateGroup, callInfo)
	mock.lockUpdateGroup.Unlock()
	mock.UpdateGroupFunc(ctx, logger, name, reqs...)
}

// UpdateGroupCalls gets all the calls that were made to UpdateGroup.
// Check the length with:
//
//	len(mockedGroupUpdater.UpdateGroupCalls())
func (mock *GroupUpdaterMock) UpdateGroupCalls() []struct {
	Ctx    context.Context
	Logger logr.Logger
	Name   string
	Reqs   []status.UpdateRequest
} {
	var calls []struct {
		Ctx    context.Context
		Logger logr.Logger
		Name   string
		Reqs   []status.UpdateRequest
	}
	mock.lockUpdateGroup.RLock()
	calls = mock.calls.UpdateGroup
	mock.lockUpdateGroup.RUnlock()
	return calls
}
