// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package statusfakes

import (
	"context"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

// K8sUpdaterMock is a mock implementation of status.K8sUpdater.
//
//	func TestSomethingThatUsesK8sUpdater(t *testing.T) {
//
//		// make and configure a mocked status.K8sUpdater
//		mockedK8sUpdater := &K8sUpdaterMock{
//			UpdateFunc: func(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedK8sUpdater in code that requires status.K8sUpdater
//		// and then make assertions.
//
//	}
type K8sUpdaterMock struct {
	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error

	// calls tracks calls to the methods.
	calls struct {
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj client.Object
			// Opts is the opts argument value.
			Opts []client.SubResourceUpdateOption
		}
	}
	lockUpdate sync.RWMutex
}

// Update calls UpdateFunc.
func (mock *K8sUpdaterMock) Update(ctx context.Context, obj client.Object, opts ...client.SubResourceUpdateOption) error {
	if mock.UpdateFunc == nil {
		panic("K8sUpdaterMock.UpdateFunc: method is nil but K8sUpdater.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Obj  client.Object
		Opts []client.SubResourceUpdateOption
	}{
		Ctx:  ctx,
		Obj:  obj,
		Opts: opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, obj, opts...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedK8sUpdater.UpdateCalls())
func (mock *K8sUpdaterMock) UpdateCalls() []struct {
	Ctx  context.Context
	Obj  client.Object
	Opts []client.SubResourceUpdateOption
} {
	var calls []struct {
		Ctx  context.Context
		Obj  client.Object
		Opts []client.SubResourceUpdateOption
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
