apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: cafe
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
    sectionName: http
  hostnames:
  - "cafe.example.com"
  rules:
  - backendRefs:
    - name: main
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: coffee
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
    sectionName: http
  hostnames:
  - "cafe.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /coffee
      method: POST
      headers:
      - name: X-Demo-Header # header names are case-insensitive
        value: Demo-X1 # header values are case-sensitive
      - name: version
        value: v1
    backendRefs:
    - name: coffee
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: tea
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
    sectionName: http
  hostnames:
  - "cafe.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /tea
      queryParams:
      - name: Great # query params and values are case-sensitive
        value: Example
    backendRefs:
    - name: tea
      port: 80
