// Code generated by gen_policies.go; DO NOT EDIT.

package v1alpha2

import "sigs.k8s.io/gateway-api/apis/v1alpha2"

func (p *ObservabilityPolicy) GetTargetRefs() []v1alpha2.LocalPolicyTargetReference {
	return p.Spec.TargetRefs
}

func (p *ObservabilityPolicy) GetPolicyStatus() v1alpha2.PolicyStatus {
	return p.Status
}

func (p *ObservabilityPolicy) SetPolicyStatus(status v1alpha2.PolicyStatus) {
	p.Status = status
}
