// Code generated by policygen.go. DO NOT EDIT

package v1alpha2

import (
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

func (p *ObservabilityPolicy) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	return p.Spec.TargetRefs
}

func (p *ObservabilityPolicy) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

func (p *ObservabilityPolicy) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}
