//go:build !ignore_autogenerated

// Code generated by policygen. DO NOT EDIT.

package v1alpha2

import (
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// GetTargetRefs implements the policies.Policy interface for ObservabilityPolicy.
func (p *ObservabilityPolicy) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	return p.Spec.TargetRefs
}

// GetPolicyStatus implements the policies.Policy interface for ObservabilityPolicy.
func (p *ObservabilityPolicy) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

// SetPolicyStatus implements the policies.Policy interface for ObservabilityPolicy.
func (p *ObservabilityPolicy) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}
