// Code generated by counterfeiter. DO NOT EDIT.
package pollerfakes

import (
	"context"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/waf/poller"
	"k8s.io/apimachinery/pkg/types"
)

type FakePollerManager struct {
	GetAllPollErrorsStub        func() map[types.NamespacedName]poller.PollError
	getAllPollErrorsMutex       sync.RWMutex
	getAllPollErrorsArgsForCall []struct {
	}
	getAllPollErrorsReturns struct {
		result1 map[types.NamespacedName]poller.PollError
	}
	getAllPollErrorsReturnsOnCall map[int]struct {
		result1 map[types.NamespacedName]poller.PollError
	}
	GetLatestBundlesStub        func() map[graph.WAFBundleKey]*graph.WAFBundleData
	getLatestBundlesMutex       sync.RWMutex
	getLatestBundlesArgsForCall []struct {
	}
	getLatestBundlesReturns struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}
	getLatestBundlesReturnsOnCall map[int]struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}
	ReconcilePollerStub        func(context.Context, poller.Config)
	reconcilePollerMutex       sync.RWMutex
	reconcilePollerArgsForCall []struct {
		arg1 context.Context
		arg2 poller.Config
	}
	StopPollerStub        func(types.NamespacedName)
	stopPollerMutex       sync.RWMutex
	stopPollerArgsForCall []struct {
		arg1 types.NamespacedName
	}
	StopPollersNotInStub        func(map[types.NamespacedName]struct{})
	stopPollersNotInMutex       sync.RWMutex
	stopPollersNotInArgsForCall []struct {
		arg1 map[types.NamespacedName]struct{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePollerManager) GetAllPollErrors() map[types.NamespacedName]poller.PollError {
	fake.getAllPollErrorsMutex.Lock()
	ret, specificReturn := fake.getAllPollErrorsReturnsOnCall[len(fake.getAllPollErrorsArgsForCall)]
	fake.getAllPollErrorsArgsForCall = append(fake.getAllPollErrorsArgsForCall, struct {
	}{})
	stub := fake.GetAllPollErrorsStub
	fakeReturns := fake.getAllPollErrorsReturns
	fake.recordInvocation("GetAllPollErrors", []interface{}{})
	fake.getAllPollErrorsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePollerManager) GetAllPollErrorsCallCount() int {
	fake.getAllPollErrorsMutex.RLock()
	defer fake.getAllPollErrorsMutex.RUnlock()
	return len(fake.getAllPollErrorsArgsForCall)
}

func (fake *FakePollerManager) GetAllPollErrorsCalls(stub func() map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = stub
}

func (fake *FakePollerManager) GetAllPollErrorsReturns(result1 map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = nil
	fake.getAllPollErrorsReturns = struct {
		result1 map[types.NamespacedName]poller.PollError
	}{result1}
}

func (fake *FakePollerManager) GetAllPollErrorsReturnsOnCall(i int, result1 map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = nil
	if fake.getAllPollErrorsReturnsOnCall == nil {
		fake.getAllPollErrorsReturnsOnCall = make(map[int]struct {
			result1 map[types.NamespacedName]poller.PollError
		})
	}
	fake.getAllPollErrorsReturnsOnCall[i] = struct {
		result1 map[types.NamespacedName]poller.PollError
	}{result1}
}

func (fake *FakePollerManager) GetLatestBundles() map[graph.WAFBundleKey]*graph.WAFBundleData {
	fake.getLatestBundlesMutex.Lock()
	ret, specificReturn := fake.getLatestBundlesReturnsOnCall[len(fake.getLatestBundlesArgsForCall)]
	fake.getLatestBundlesArgsForCall = append(fake.getLatestBundlesArgsForCall, struct {
	}{})
	stub := fake.GetLatestBundlesStub
	fakeReturns := fake.getLatestBundlesReturns
	fake.recordInvocation("GetLatestBundles", []interface{}{})
	fake.getLatestBundlesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePollerManager) GetLatestBundlesCallCount() int {
	fake.getLatestBundlesMutex.RLock()
	defer fake.getLatestBundlesMutex.RUnlock()
	return len(fake.getLatestBundlesArgsForCall)
}

func (fake *FakePollerManager) GetLatestBundlesCalls(stub func() map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = stub
}

func (fake *FakePollerManager) GetLatestBundlesReturns(result1 map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = nil
	fake.getLatestBundlesReturns = struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}{result1}
}

func (fake *FakePollerManager) GetLatestBundlesReturnsOnCall(i int, result1 map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = nil
	if fake.getLatestBundlesReturnsOnCall == nil {
		fake.getLatestBundlesReturnsOnCall = make(map[int]struct {
			result1 map[graph.WAFBundleKey]*graph.WAFBundleData
		})
	}
	fake.getLatestBundlesReturnsOnCall[i] = struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}{result1}
}

func (fake *FakePollerManager) ReconcilePoller(arg1 context.Context, arg2 poller.Config) {
	fake.reconcilePollerMutex.Lock()
	fake.reconcilePollerArgsForCall = append(fake.reconcilePollerArgsForCall, struct {
		arg1 context.Context
		arg2 poller.Config
	}{arg1, arg2})
	stub := fake.ReconcilePollerStub
	fake.recordInvocation("ReconcilePoller", []interface{}{arg1, arg2})
	fake.reconcilePollerMutex.Unlock()
	if stub != nil {
		fake.ReconcilePollerStub(arg1, arg2)
	}
}

func (fake *FakePollerManager) ReconcilePollerCallCount() int {
	fake.reconcilePollerMutex.RLock()
	defer fake.reconcilePollerMutex.RUnlock()
	return len(fake.reconcilePollerArgsForCall)
}

func (fake *FakePollerManager) ReconcilePollerCalls(stub func(context.Context, poller.Config)) {
	fake.reconcilePollerMutex.Lock()
	defer fake.reconcilePollerMutex.Unlock()
	fake.ReconcilePollerStub = stub
}

func (fake *FakePollerManager) ReconcilePollerArgsForCall(i int) (context.Context, poller.Config) {
	fake.reconcilePollerMutex.RLock()
	defer fake.reconcilePollerMutex.RUnlock()
	argsForCall := fake.reconcilePollerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePollerManager) StopPoller(arg1 types.NamespacedName) {
	fake.stopPollerMutex.Lock()
	fake.stopPollerArgsForCall = append(fake.stopPollerArgsForCall, struct {
		arg1 types.NamespacedName
	}{arg1})
	stub := fake.StopPollerStub
	fake.recordInvocation("StopPoller", []interface{}{arg1})
	fake.stopPollerMutex.Unlock()
	if stub != nil {
		fake.StopPollerStub(arg1)
	}
}

func (fake *FakePollerManager) StopPollerCallCount() int {
	fake.stopPollerMutex.RLock()
	defer fake.stopPollerMutex.RUnlock()
	return len(fake.stopPollerArgsForCall)
}

func (fake *FakePollerManager) StopPollerCalls(stub func(types.NamespacedName)) {
	fake.stopPollerMutex.Lock()
	defer fake.stopPollerMutex.Unlock()
	fake.StopPollerStub = stub
}

func (fake *FakePollerManager) StopPollerArgsForCall(i int) types.NamespacedName {
	fake.stopPollerMutex.RLock()
	defer fake.stopPollerMutex.RUnlock()
	argsForCall := fake.stopPollerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePollerManager) StopPollersNotIn(arg1 map[types.NamespacedName]struct{}) {
	fake.stopPollersNotInMutex.Lock()
	fake.stopPollersNotInArgsForCall = append(fake.stopPollersNotInArgsForCall, struct {
		arg1 map[types.NamespacedName]struct{}
	}{arg1})
	stub := fake.StopPollersNotInStub
	fake.recordInvocation("StopPollersNotIn", []interface{}{arg1})
	fake.stopPollersNotInMutex.Unlock()
	if stub != nil {
		fake.StopPollersNotInStub(arg1)
	}
}

func (fake *FakePollerManager) StopPollersNotInCallCount() int {
	fake.stopPollersNotInMutex.RLock()
	defer fake.stopPollersNotInMutex.RUnlock()
	return len(fake.stopPollersNotInArgsForCall)
}

func (fake *FakePollerManager) StopPollersNotInCalls(stub func(map[types.NamespacedName]struct{})) {
	fake.stopPollersNotInMutex.Lock()
	defer fake.stopPollersNotInMutex.Unlock()
	fake.StopPollersNotInStub = stub
}

func (fake *FakePollerManager) StopPollersNotInArgsForCall(i int) map[types.NamespacedName]struct{} {
	fake.stopPollersNotInMutex.RLock()
	defer fake.stopPollersNotInMutex.RUnlock()
	argsForCall := fake.stopPollersNotInArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePollerManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePollerManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ poller.Manager = new(FakePollerManager)
