// Code generated by counterfeiter. DO NOT EDIT.
package pollerfakes

import (
	"context"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/waf/poller"
	"k8s.io/apimachinery/pkg/types"
)

type FakeManager struct {
	GetAllBundleUpdatesStub        func() map[types.NamespacedName]poller.BundleUpdate
	getAllBundleUpdatesMutex       sync.RWMutex
	getAllBundleUpdatesArgsForCall []struct {
	}
	getAllBundleUpdatesReturns struct {
		result1 map[types.NamespacedName]poller.BundleUpdate
	}
	getAllBundleUpdatesReturnsOnCall map[int]struct {
		result1 map[types.NamespacedName]poller.BundleUpdate
	}
	GetAllPollErrorsStub        func() map[types.NamespacedName]poller.PollError
	getAllPollErrorsMutex       sync.RWMutex
	getAllPollErrorsArgsForCall []struct {
	}
	getAllPollErrorsReturns struct {
		result1 map[types.NamespacedName]poller.PollError
	}
	getAllPollErrorsReturnsOnCall map[int]struct {
		result1 map[types.NamespacedName]poller.PollError
	}
	GetLatestBundlesStub        func() map[graph.WAFBundleKey]*graph.WAFBundleData
	getLatestBundlesMutex       sync.RWMutex
	getLatestBundlesArgsForCall []struct {
	}
	getLatestBundlesReturns struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}
	getLatestBundlesReturnsOnCall map[int]struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}
	HasPollerStub        func(types.NamespacedName) bool
	hasPollerMutex       sync.RWMutex
	hasPollerArgsForCall []struct {
		arg1 types.NamespacedName
	}
	hasPollerReturns struct {
		result1 bool
	}
	hasPollerReturnsOnCall map[int]struct {
		result1 bool
	}
	ReconcilePollerStub        func(context.Context, poller.Config)
	reconcilePollerMutex       sync.RWMutex
	reconcilePollerArgsForCall []struct {
		arg1 context.Context
		arg2 poller.Config
	}
	StopPollerStub        func(types.NamespacedName)
	stopPollerMutex       sync.RWMutex
	stopPollerArgsForCall []struct {
		arg1 types.NamespacedName
	}
	StopPollersNotInStub        func(map[types.NamespacedName]struct{})
	stopPollersNotInMutex       sync.RWMutex
	stopPollersNotInArgsForCall []struct {
		arg1 map[types.NamespacedName]struct{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) GetAllBundleUpdates() map[types.NamespacedName]poller.BundleUpdate {
	fake.getAllBundleUpdatesMutex.Lock()
	ret, specificReturn := fake.getAllBundleUpdatesReturnsOnCall[len(fake.getAllBundleUpdatesArgsForCall)]
	fake.getAllBundleUpdatesArgsForCall = append(fake.getAllBundleUpdatesArgsForCall, struct {
	}{})
	stub := fake.GetAllBundleUpdatesStub
	fakeReturns := fake.getAllBundleUpdatesReturns
	fake.recordInvocation("GetAllBundleUpdates", []interface{}{})
	fake.getAllBundleUpdatesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) GetAllBundleUpdatesCallCount() int {
	fake.getAllBundleUpdatesMutex.RLock()
	defer fake.getAllBundleUpdatesMutex.RUnlock()
	return len(fake.getAllBundleUpdatesArgsForCall)
}

func (fake *FakeManager) GetAllBundleUpdatesCalls(stub func() map[types.NamespacedName]poller.BundleUpdate) {
	fake.getAllBundleUpdatesMutex.Lock()
	defer fake.getAllBundleUpdatesMutex.Unlock()
	fake.GetAllBundleUpdatesStub = stub
}

func (fake *FakeManager) GetAllBundleUpdatesReturns(result1 map[types.NamespacedName]poller.BundleUpdate) {
	fake.getAllBundleUpdatesMutex.Lock()
	defer fake.getAllBundleUpdatesMutex.Unlock()
	fake.GetAllBundleUpdatesStub = nil
	fake.getAllBundleUpdatesReturns = struct {
		result1 map[types.NamespacedName]poller.BundleUpdate
	}{result1}
}

func (fake *FakeManager) GetAllBundleUpdatesReturnsOnCall(i int, result1 map[types.NamespacedName]poller.BundleUpdate) {
	fake.getAllBundleUpdatesMutex.Lock()
	defer fake.getAllBundleUpdatesMutex.Unlock()
	fake.GetAllBundleUpdatesStub = nil
	if fake.getAllBundleUpdatesReturnsOnCall == nil {
		fake.getAllBundleUpdatesReturnsOnCall = make(map[int]struct {
			result1 map[types.NamespacedName]poller.BundleUpdate
		})
	}
	fake.getAllBundleUpdatesReturnsOnCall[i] = struct {
		result1 map[types.NamespacedName]poller.BundleUpdate
	}{result1}
}

func (fake *FakeManager) GetAllPollErrors() map[types.NamespacedName]poller.PollError {
	fake.getAllPollErrorsMutex.Lock()
	ret, specificReturn := fake.getAllPollErrorsReturnsOnCall[len(fake.getAllPollErrorsArgsForCall)]
	fake.getAllPollErrorsArgsForCall = append(fake.getAllPollErrorsArgsForCall, struct {
	}{})
	stub := fake.GetAllPollErrorsStub
	fakeReturns := fake.getAllPollErrorsReturns
	fake.recordInvocation("GetAllPollErrors", []interface{}{})
	fake.getAllPollErrorsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) GetAllPollErrorsCallCount() int {
	fake.getAllPollErrorsMutex.RLock()
	defer fake.getAllPollErrorsMutex.RUnlock()
	return len(fake.getAllPollErrorsArgsForCall)
}

func (fake *FakeManager) GetAllPollErrorsCalls(stub func() map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = stub
}

func (fake *FakeManager) GetAllPollErrorsReturns(result1 map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = nil
	fake.getAllPollErrorsReturns = struct {
		result1 map[types.NamespacedName]poller.PollError
	}{result1}
}

func (fake *FakeManager) GetAllPollErrorsReturnsOnCall(i int, result1 map[types.NamespacedName]poller.PollError) {
	fake.getAllPollErrorsMutex.Lock()
	defer fake.getAllPollErrorsMutex.Unlock()
	fake.GetAllPollErrorsStub = nil
	if fake.getAllPollErrorsReturnsOnCall == nil {
		fake.getAllPollErrorsReturnsOnCall = make(map[int]struct {
			result1 map[types.NamespacedName]poller.PollError
		})
	}
	fake.getAllPollErrorsReturnsOnCall[i] = struct {
		result1 map[types.NamespacedName]poller.PollError
	}{result1}
}

func (fake *FakeManager) GetLatestBundles() map[graph.WAFBundleKey]*graph.WAFBundleData {
	fake.getLatestBundlesMutex.Lock()
	ret, specificReturn := fake.getLatestBundlesReturnsOnCall[len(fake.getLatestBundlesArgsForCall)]
	fake.getLatestBundlesArgsForCall = append(fake.getLatestBundlesArgsForCall, struct {
	}{})
	stub := fake.GetLatestBundlesStub
	fakeReturns := fake.getLatestBundlesReturns
	fake.recordInvocation("GetLatestBundles", []interface{}{})
	fake.getLatestBundlesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) GetLatestBundlesCallCount() int {
	fake.getLatestBundlesMutex.RLock()
	defer fake.getLatestBundlesMutex.RUnlock()
	return len(fake.getLatestBundlesArgsForCall)
}

func (fake *FakeManager) GetLatestBundlesCalls(stub func() map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = stub
}

func (fake *FakeManager) GetLatestBundlesReturns(result1 map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = nil
	fake.getLatestBundlesReturns = struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}{result1}
}

func (fake *FakeManager) GetLatestBundlesReturnsOnCall(i int, result1 map[graph.WAFBundleKey]*graph.WAFBundleData) {
	fake.getLatestBundlesMutex.Lock()
	defer fake.getLatestBundlesMutex.Unlock()
	fake.GetLatestBundlesStub = nil
	if fake.getLatestBundlesReturnsOnCall == nil {
		fake.getLatestBundlesReturnsOnCall = make(map[int]struct {
			result1 map[graph.WAFBundleKey]*graph.WAFBundleData
		})
	}
	fake.getLatestBundlesReturnsOnCall[i] = struct {
		result1 map[graph.WAFBundleKey]*graph.WAFBundleData
	}{result1}
}

func (fake *FakeManager) HasPoller(arg1 types.NamespacedName) bool {
	fake.hasPollerMutex.Lock()
	ret, specificReturn := fake.hasPollerReturnsOnCall[len(fake.hasPollerArgsForCall)]
	fake.hasPollerArgsForCall = append(fake.hasPollerArgsForCall, struct {
		arg1 types.NamespacedName
	}{arg1})
	stub := fake.HasPollerStub
	fakeReturns := fake.hasPollerReturns
	fake.recordInvocation("HasPoller", []interface{}{arg1})
	fake.hasPollerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) HasPollerCallCount() int {
	fake.hasPollerMutex.RLock()
	defer fake.hasPollerMutex.RUnlock()
	return len(fake.hasPollerArgsForCall)
}

func (fake *FakeManager) HasPollerCalls(stub func(types.NamespacedName) bool) {
	fake.hasPollerMutex.Lock()
	defer fake.hasPollerMutex.Unlock()
	fake.HasPollerStub = stub
}

func (fake *FakeManager) HasPollerArgsForCall(i int) types.NamespacedName {
	fake.hasPollerMutex.RLock()
	defer fake.hasPollerMutex.RUnlock()
	argsForCall := fake.hasPollerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeManager) HasPollerReturns(result1 bool) {
	fake.hasPollerMutex.Lock()
	defer fake.hasPollerMutex.Unlock()
	fake.HasPollerStub = nil
	fake.hasPollerReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeManager) HasPollerReturnsOnCall(i int, result1 bool) {
	fake.hasPollerMutex.Lock()
	defer fake.hasPollerMutex.Unlock()
	fake.HasPollerStub = nil
	if fake.hasPollerReturnsOnCall == nil {
		fake.hasPollerReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasPollerReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeManager) ReconcilePoller(arg1 context.Context, arg2 poller.Config) {
	fake.reconcilePollerMutex.Lock()
	fake.reconcilePollerArgsForCall = append(fake.reconcilePollerArgsForCall, struct {
		arg1 context.Context
		arg2 poller.Config
	}{arg1, arg2})
	stub := fake.ReconcilePollerStub
	fake.recordInvocation("ReconcilePoller", []interface{}{arg1, arg2})
	fake.reconcilePollerMutex.Unlock()
	if stub != nil {
		fake.ReconcilePollerStub(arg1, arg2)
	}
}

func (fake *FakeManager) ReconcilePollerCallCount() int {
	fake.reconcilePollerMutex.RLock()
	defer fake.reconcilePollerMutex.RUnlock()
	return len(fake.reconcilePollerArgsForCall)
}

func (fake *FakeManager) ReconcilePollerCalls(stub func(context.Context, poller.Config)) {
	fake.reconcilePollerMutex.Lock()
	defer fake.reconcilePollerMutex.Unlock()
	fake.ReconcilePollerStub = stub
}

func (fake *FakeManager) ReconcilePollerArgsForCall(i int) (context.Context, poller.Config) {
	fake.reconcilePollerMutex.RLock()
	defer fake.reconcilePollerMutex.RUnlock()
	argsForCall := fake.reconcilePollerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeManager) StopPoller(arg1 types.NamespacedName) {
	fake.stopPollerMutex.Lock()
	fake.stopPollerArgsForCall = append(fake.stopPollerArgsForCall, struct {
		arg1 types.NamespacedName
	}{arg1})
	stub := fake.StopPollerStub
	fake.recordInvocation("StopPoller", []interface{}{arg1})
	fake.stopPollerMutex.Unlock()
	if stub != nil {
		fake.StopPollerStub(arg1)
	}
}

func (fake *FakeManager) StopPollerCallCount() int {
	fake.stopPollerMutex.RLock()
	defer fake.stopPollerMutex.RUnlock()
	return len(fake.stopPollerArgsForCall)
}

func (fake *FakeManager) StopPollerCalls(stub func(types.NamespacedName)) {
	fake.stopPollerMutex.Lock()
	defer fake.stopPollerMutex.Unlock()
	fake.StopPollerStub = stub
}

func (fake *FakeManager) StopPollerArgsForCall(i int) types.NamespacedName {
	fake.stopPollerMutex.RLock()
	defer fake.stopPollerMutex.RUnlock()
	argsForCall := fake.stopPollerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeManager) StopPollersNotIn(arg1 map[types.NamespacedName]struct{}) {
	fake.stopPollersNotInMutex.Lock()
	fake.stopPollersNotInArgsForCall = append(fake.stopPollersNotInArgsForCall, struct {
		arg1 map[types.NamespacedName]struct{}
	}{arg1})
	stub := fake.StopPollersNotInStub
	fake.recordInvocation("StopPollersNotIn", []interface{}{arg1})
	fake.stopPollersNotInMutex.Unlock()
	if stub != nil {
		fake.StopPollersNotInStub(arg1)
	}
}

func (fake *FakeManager) StopPollersNotInCallCount() int {
	fake.stopPollersNotInMutex.RLock()
	defer fake.stopPollersNotInMutex.RUnlock()
	return len(fake.stopPollersNotInArgsForCall)
}

func (fake *FakeManager) StopPollersNotInCalls(stub func(map[types.NamespacedName]struct{})) {
	fake.stopPollersNotInMutex.Lock()
	defer fake.stopPollersNotInMutex.Unlock()
	fake.StopPollersNotInStub = stub
}

func (fake *FakeManager) StopPollersNotInArgsForCall(i int) map[types.NamespacedName]struct{} {
	fake.stopPollersNotInMutex.RLock()
	defer fake.stopPollersNotInMutex.RUnlock()
	argsForCall := fake.stopPollersNotInArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ poller.Manager = new(FakeManager)
