// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pollerfakes

import (
	"context"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/waf/poller"
	"k8s.io/apimachinery/pkg/types"
	"sync"
)

// ManagerMock is a mock implementation of poller.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked poller.Manager
//		mockedManager := &ManagerMock{
//			GetAllBundleUpdatesFunc: func() map[types.NamespacedName]poller.BundleUpdate {
//				panic("mock out the GetAllBundleUpdates method")
//			},
//			GetAllPollErrorsFunc: func() map[types.NamespacedName]poller.PollError {
//				panic("mock out the GetAllPollErrors method")
//			},
//			GetLatestBundlesFunc: func() map[graph.WAFBundleKey]*graph.WAFBundleData {
//				panic("mock out the GetLatestBundles method")
//			},
//			HasPollerFunc: func(policyNsName types.NamespacedName) bool {
//				panic("mock out the HasPoller method")
//			},
//			ReconcilePollerFunc: func(ctx context.Context, cfg poller.Config)  {
//				panic("mock out the ReconcilePoller method")
//			},
//			StopPollerFunc: func(policyNsName types.NamespacedName)  {
//				panic("mock out the StopPoller method")
//			},
//			StopPollersNotInFunc: func(activePolicies map[types.NamespacedName]struct{})  {
//				panic("mock out the StopPollersNotIn method")
//			},
//		}
//
//		// use mockedManager in code that requires poller.Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// GetAllBundleUpdatesFunc mocks the GetAllBundleUpdates method.
	GetAllBundleUpdatesFunc func() map[types.NamespacedName]poller.BundleUpdate

	// GetAllPollErrorsFunc mocks the GetAllPollErrors method.
	GetAllPollErrorsFunc func() map[types.NamespacedName]poller.PollError

	// GetLatestBundlesFunc mocks the GetLatestBundles method.
	GetLatestBundlesFunc func() map[graph.WAFBundleKey]*graph.WAFBundleData

	// HasPollerFunc mocks the HasPoller method.
	HasPollerFunc func(policyNsName types.NamespacedName) bool

	// ReconcilePollerFunc mocks the ReconcilePoller method.
	ReconcilePollerFunc func(ctx context.Context, cfg poller.Config)

	// StopPollerFunc mocks the StopPoller method.
	StopPollerFunc func(policyNsName types.NamespacedName)

	// StopPollersNotInFunc mocks the StopPollersNotIn method.
	StopPollersNotInFunc func(activePolicies map[types.NamespacedName]struct{})

	// calls tracks calls to the methods.
	calls struct {
		// GetAllBundleUpdates holds details about calls to the GetAllBundleUpdates method.
		GetAllBundleUpdates []struct {
		}
		// GetAllPollErrors holds details about calls to the GetAllPollErrors method.
		GetAllPollErrors []struct {
		}
		// GetLatestBundles holds details about calls to the GetLatestBundles method.
		GetLatestBundles []struct {
		}
		// HasPoller holds details about calls to the HasPoller method.
		HasPoller []struct {
			// PolicyNsName is the policyNsName argument value.
			PolicyNsName types.NamespacedName
		}
		// ReconcilePoller holds details about calls to the ReconcilePoller method.
		ReconcilePoller []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg poller.Config
		}
		// StopPoller holds details about calls to the StopPoller method.
		StopPoller []struct {
			// PolicyNsName is the policyNsName argument value.
			PolicyNsName types.NamespacedName
		}
		// StopPollersNotIn holds details about calls to the StopPollersNotIn method.
		StopPollersNotIn []struct {
			// ActivePolicies is the activePolicies argument value.
			ActivePolicies map[types.NamespacedName]struct{}
		}
	}
	lockGetAllBundleUpdates sync.RWMutex
	lockGetAllPollErrors    sync.RWMutex
	lockGetLatestBundles    sync.RWMutex
	lockHasPoller           sync.RWMutex
	lockReconcilePoller     sync.RWMutex
	lockStopPoller          sync.RWMutex
	lockStopPollersNotIn    sync.RWMutex
}

// GetAllBundleUpdates calls GetAllBundleUpdatesFunc.
func (mock *ManagerMock) GetAllBundleUpdates() map[types.NamespacedName]poller.BundleUpdate {
	if mock.GetAllBundleUpdatesFunc == nil {
		panic("ManagerMock.GetAllBundleUpdatesFunc: method is nil but Manager.GetAllBundleUpdates was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAllBundleUpdates.Lock()
	mock.calls.GetAllBundleUpdates = append(mock.calls.GetAllBundleUpdates, callInfo)
	mock.lockGetAllBundleUpdates.Unlock()
	return mock.GetAllBundleUpdatesFunc()
}

// GetAllBundleUpdatesCalls gets all the calls that were made to GetAllBundleUpdates.
// Check the length with:
//
//	len(mockedManager.GetAllBundleUpdatesCalls())
func (mock *ManagerMock) GetAllBundleUpdatesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAllBundleUpdates.RLock()
	calls = mock.calls.GetAllBundleUpdates
	mock.lockGetAllBundleUpdates.RUnlock()
	return calls
}

// GetAllPollErrors calls GetAllPollErrorsFunc.
func (mock *ManagerMock) GetAllPollErrors() map[types.NamespacedName]poller.PollError {
	if mock.GetAllPollErrorsFunc == nil {
		panic("ManagerMock.GetAllPollErrorsFunc: method is nil but Manager.GetAllPollErrors was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAllPollErrors.Lock()
	mock.calls.GetAllPollErrors = append(mock.calls.GetAllPollErrors, callInfo)
	mock.lockGetAllPollErrors.Unlock()
	return mock.GetAllPollErrorsFunc()
}

// GetAllPollErrorsCalls gets all the calls that were made to GetAllPollErrors.
// Check the length with:
//
//	len(mockedManager.GetAllPollErrorsCalls())
func (mock *ManagerMock) GetAllPollErrorsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAllPollErrors.RLock()
	calls = mock.calls.GetAllPollErrors
	mock.lockGetAllPollErrors.RUnlock()
	return calls
}

// GetLatestBundles calls GetLatestBundlesFunc.
func (mock *ManagerMock) GetLatestBundles() map[graph.WAFBundleKey]*graph.WAFBundleData {
	if mock.GetLatestBundlesFunc == nil {
		panic("ManagerMock.GetLatestBundlesFunc: method is nil but Manager.GetLatestBundles was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLatestBundles.Lock()
	mock.calls.GetLatestBundles = append(mock.calls.GetLatestBundles, callInfo)
	mock.lockGetLatestBundles.Unlock()
	return mock.GetLatestBundlesFunc()
}

// GetLatestBundlesCalls gets all the calls that were made to GetLatestBundles.
// Check the length with:
//
//	len(mockedManager.GetLatestBundlesCalls())
func (mock *ManagerMock) GetLatestBundlesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLatestBundles.RLock()
	calls = mock.calls.GetLatestBundles
	mock.lockGetLatestBundles.RUnlock()
	return calls
}

// HasPoller calls HasPollerFunc.
func (mock *ManagerMock) HasPoller(policyNsName types.NamespacedName) bool {
	if mock.HasPollerFunc == nil {
		panic("ManagerMock.HasPollerFunc: method is nil but Manager.HasPoller was just called")
	}
	callInfo := struct {
		PolicyNsName types.NamespacedName
	}{
		PolicyNsName: policyNsName,
	}
	mock.lockHasPoller.Lock()
	mock.calls.HasPoller = append(mock.calls.HasPoller, callInfo)
	mock.lockHasPoller.Unlock()
	return mock.HasPollerFunc(policyNsName)
}

// HasPollerCalls gets all the calls that were made to HasPoller.
// Check the length with:
//
//	len(mockedManager.HasPollerCalls())
func (mock *ManagerMock) HasPollerCalls() []struct {
	PolicyNsName types.NamespacedName
} {
	var calls []struct {
		PolicyNsName types.NamespacedName
	}
	mock.lockHasPoller.RLock()
	calls = mock.calls.HasPoller
	mock.lockHasPoller.RUnlock()
	return calls
}

// ReconcilePoller calls ReconcilePollerFunc.
func (mock *ManagerMock) ReconcilePoller(ctx context.Context, cfg poller.Config) {
	if mock.ReconcilePollerFunc == nil {
		panic("ManagerMock.ReconcilePollerFunc: method is nil but Manager.ReconcilePoller was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg poller.Config
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockReconcilePoller.Lock()
	mock.calls.ReconcilePoller = append(mock.calls.ReconcilePoller, callInfo)
	mock.lockReconcilePoller.Unlock()
	mock.ReconcilePollerFunc(ctx, cfg)
}

// ReconcilePollerCalls gets all the calls that were made to ReconcilePoller.
// Check the length with:
//
//	len(mockedManager.ReconcilePollerCalls())
func (mock *ManagerMock) ReconcilePollerCalls() []struct {
	Ctx context.Context
	Cfg poller.Config
} {
	var calls []struct {
		Ctx context.Context
		Cfg poller.Config
	}
	mock.lockReconcilePoller.RLock()
	calls = mock.calls.ReconcilePoller
	mock.lockReconcilePoller.RUnlock()
	return calls
}

// StopPoller calls StopPollerFunc.
func (mock *ManagerMock) StopPoller(policyNsName types.NamespacedName) {
	if mock.StopPollerFunc == nil {
		panic("ManagerMock.StopPollerFunc: method is nil but Manager.StopPoller was just called")
	}
	callInfo := struct {
		PolicyNsName types.NamespacedName
	}{
		PolicyNsName: policyNsName,
	}
	mock.lockStopPoller.Lock()
	mock.calls.StopPoller = append(mock.calls.StopPoller, callInfo)
	mock.lockStopPoller.Unlock()
	mock.StopPollerFunc(policyNsName)
}

// StopPollerCalls gets all the calls that were made to StopPoller.
// Check the length with:
//
//	len(mockedManager.StopPollerCalls())
func (mock *ManagerMock) StopPollerCalls() []struct {
	PolicyNsName types.NamespacedName
} {
	var calls []struct {
		PolicyNsName types.NamespacedName
	}
	mock.lockStopPoller.RLock()
	calls = mock.calls.StopPoller
	mock.lockStopPoller.RUnlock()
	return calls
}

// StopPollersNotIn calls StopPollersNotInFunc.
func (mock *ManagerMock) StopPollersNotIn(activePolicies map[types.NamespacedName]struct{}) {
	if mock.StopPollersNotInFunc == nil {
		panic("ManagerMock.StopPollersNotInFunc: method is nil but Manager.StopPollersNotIn was just called")
	}
	callInfo := struct {
		ActivePolicies map[types.NamespacedName]struct{}
	}{
		ActivePolicies: activePolicies,
	}
	mock.lockStopPollersNotIn.Lock()
	mock.calls.StopPollersNotIn = append(mock.calls.StopPollersNotIn, callInfo)
	mock.lockStopPollersNotIn.Unlock()
	mock.StopPollersNotInFunc(activePolicies)
}

// StopPollersNotInCalls gets all the calls that were made to StopPollersNotIn.
// Check the length with:
//
//	len(mockedManager.StopPollersNotInCalls())
func (mock *ManagerMock) StopPollersNotInCalls() []struct {
	ActivePolicies map[types.NamespacedName]struct{}
} {
	var calls []struct {
		ActivePolicies map[types.NamespacedName]struct{}
	}
	mock.lockStopPollersNotIn.RLock()
	calls = mock.calls.StopPollersNotIn
	mock.lockStopPollersNotIn.RUnlock()
	return calls
}
