# This rule is not used by the project operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gateway.nginx.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: nginxgatewayfabric-viewer-role
rules:
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgatewayfabrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgatewayfabrics/status
  verbs:
  - get
