# This rule is not used by the project operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gateway.nginx.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: nginxgatewayfabric-editor-role
rules:
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgatewayfabrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgatewayfabrics/status
  verbs:
  - get
