apiVersion: v1
kind: Service
metadata:
  name: nginx-with-agent
  namespace: nginx-gateway
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-with-agent
