// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controllerfakes

import (
	"context"
	"github.com/go-logr/logr"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/record"
	"net/http"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/config"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/recorder"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/conversion"
	"sync"
)

// ManagerMock is a mock implementation of manager.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked manager.Manager
//		mockedManager := &ManagerMock{
//			AddFunc: func(runnable manager.Runnable) error {
//				panic("mock out the Add method")
//			},
//			AddHealthzCheckFunc: func(name string, check healthz.Checker) error {
//				panic("mock out the AddHealthzCheck method")
//			},
//			AddMetricsServerExtraHandlerFunc: func(path string, handler http.Handler) error {
//				panic("mock out the AddMetricsServerExtraHandler method")
//			},
//			AddReadyzCheckFunc: func(name string, check healthz.Checker) error {
//				panic("mock out the AddReadyzCheck method")
//			},
//			ElectedFunc: func() <-chan struct{} {
//				panic("mock out the Elected method")
//			},
//			GetAPIReaderFunc: func() client.Reader {
//				panic("mock out the GetAPIReader method")
//			},
//			GetCacheFunc: func() cache.Cache {
//				panic("mock out the GetCache method")
//			},
//			GetClientFunc: func() client.Client {
//				panic("mock out the GetClient method")
//			},
//			GetConfigFunc: func() *rest.Config {
//				panic("mock out the GetConfig method")
//			},
//			GetControllerOptionsFunc: func() config.Controller {
//				panic("mock out the GetControllerOptions method")
//			},
//			GetConverterRegistryFunc: func() conversion.Registry {
//				panic("mock out the GetConverterRegistry method")
//			},
//			GetEventRecorderFunc: func(name string) recorder.EventRecorder {
//				panic("mock out the GetEventRecorder method")
//			},
//			GetEventRecorderForFunc: func(name string) record.EventRecorder {
//				panic("mock out the GetEventRecorderFor method")
//			},
//			GetFieldIndexerFunc: func() client.FieldIndexer {
//				panic("mock out the GetFieldIndexer method")
//			},
//			GetHTTPClientFunc: func() *http.Client {
//				panic("mock out the GetHTTPClient method")
//			},
//			GetLoggerFunc: func() logr.Logger {
//				panic("mock out the GetLogger method")
//			},
//			GetRESTMapperFunc: func() meta.RESTMapper {
//				panic("mock out the GetRESTMapper method")
//			},
//			GetSchemeFunc: func() *runtime.Scheme {
//				panic("mock out the GetScheme method")
//			},
//			GetWebhookServerFunc: func() webhook.Server {
//				panic("mock out the GetWebhookServer method")
//			},
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedManager in code that requires manager.Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(runnable manager.Runnable) error

	// AddHealthzCheckFunc mocks the AddHealthzCheck method.
	AddHealthzCheckFunc func(name string, check healthz.Checker) error

	// AddMetricsServerExtraHandlerFunc mocks the AddMetricsServerExtraHandler method.
	AddMetricsServerExtraHandlerFunc func(path string, handler http.Handler) error

	// AddReadyzCheckFunc mocks the AddReadyzCheck method.
	AddReadyzCheckFunc func(name string, check healthz.Checker) error

	// ElectedFunc mocks the Elected method.
	ElectedFunc func() <-chan struct{}

	// GetAPIReaderFunc mocks the GetAPIReader method.
	GetAPIReaderFunc func() client.Reader

	// GetCacheFunc mocks the GetCache method.
	GetCacheFunc func() cache.Cache

	// GetClientFunc mocks the GetClient method.
	GetClientFunc func() client.Client

	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func() *rest.Config

	// GetControllerOptionsFunc mocks the GetControllerOptions method.
	GetControllerOptionsFunc func() config.Controller

	// GetConverterRegistryFunc mocks the GetConverterRegistry method.
	GetConverterRegistryFunc func() conversion.Registry

	// GetEventRecorderFunc mocks the GetEventRecorder method.
	GetEventRecorderFunc func(name string) recorder.EventRecorder

	// GetEventRecorderForFunc mocks the GetEventRecorderFor method.
	GetEventRecorderForFunc func(name string) record.EventRecorder

	// GetFieldIndexerFunc mocks the GetFieldIndexer method.
	GetFieldIndexerFunc func() client.FieldIndexer

	// GetHTTPClientFunc mocks the GetHTTPClient method.
	GetHTTPClientFunc func() *http.Client

	// GetLoggerFunc mocks the GetLogger method.
	GetLoggerFunc func() logr.Logger

	// GetRESTMapperFunc mocks the GetRESTMapper method.
	GetRESTMapperFunc func() meta.RESTMapper

	// GetSchemeFunc mocks the GetScheme method.
	GetSchemeFunc func() *runtime.Scheme

	// GetWebhookServerFunc mocks the GetWebhookServer method.
	GetWebhookServerFunc func() webhook.Server

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Runnable is the runnable argument value.
			Runnable manager.Runnable
		}
		// AddHealthzCheck holds details about calls to the AddHealthzCheck method.
		AddHealthzCheck []struct {
			// Name is the name argument value.
			Name string
			// Check is the check argument value.
			Check healthz.Checker
		}
		// AddMetricsServerExtraHandler holds details about calls to the AddMetricsServerExtraHandler method.
		AddMetricsServerExtraHandler []struct {
			// Path is the path argument value.
			Path string
			// Handler is the handler argument value.
			Handler http.Handler
		}
		// AddReadyzCheck holds details about calls to the AddReadyzCheck method.
		AddReadyzCheck []struct {
			// Name is the name argument value.
			Name string
			// Check is the check argument value.
			Check healthz.Checker
		}
		// Elected holds details about calls to the Elected method.
		Elected []struct {
		}
		// GetAPIReader holds details about calls to the GetAPIReader method.
		GetAPIReader []struct {
		}
		// GetCache holds details about calls to the GetCache method.
		GetCache []struct {
		}
		// GetClient holds details about calls to the GetClient method.
		GetClient []struct {
		}
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
		}
		// GetControllerOptions holds details about calls to the GetControllerOptions method.
		GetControllerOptions []struct {
		}
		// GetConverterRegistry holds details about calls to the GetConverterRegistry method.
		GetConverterRegistry []struct {
		}
		// GetEventRecorder holds details about calls to the GetEventRecorder method.
		GetEventRecorder []struct {
			// Name is the name argument value.
			Name string
		}
		// GetEventRecorderFor holds details about calls to the GetEventRecorderFor method.
		GetEventRecorderFor []struct {
			// Name is the name argument value.
			Name string
		}
		// GetFieldIndexer holds details about calls to the GetFieldIndexer method.
		GetFieldIndexer []struct {
		}
		// GetHTTPClient holds details about calls to the GetHTTPClient method.
		GetHTTPClient []struct {
		}
		// GetLogger holds details about calls to the GetLogger method.
		GetLogger []struct {
		}
		// GetRESTMapper holds details about calls to the GetRESTMapper method.
		GetRESTMapper []struct {
		}
		// GetScheme holds details about calls to the GetScheme method.
		GetScheme []struct {
		}
		// GetWebhookServer holds details about calls to the GetWebhookServer method.
		GetWebhookServer []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAdd                          sync.RWMutex
	lockAddHealthzCheck              sync.RWMutex
	lockAddMetricsServerExtraHandler sync.RWMutex
	lockAddReadyzCheck               sync.RWMutex
	lockElected                      sync.RWMutex
	lockGetAPIReader                 sync.RWMutex
	lockGetCache                     sync.RWMutex
	lockGetClient                    sync.RWMutex
	lockGetConfig                    sync.RWMutex
	lockGetControllerOptions         sync.RWMutex
	lockGetConverterRegistry         sync.RWMutex
	lockGetEventRecorder             sync.RWMutex
	lockGetEventRecorderFor          sync.RWMutex
	lockGetFieldIndexer              sync.RWMutex
	lockGetHTTPClient                sync.RWMutex
	lockGetLogger                    sync.RWMutex
	lockGetRESTMapper                sync.RWMutex
	lockGetScheme                    sync.RWMutex
	lockGetWebhookServer             sync.RWMutex
	lockStart                        sync.RWMutex
}

// Add calls AddFunc.
func (mock *ManagerMock) Add(runnable manager.Runnable) error {
	if mock.AddFunc == nil {
		panic("ManagerMock.AddFunc: method is nil but Manager.Add was just called")
	}
	callInfo := struct {
		Runnable manager.Runnable
	}{
		Runnable: runnable,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(runnable)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedManager.AddCalls())
func (mock *ManagerMock) AddCalls() []struct {
	Runnable manager.Runnable
} {
	var calls []struct {
		Runnable manager.Runnable
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// AddHealthzCheck calls AddHealthzCheckFunc.
func (mock *ManagerMock) AddHealthzCheck(name string, check healthz.Checker) error {
	if mock.AddHealthzCheckFunc == nil {
		panic("ManagerMock.AddHealthzCheckFunc: method is nil but Manager.AddHealthzCheck was just called")
	}
	callInfo := struct {
		Name  string
		Check healthz.Checker
	}{
		Name:  name,
		Check: check,
	}
	mock.lockAddHealthzCheck.Lock()
	mock.calls.AddHealthzCheck = append(mock.calls.AddHealthzCheck, callInfo)
	mock.lockAddHealthzCheck.Unlock()
	return mock.AddHealthzCheckFunc(name, check)
}

// AddHealthzCheckCalls gets all the calls that were made to AddHealthzCheck.
// Check the length with:
//
//	len(mockedManager.AddHealthzCheckCalls())
func (mock *ManagerMock) AddHealthzCheckCalls() []struct {
	Name  string
	Check healthz.Checker
} {
	var calls []struct {
		Name  string
		Check healthz.Checker
	}
	mock.lockAddHealthzCheck.RLock()
	calls = mock.calls.AddHealthzCheck
	mock.lockAddHealthzCheck.RUnlock()
	return calls
}

// AddMetricsServerExtraHandler calls AddMetricsServerExtraHandlerFunc.
func (mock *ManagerMock) AddMetricsServerExtraHandler(path string, handler http.Handler) error {
	if mock.AddMetricsServerExtraHandlerFunc == nil {
		panic("ManagerMock.AddMetricsServerExtraHandlerFunc: method is nil but Manager.AddMetricsServerExtraHandler was just called")
	}
	callInfo := struct {
		Path    string
		Handler http.Handler
	}{
		Path:    path,
		Handler: handler,
	}
	mock.lockAddMetricsServerExtraHandler.Lock()
	mock.calls.AddMetricsServerExtraHandler = append(mock.calls.AddMetricsServerExtraHandler, callInfo)
	mock.lockAddMetricsServerExtraHandler.Unlock()
	return mock.AddMetricsServerExtraHandlerFunc(path, handler)
}

// AddMetricsServerExtraHandlerCalls gets all the calls that were made to AddMetricsServerExtraHandler.
// Check the length with:
//
//	len(mockedManager.AddMetricsServerExtraHandlerCalls())
func (mock *ManagerMock) AddMetricsServerExtraHandlerCalls() []struct {
	Path    string
	Handler http.Handler
} {
	var calls []struct {
		Path    string
		Handler http.Handler
	}
	mock.lockAddMetricsServerExtraHandler.RLock()
	calls = mock.calls.AddMetricsServerExtraHandler
	mock.lockAddMetricsServerExtraHandler.RUnlock()
	return calls
}

// AddReadyzCheck calls AddReadyzCheckFunc.
func (mock *ManagerMock) AddReadyzCheck(name string, check healthz.Checker) error {
	if mock.AddReadyzCheckFunc == nil {
		panic("ManagerMock.AddReadyzCheckFunc: method is nil but Manager.AddReadyzCheck was just called")
	}
	callInfo := struct {
		Name  string
		Check healthz.Checker
	}{
		Name:  name,
		Check: check,
	}
	mock.lockAddReadyzCheck.Lock()
	mock.calls.AddReadyzCheck = append(mock.calls.AddReadyzCheck, callInfo)
	mock.lockAddReadyzCheck.Unlock()
	return mock.AddReadyzCheckFunc(name, check)
}

// AddReadyzCheckCalls gets all the calls that were made to AddReadyzCheck.
// Check the length with:
//
//	len(mockedManager.AddReadyzCheckCalls())
func (mock *ManagerMock) AddReadyzCheckCalls() []struct {
	Name  string
	Check healthz.Checker
} {
	var calls []struct {
		Name  string
		Check healthz.Checker
	}
	mock.lockAddReadyzCheck.RLock()
	calls = mock.calls.AddReadyzCheck
	mock.lockAddReadyzCheck.RUnlock()
	return calls
}

// Elected calls ElectedFunc.
func (mock *ManagerMock) Elected() <-chan struct{} {
	if mock.ElectedFunc == nil {
		panic("ManagerMock.ElectedFunc: method is nil but Manager.Elected was just called")
	}
	callInfo := struct {
	}{}
	mock.lockElected.Lock()
	mock.calls.Elected = append(mock.calls.Elected, callInfo)
	mock.lockElected.Unlock()
	return mock.ElectedFunc()
}

// ElectedCalls gets all the calls that were made to Elected.
// Check the length with:
//
//	len(mockedManager.ElectedCalls())
func (mock *ManagerMock) ElectedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockElected.RLock()
	calls = mock.calls.Elected
	mock.lockElected.RUnlock()
	return calls
}

// GetAPIReader calls GetAPIReaderFunc.
func (mock *ManagerMock) GetAPIReader() client.Reader {
	if mock.GetAPIReaderFunc == nil {
		panic("ManagerMock.GetAPIReaderFunc: method is nil but Manager.GetAPIReader was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAPIReader.Lock()
	mock.calls.GetAPIReader = append(mock.calls.GetAPIReader, callInfo)
	mock.lockGetAPIReader.Unlock()
	return mock.GetAPIReaderFunc()
}

// GetAPIReaderCalls gets all the calls that were made to GetAPIReader.
// Check the length with:
//
//	len(mockedManager.GetAPIReaderCalls())
func (mock *ManagerMock) GetAPIReaderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAPIReader.RLock()
	calls = mock.calls.GetAPIReader
	mock.lockGetAPIReader.RUnlock()
	return calls
}

// GetCache calls GetCacheFunc.
func (mock *ManagerMock) GetCache() cache.Cache {
	if mock.GetCacheFunc == nil {
		panic("ManagerMock.GetCacheFunc: method is nil but Manager.GetCache was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCache.Lock()
	mock.calls.GetCache = append(mock.calls.GetCache, callInfo)
	mock.lockGetCache.Unlock()
	return mock.GetCacheFunc()
}

// GetCacheCalls gets all the calls that were made to GetCache.
// Check the length with:
//
//	len(mockedManager.GetCacheCalls())
func (mock *ManagerMock) GetCacheCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCache.RLock()
	calls = mock.calls.GetCache
	mock.lockGetCache.RUnlock()
	return calls
}

// GetClient calls GetClientFunc.
func (mock *ManagerMock) GetClient() client.Client {
	if mock.GetClientFunc == nil {
		panic("ManagerMock.GetClientFunc: method is nil but Manager.GetClient was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetClient.Lock()
	mock.calls.GetClient = append(mock.calls.GetClient, callInfo)
	mock.lockGetClient.Unlock()
	return mock.GetClientFunc()
}

// GetClientCalls gets all the calls that were made to GetClient.
// Check the length with:
//
//	len(mockedManager.GetClientCalls())
func (mock *ManagerMock) GetClientCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetClient.RLock()
	calls = mock.calls.GetClient
	mock.lockGetClient.RUnlock()
	return calls
}

// GetConfig calls GetConfigFunc.
func (mock *ManagerMock) GetConfig() *rest.Config {
	if mock.GetConfigFunc == nil {
		panic("ManagerMock.GetConfigFunc: method is nil but Manager.GetConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc()
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//
//	len(mockedManager.GetConfigCalls())
func (mock *ManagerMock) GetConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}

// GetControllerOptions calls GetControllerOptionsFunc.
func (mock *ManagerMock) GetControllerOptions() config.Controller {
	if mock.GetControllerOptionsFunc == nil {
		panic("ManagerMock.GetControllerOptionsFunc: method is nil but Manager.GetControllerOptions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetControllerOptions.Lock()
	mock.calls.GetControllerOptions = append(mock.calls.GetControllerOptions, callInfo)
	mock.lockGetControllerOptions.Unlock()
	return mock.GetControllerOptionsFunc()
}

// GetControllerOptionsCalls gets all the calls that were made to GetControllerOptions.
// Check the length with:
//
//	len(mockedManager.GetControllerOptionsCalls())
func (mock *ManagerMock) GetControllerOptionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetControllerOptions.RLock()
	calls = mock.calls.GetControllerOptions
	mock.lockGetControllerOptions.RUnlock()
	return calls
}

// GetConverterRegistry calls GetConverterRegistryFunc.
func (mock *ManagerMock) GetConverterRegistry() conversion.Registry {
	if mock.GetConverterRegistryFunc == nil {
		panic("ManagerMock.GetConverterRegistryFunc: method is nil but Manager.GetConverterRegistry was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConverterRegistry.Lock()
	mock.calls.GetConverterRegistry = append(mock.calls.GetConverterRegistry, callInfo)
	mock.lockGetConverterRegistry.Unlock()
	return mock.GetConverterRegistryFunc()
}

// GetConverterRegistryCalls gets all the calls that were made to GetConverterRegistry.
// Check the length with:
//
//	len(mockedManager.GetConverterRegistryCalls())
func (mock *ManagerMock) GetConverterRegistryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConverterRegistry.RLock()
	calls = mock.calls.GetConverterRegistry
	mock.lockGetConverterRegistry.RUnlock()
	return calls
}

// GetEventRecorder calls GetEventRecorderFunc.
func (mock *ManagerMock) GetEventRecorder(name string) recorder.EventRecorder {
	if mock.GetEventRecorderFunc == nil {
		panic("ManagerMock.GetEventRecorderFunc: method is nil but Manager.GetEventRecorder was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetEventRecorder.Lock()
	mock.calls.GetEventRecorder = append(mock.calls.GetEventRecorder, callInfo)
	mock.lockGetEventRecorder.Unlock()
	return mock.GetEventRecorderFunc(name)
}

// GetEventRecorderCalls gets all the calls that were made to GetEventRecorder.
// Check the length with:
//
//	len(mockedManager.GetEventRecorderCalls())
func (mock *ManagerMock) GetEventRecorderCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetEventRecorder.RLock()
	calls = mock.calls.GetEventRecorder
	mock.lockGetEventRecorder.RUnlock()
	return calls
}

// GetEventRecorderFor calls GetEventRecorderForFunc.
func (mock *ManagerMock) GetEventRecorderFor(name string) record.EventRecorder {
	if mock.GetEventRecorderForFunc == nil {
		panic("ManagerMock.GetEventRecorderForFunc: method is nil but Manager.GetEventRecorderFor was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetEventRecorderFor.Lock()
	mock.calls.GetEventRecorderFor = append(mock.calls.GetEventRecorderFor, callInfo)
	mock.lockGetEventRecorderFor.Unlock()
	return mock.GetEventRecorderForFunc(name)
}

// GetEventRecorderForCalls gets all the calls that were made to GetEventRecorderFor.
// Check the length with:
//
//	len(mockedManager.GetEventRecorderForCalls())
func (mock *ManagerMock) GetEventRecorderForCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetEventRecorderFor.RLock()
	calls = mock.calls.GetEventRecorderFor
	mock.lockGetEventRecorderFor.RUnlock()
	return calls
}

// GetFieldIndexer calls GetFieldIndexerFunc.
func (mock *ManagerMock) GetFieldIndexer() client.FieldIndexer {
	if mock.GetFieldIndexerFunc == nil {
		panic("ManagerMock.GetFieldIndexerFunc: method is nil but Manager.GetFieldIndexer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetFieldIndexer.Lock()
	mock.calls.GetFieldIndexer = append(mock.calls.GetFieldIndexer, callInfo)
	mock.lockGetFieldIndexer.Unlock()
	return mock.GetFieldIndexerFunc()
}

// GetFieldIndexerCalls gets all the calls that were made to GetFieldIndexer.
// Check the length with:
//
//	len(mockedManager.GetFieldIndexerCalls())
func (mock *ManagerMock) GetFieldIndexerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetFieldIndexer.RLock()
	calls = mock.calls.GetFieldIndexer
	mock.lockGetFieldIndexer.RUnlock()
	return calls
}

// GetHTTPClient calls GetHTTPClientFunc.
func (mock *ManagerMock) GetHTTPClient() *http.Client {
	if mock.GetHTTPClientFunc == nil {
		panic("ManagerMock.GetHTTPClientFunc: method is nil but Manager.GetHTTPClient was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHTTPClient.Lock()
	mock.calls.GetHTTPClient = append(mock.calls.GetHTTPClient, callInfo)
	mock.lockGetHTTPClient.Unlock()
	return mock.GetHTTPClientFunc()
}

// GetHTTPClientCalls gets all the calls that were made to GetHTTPClient.
// Check the length with:
//
//	len(mockedManager.GetHTTPClientCalls())
func (mock *ManagerMock) GetHTTPClientCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHTTPClient.RLock()
	calls = mock.calls.GetHTTPClient
	mock.lockGetHTTPClient.RUnlock()
	return calls
}

// GetLogger calls GetLoggerFunc.
func (mock *ManagerMock) GetLogger() logr.Logger {
	if mock.GetLoggerFunc == nil {
		panic("ManagerMock.GetLoggerFunc: method is nil but Manager.GetLogger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLogger.Lock()
	mock.calls.GetLogger = append(mock.calls.GetLogger, callInfo)
	mock.lockGetLogger.Unlock()
	return mock.GetLoggerFunc()
}

// GetLoggerCalls gets all the calls that were made to GetLogger.
// Check the length with:
//
//	len(mockedManager.GetLoggerCalls())
func (mock *ManagerMock) GetLoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLogger.RLock()
	calls = mock.calls.GetLogger
	mock.lockGetLogger.RUnlock()
	return calls
}

// GetRESTMapper calls GetRESTMapperFunc.
func (mock *ManagerMock) GetRESTMapper() meta.RESTMapper {
	if mock.GetRESTMapperFunc == nil {
		panic("ManagerMock.GetRESTMapperFunc: method is nil but Manager.GetRESTMapper was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetRESTMapper.Lock()
	mock.calls.GetRESTMapper = append(mock.calls.GetRESTMapper, callInfo)
	mock.lockGetRESTMapper.Unlock()
	return mock.GetRESTMapperFunc()
}

// GetRESTMapperCalls gets all the calls that were made to GetRESTMapper.
// Check the length with:
//
//	len(mockedManager.GetRESTMapperCalls())
func (mock *ManagerMock) GetRESTMapperCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetRESTMapper.RLock()
	calls = mock.calls.GetRESTMapper
	mock.lockGetRESTMapper.RUnlock()
	return calls
}

// GetScheme calls GetSchemeFunc.
func (mock *ManagerMock) GetScheme() *runtime.Scheme {
	if mock.GetSchemeFunc == nil {
		panic("ManagerMock.GetSchemeFunc: method is nil but Manager.GetScheme was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetScheme.Lock()
	mock.calls.GetScheme = append(mock.calls.GetScheme, callInfo)
	mock.lockGetScheme.Unlock()
	return mock.GetSchemeFunc()
}

// GetSchemeCalls gets all the calls that were made to GetScheme.
// Check the length with:
//
//	len(mockedManager.GetSchemeCalls())
func (mock *ManagerMock) GetSchemeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetScheme.RLock()
	calls = mock.calls.GetScheme
	mock.lockGetScheme.RUnlock()
	return calls
}

// GetWebhookServer calls GetWebhookServerFunc.
func (mock *ManagerMock) GetWebhookServer() webhook.Server {
	if mock.GetWebhookServerFunc == nil {
		panic("ManagerMock.GetWebhookServerFunc: method is nil but Manager.GetWebhookServer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetWebhookServer.Lock()
	mock.calls.GetWebhookServer = append(mock.calls.GetWebhookServer, callInfo)
	mock.lockGetWebhookServer.Unlock()
	return mock.GetWebhookServerFunc()
}

// GetWebhookServerCalls gets all the calls that were made to GetWebhookServer.
// Check the length with:
//
//	len(mockedManager.GetWebhookServerCalls())
func (mock *ManagerMock) GetWebhookServerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetWebhookServer.RLock()
	calls = mock.calls.GetWebhookServer
	mock.lockGetWebhookServer.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *ManagerMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("ManagerMock.StartFunc: method is nil but Manager.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedManager.StartCalls())
func (mock *ManagerMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
