// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controllerfakes

import (
	"context"
	"sigs.k8s.io/controller-runtime/pkg/cache/cacheapi"
	"sync"
)

// FieldIndexerMock is a mock implementation of client.FieldIndexer.
//
//	func TestSomethingThatUsesFieldIndexer(t *testing.T) {
//
//		// make and configure a mocked client.FieldIndexer
//		mockedFieldIndexer := &FieldIndexerMock{
//			IndexFieldFunc: func(ctx context.Context, obj cacheapi.Object, field string, extractValue cacheapi.IndexerFunc) error {
//				panic("mock out the IndexField method")
//			},
//		}
//
//		// use mockedFieldIndexer in code that requires client.FieldIndexer
//		// and then make assertions.
//
//	}
type FieldIndexerMock struct {
	// IndexFieldFunc mocks the IndexField method.
	IndexFieldFunc func(ctx context.Context, obj cacheapi.Object, field string, extractValue cacheapi.IndexerFunc) error

	// calls tracks calls to the methods.
	calls struct {
		// IndexField holds details about calls to the IndexField method.
		IndexField []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj cacheapi.Object
			// Field is the field argument value.
			Field string
			// ExtractValue is the extractValue argument value.
			ExtractValue cacheapi.IndexerFunc
		}
	}
	lockIndexField sync.RWMutex
}

// IndexField calls IndexFieldFunc.
func (mock *FieldIndexerMock) IndexField(ctx context.Context, obj cacheapi.Object, field string, extractValue cacheapi.IndexerFunc) error {
	if mock.IndexFieldFunc == nil {
		panic("FieldIndexerMock.IndexFieldFunc: method is nil but FieldIndexer.IndexField was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Obj          cacheapi.Object
		Field        string
		ExtractValue cacheapi.IndexerFunc
	}{
		Ctx:          ctx,
		Obj:          obj,
		Field:        field,
		ExtractValue: extractValue,
	}
	mock.lockIndexField.Lock()
	mock.calls.IndexField = append(mock.calls.IndexField, callInfo)
	mock.lockIndexField.Unlock()
	return mock.IndexFieldFunc(ctx, obj, field, extractValue)
}

// IndexFieldCalls gets all the calls that were made to IndexField.
// Check the length with:
//
//	len(mockedFieldIndexer.IndexFieldCalls())
func (mock *FieldIndexerMock) IndexFieldCalls() []struct {
	Ctx          context.Context
	Obj          cacheapi.Object
	Field        string
	ExtractValue cacheapi.IndexerFunc
} {
	var calls []struct {
		Ctx          context.Context
		Obj          cacheapi.Object
		Field        string
		ExtractValue cacheapi.IndexerFunc
	}
	mock.lockIndexField.RLock()
	calls = mock.calls.IndexField
	mock.lockIndexField.RUnlock()
	return calls
}
