// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controllerfakes

import (
	"context"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

// GetterMock is a mock implementation of controller.Getter.
//
//	func TestSomethingThatUsesGetter(t *testing.T) {
//
//		// make and configure a mocked controller.Getter
//		mockedGetter := &GetterMock{
//			GetFunc: func(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedGetter in code that requires controller.Getter
//		// and then make assertions.
//
//	}
type GetterMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key client.ObjectKey
			// Obj is the obj argument value.
			Obj client.Object
			// Opts is the opts argument value.
			Opts []client.GetOption
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *GetterMock) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	if mock.GetFunc == nil {
		panic("GetterMock.GetFunc: method is nil but Getter.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Key  client.ObjectKey
		Obj  client.Object
		Opts []client.GetOption
	}{
		Ctx:  ctx,
		Key:  key,
		Obj:  obj,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key, obj, opts...)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGetter.GetCalls())
func (mock *GetterMock) GetCalls() []struct {
	Ctx  context.Context
	Key  client.ObjectKey
	Obj  client.Object
	Opts []client.GetOption
} {
	var calls []struct {
		Ctx  context.Context
		Key  client.ObjectKey
		Obj  client.Object
		Opts []client.GetOption
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
