apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: access-control
spec:
  snippets:
    - context: http.server.location
      value: |
        allow 10.0.0.0/8;
        deny all;
