apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: gw
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  body:
    maxSize: 10m
    timeout: 30s
  keepAlive:
    requests: 100
    time: 5s
    timeout:
      server: 2s
      header: 1s
