// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package policiesfakes

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
	"sync"
)

// PolicyMock is a mock implementation of policies.Policy.
//
//	func TestSomethingThatUsesPolicy(t *testing.T) {
//
//		// make and configure a mocked policies.Policy
//		mockedPolicy := &PolicyMock{
//			DeepCopyObjectFunc: func() runtime.Object {
//				panic("mock out the DeepCopyObject method")
//			},
//			GetAnnotationsFunc: func() map[string]string {
//				panic("mock out the GetAnnotations method")
//			},
//			GetCreationTimestampFunc: func() v1.Time {
//				panic("mock out the GetCreationTimestamp method")
//			},
//			GetDeletionGracePeriodSecondsFunc: func() *int64 {
//				panic("mock out the GetDeletionGracePeriodSeconds method")
//			},
//			GetDeletionTimestampFunc: func() *v1.Time {
//				panic("mock out the GetDeletionTimestamp method")
//			},
//			GetFinalizersFunc: func() []string {
//				panic("mock out the GetFinalizers method")
//			},
//			GetGenerateNameFunc: func() string {
//				panic("mock out the GetGenerateName method")
//			},
//			GetGenerationFunc: func() int64 {
//				panic("mock out the GetGeneration method")
//			},
//			GetLabelsFunc: func() map[string]string {
//				panic("mock out the GetLabels method")
//			},
//			GetManagedFieldsFunc: func() []v1.ManagedFieldsEntry {
//				panic("mock out the GetManagedFields method")
//			},
//			GetNameFunc: func() string {
//				panic("mock out the GetName method")
//			},
//			GetNamespaceFunc: func() string {
//				panic("mock out the GetNamespace method")
//			},
//			GetObjectKindFunc: func() schema.ObjectKind {
//				panic("mock out the GetObjectKind method")
//			},
//			GetOwnerReferencesFunc: func() []v1.OwnerReference {
//				panic("mock out the GetOwnerReferences method")
//			},
//			GetPolicyStatusFunc: func() gatewayv1.PolicyStatus {
//				panic("mock out the GetPolicyStatus method")
//			},
//			GetResourceVersionFunc: func() string {
//				panic("mock out the GetResourceVersion method")
//			},
//			GetSelfLinkFunc: func() string {
//				panic("mock out the GetSelfLink method")
//			},
//			GetTargetRefsFunc: func() []gatewayv1.LocalPolicyTargetReference {
//				panic("mock out the GetTargetRefs method")
//			},
//			GetUIDFunc: func() types.UID {
//				panic("mock out the GetUID method")
//			},
//			SetAnnotationsFunc: func(annotations map[string]string)  {
//				panic("mock out the SetAnnotations method")
//			},
//			SetCreationTimestampFunc: func(timestamp v1.Time)  {
//				panic("mock out the SetCreationTimestamp method")
//			},
//			SetDeletionGracePeriodSecondsFunc: func(n *int64)  {
//				panic("mock out the SetDeletionGracePeriodSeconds method")
//			},
//			SetDeletionTimestampFunc: func(timestamp *v1.Time)  {
//				panic("mock out the SetDeletionTimestamp method")
//			},
//			SetFinalizersFunc: func(finalizers []string)  {
//				panic("mock out the SetFinalizers method")
//			},
//			SetGenerateNameFunc: func(name string)  {
//				panic("mock out the SetGenerateName method")
//			},
//			SetGenerationFunc: func(generation int64)  {
//				panic("mock out the SetGeneration method")
//			},
//			SetLabelsFunc: func(labels map[string]string)  {
//				panic("mock out the SetLabels method")
//			},
//			SetManagedFieldsFunc: func(managedFields []v1.ManagedFieldsEntry)  {
//				panic("mock out the SetManagedFields method")
//			},
//			SetNameFunc: func(name string)  {
//				panic("mock out the SetName method")
//			},
//			SetNamespaceFunc: func(namespace string)  {
//				panic("mock out the SetNamespace method")
//			},
//			SetOwnerReferencesFunc: func(ownerReferences []v1.OwnerReference)  {
//				panic("mock out the SetOwnerReferences method")
//			},
//			SetPolicyStatusFunc: func(status gatewayv1.PolicyStatus)  {
//				panic("mock out the SetPolicyStatus method")
//			},
//			SetResourceVersionFunc: func(version string)  {
//				panic("mock out the SetResourceVersion method")
//			},
//			SetSelfLinkFunc: func(selfLink string)  {
//				panic("mock out the SetSelfLink method")
//			},
//			SetUIDFunc: func(uid types.UID)  {
//				panic("mock out the SetUID method")
//			},
//		}
//
//		// use mockedPolicy in code that requires policies.Policy
//		// and then make assertions.
//
//	}
type PolicyMock struct {
	// DeepCopyObjectFunc mocks the DeepCopyObject method.
	DeepCopyObjectFunc func() runtime.Object

	// GetAnnotationsFunc mocks the GetAnnotations method.
	GetAnnotationsFunc func() map[string]string

	// GetCreationTimestampFunc mocks the GetCreationTimestamp method.
	GetCreationTimestampFunc func() v1.Time

	// GetDeletionGracePeriodSecondsFunc mocks the GetDeletionGracePeriodSeconds method.
	GetDeletionGracePeriodSecondsFunc func() *int64

	// GetDeletionTimestampFunc mocks the GetDeletionTimestamp method.
	GetDeletionTimestampFunc func() *v1.Time

	// GetFinalizersFunc mocks the GetFinalizers method.
	GetFinalizersFunc func() []string

	// GetGenerateNameFunc mocks the GetGenerateName method.
	GetGenerateNameFunc func() string

	// GetGenerationFunc mocks the GetGeneration method.
	GetGenerationFunc func() int64

	// GetLabelsFunc mocks the GetLabels method.
	GetLabelsFunc func() map[string]string

	// GetManagedFieldsFunc mocks the GetManagedFields method.
	GetManagedFieldsFunc func() []v1.ManagedFieldsEntry

	// GetNameFunc mocks the GetName method.
	GetNameFunc func() string

	// GetNamespaceFunc mocks the GetNamespace method.
	GetNamespaceFunc func() string

	// GetObjectKindFunc mocks the GetObjectKind method.
	GetObjectKindFunc func() schema.ObjectKind

	// GetOwnerReferencesFunc mocks the GetOwnerReferences method.
	GetOwnerReferencesFunc func() []v1.OwnerReference

	// GetPolicyStatusFunc mocks the GetPolicyStatus method.
	GetPolicyStatusFunc func() gatewayv1.PolicyStatus

	// GetResourceVersionFunc mocks the GetResourceVersion method.
	GetResourceVersionFunc func() string

	// GetSelfLinkFunc mocks the GetSelfLink method.
	GetSelfLinkFunc func() string

	// GetTargetRefsFunc mocks the GetTargetRefs method.
	GetTargetRefsFunc func() []gatewayv1.LocalPolicyTargetReference

	// GetUIDFunc mocks the GetUID method.
	GetUIDFunc func() types.UID

	// SetAnnotationsFunc mocks the SetAnnotations method.
	SetAnnotationsFunc func(annotations map[string]string)

	// SetCreationTimestampFunc mocks the SetCreationTimestamp method.
	SetCreationTimestampFunc func(timestamp v1.Time)

	// SetDeletionGracePeriodSecondsFunc mocks the SetDeletionGracePeriodSeconds method.
	SetDeletionGracePeriodSecondsFunc func(n *int64)

	// SetDeletionTimestampFunc mocks the SetDeletionTimestamp method.
	SetDeletionTimestampFunc func(timestamp *v1.Time)

	// SetFinalizersFunc mocks the SetFinalizers method.
	SetFinalizersFunc func(finalizers []string)

	// SetGenerateNameFunc mocks the SetGenerateName method.
	SetGenerateNameFunc func(name string)

	// SetGenerationFunc mocks the SetGeneration method.
	SetGenerationFunc func(generation int64)

	// SetLabelsFunc mocks the SetLabels method.
	SetLabelsFunc func(labels map[string]string)

	// SetManagedFieldsFunc mocks the SetManagedFields method.
	SetManagedFieldsFunc func(managedFields []v1.ManagedFieldsEntry)

	// SetNameFunc mocks the SetName method.
	SetNameFunc func(name string)

	// SetNamespaceFunc mocks the SetNamespace method.
	SetNamespaceFunc func(namespace string)

	// SetOwnerReferencesFunc mocks the SetOwnerReferences method.
	SetOwnerReferencesFunc func(ownerReferences []v1.OwnerReference)

	// SetPolicyStatusFunc mocks the SetPolicyStatus method.
	SetPolicyStatusFunc func(status gatewayv1.PolicyStatus)

	// SetResourceVersionFunc mocks the SetResourceVersion method.
	SetResourceVersionFunc func(version string)

	// SetSelfLinkFunc mocks the SetSelfLink method.
	SetSelfLinkFunc func(selfLink string)

	// SetUIDFunc mocks the SetUID method.
	SetUIDFunc func(uid types.UID)

	// calls tracks calls to the methods.
	calls struct {
		// DeepCopyObject holds details about calls to the DeepCopyObject method.
		DeepCopyObject []struct {
		}
		// GetAnnotations holds details about calls to the GetAnnotations method.
		GetAnnotations []struct {
		}
		// GetCreationTimestamp holds details about calls to the GetCreationTimestamp method.
		GetCreationTimestamp []struct {
		}
		// GetDeletionGracePeriodSeconds holds details about calls to the GetDeletionGracePeriodSeconds method.
		GetDeletionGracePeriodSeconds []struct {
		}
		// GetDeletionTimestamp holds details about calls to the GetDeletionTimestamp method.
		GetDeletionTimestamp []struct {
		}
		// GetFinalizers holds details about calls to the GetFinalizers method.
		GetFinalizers []struct {
		}
		// GetGenerateName holds details about calls to the GetGenerateName method.
		GetGenerateName []struct {
		}
		// GetGeneration holds details about calls to the GetGeneration method.
		GetGeneration []struct {
		}
		// GetLabels holds details about calls to the GetLabels method.
		GetLabels []struct {
		}
		// GetManagedFields holds details about calls to the GetManagedFields method.
		GetManagedFields []struct {
		}
		// GetName holds details about calls to the GetName method.
		GetName []struct {
		}
		// GetNamespace holds details about calls to the GetNamespace method.
		GetNamespace []struct {
		}
		// GetObjectKind holds details about calls to the GetObjectKind method.
		GetObjectKind []struct {
		}
		// GetOwnerReferences holds details about calls to the GetOwnerReferences method.
		GetOwnerReferences []struct {
		}
		// GetPolicyStatus holds details about calls to the GetPolicyStatus method.
		GetPolicyStatus []struct {
		}
		// GetResourceVersion holds details about calls to the GetResourceVersion method.
		GetResourceVersion []struct {
		}
		// GetSelfLink holds details about calls to the GetSelfLink method.
		GetSelfLink []struct {
		}
		// GetTargetRefs holds details about calls to the GetTargetRefs method.
		GetTargetRefs []struct {
		}
		// GetUID holds details about calls to the GetUID method.
		GetUID []struct {
		}
		// SetAnnotations holds details about calls to the SetAnnotations method.
		SetAnnotations []struct {
			// Annotations is the annotations argument value.
			Annotations map[string]string
		}
		// SetCreationTimestamp holds details about calls to the SetCreationTimestamp method.
		SetCreationTimestamp []struct {
			// Timestamp is the timestamp argument value.
			Timestamp v1.Time
		}
		// SetDeletionGracePeriodSeconds holds details about calls to the SetDeletionGracePeriodSeconds method.
		SetDeletionGracePeriodSeconds []struct {
			// N is the n argument value.
			N *int64
		}
		// SetDeletionTimestamp holds details about calls to the SetDeletionTimestamp method.
		SetDeletionTimestamp []struct {
			// Timestamp is the timestamp argument value.
			Timestamp *v1.Time
		}
		// SetFinalizers holds details about calls to the SetFinalizers method.
		SetFinalizers []struct {
			// Finalizers is the finalizers argument value.
			Finalizers []string
		}
		// SetGenerateName holds details about calls to the SetGenerateName method.
		SetGenerateName []struct {
			// Name is the name argument value.
			Name string
		}
		// SetGeneration holds details about calls to the SetGeneration method.
		SetGeneration []struct {
			// Generation is the generation argument value.
			Generation int64
		}
		// SetLabels holds details about calls to the SetLabels method.
		SetLabels []struct {
			// Labels is the labels argument value.
			Labels map[string]string
		}
		// SetManagedFields holds details about calls to the SetManagedFields method.
		SetManagedFields []struct {
			// ManagedFields is the managedFields argument value.
			ManagedFields []v1.ManagedFieldsEntry
		}
		// SetName holds details about calls to the SetName method.
		SetName []struct {
			// Name is the name argument value.
			Name string
		}
		// SetNamespace holds details about calls to the SetNamespace method.
		SetNamespace []struct {
			// Namespace is the namespace argument value.
			Namespace string
		}
		// SetOwnerReferences holds details about calls to the SetOwnerReferences method.
		SetOwnerReferences []struct {
			// OwnerReferences is the ownerReferences argument value.
			OwnerReferences []v1.OwnerReference
		}
		// SetPolicyStatus holds details about calls to the SetPolicyStatus method.
		SetPolicyStatus []struct {
			// Status is the status argument value.
			Status gatewayv1.PolicyStatus
		}
		// SetResourceVersion holds details about calls to the SetResourceVersion method.
		SetResourceVersion []struct {
			// Version is the version argument value.
			Version string
		}
		// SetSelfLink holds details about calls to the SetSelfLink method.
		SetSelfLink []struct {
			// SelfLink is the selfLink argument value.
			SelfLink string
		}
		// SetUID holds details about calls to the SetUID method.
		SetUID []struct {
			// UID is the uid argument value.
			UID types.UID
		}
	}
	lockDeepCopyObject                sync.RWMutex
	lockGetAnnotations                sync.RWMutex
	lockGetCreationTimestamp          sync.RWMutex
	lockGetDeletionGracePeriodSeconds sync.RWMutex
	lockGetDeletionTimestamp          sync.RWMutex
	lockGetFinalizers                 sync.RWMutex
	lockGetGenerateName               sync.RWMutex
	lockGetGeneration                 sync.RWMutex
	lockGetLabels                     sync.RWMutex
	lockGetManagedFields              sync.RWMutex
	lockGetName                       sync.RWMutex
	lockGetNamespace                  sync.RWMutex
	lockGetObjectKind                 sync.RWMutex
	lockGetOwnerReferences            sync.RWMutex
	lockGetPolicyStatus               sync.RWMutex
	lockGetResourceVersion            sync.RWMutex
	lockGetSelfLink                   sync.RWMutex
	lockGetTargetRefs                 sync.RWMutex
	lockGetUID                        sync.RWMutex
	lockSetAnnotations                sync.RWMutex
	lockSetCreationTimestamp          sync.RWMutex
	lockSetDeletionGracePeriodSeconds sync.RWMutex
	lockSetDeletionTimestamp          sync.RWMutex
	lockSetFinalizers                 sync.RWMutex
	lockSetGenerateName               sync.RWMutex
	lockSetGeneration                 sync.RWMutex
	lockSetLabels                     sync.RWMutex
	lockSetManagedFields              sync.RWMutex
	lockSetName                       sync.RWMutex
	lockSetNamespace                  sync.RWMutex
	lockSetOwnerReferences            sync.RWMutex
	lockSetPolicyStatus               sync.RWMutex
	lockSetResourceVersion            sync.RWMutex
	lockSetSelfLink                   sync.RWMutex
	lockSetUID                        sync.RWMutex
}

// DeepCopyObject calls DeepCopyObjectFunc.
func (mock *PolicyMock) DeepCopyObject() runtime.Object {
	if mock.DeepCopyObjectFunc == nil {
		panic("PolicyMock.DeepCopyObjectFunc: method is nil but Policy.DeepCopyObject was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDeepCopyObject.Lock()
	mock.calls.DeepCopyObject = append(mock.calls.DeepCopyObject, callInfo)
	mock.lockDeepCopyObject.Unlock()
	return mock.DeepCopyObjectFunc()
}

// DeepCopyObjectCalls gets all the calls that were made to DeepCopyObject.
// Check the length with:
//
//	len(mockedPolicy.DeepCopyObjectCalls())
func (mock *PolicyMock) DeepCopyObjectCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDeepCopyObject.RLock()
	calls = mock.calls.DeepCopyObject
	mock.lockDeepCopyObject.RUnlock()
	return calls
}

// GetAnnotations calls GetAnnotationsFunc.
func (mock *PolicyMock) GetAnnotations() map[string]string {
	if mock.GetAnnotationsFunc == nil {
		panic("PolicyMock.GetAnnotationsFunc: method is nil but Policy.GetAnnotations was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAnnotations.Lock()
	mock.calls.GetAnnotations = append(mock.calls.GetAnnotations, callInfo)
	mock.lockGetAnnotations.Unlock()
	return mock.GetAnnotationsFunc()
}

// GetAnnotationsCalls gets all the calls that were made to GetAnnotations.
// Check the length with:
//
//	len(mockedPolicy.GetAnnotationsCalls())
func (mock *PolicyMock) GetAnnotationsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAnnotations.RLock()
	calls = mock.calls.GetAnnotations
	mock.lockGetAnnotations.RUnlock()
	return calls
}

// GetCreationTimestamp calls GetCreationTimestampFunc.
func (mock *PolicyMock) GetCreationTimestamp() v1.Time {
	if mock.GetCreationTimestampFunc == nil {
		panic("PolicyMock.GetCreationTimestampFunc: method is nil but Policy.GetCreationTimestamp was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCreationTimestamp.Lock()
	mock.calls.GetCreationTimestamp = append(mock.calls.GetCreationTimestamp, callInfo)
	mock.lockGetCreationTimestamp.Unlock()
	return mock.GetCreationTimestampFunc()
}

// GetCreationTimestampCalls gets all the calls that were made to GetCreationTimestamp.
// Check the length with:
//
//	len(mockedPolicy.GetCreationTimestampCalls())
func (mock *PolicyMock) GetCreationTimestampCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCreationTimestamp.RLock()
	calls = mock.calls.GetCreationTimestamp
	mock.lockGetCreationTimestamp.RUnlock()
	return calls
}

// GetDeletionGracePeriodSeconds calls GetDeletionGracePeriodSecondsFunc.
func (mock *PolicyMock) GetDeletionGracePeriodSeconds() *int64 {
	if mock.GetDeletionGracePeriodSecondsFunc == nil {
		panic("PolicyMock.GetDeletionGracePeriodSecondsFunc: method is nil but Policy.GetDeletionGracePeriodSeconds was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDeletionGracePeriodSeconds.Lock()
	mock.calls.GetDeletionGracePeriodSeconds = append(mock.calls.GetDeletionGracePeriodSeconds, callInfo)
	mock.lockGetDeletionGracePeriodSeconds.Unlock()
	return mock.GetDeletionGracePeriodSecondsFunc()
}

// GetDeletionGracePeriodSecondsCalls gets all the calls that were made to GetDeletionGracePeriodSeconds.
// Check the length with:
//
//	len(mockedPolicy.GetDeletionGracePeriodSecondsCalls())
func (mock *PolicyMock) GetDeletionGracePeriodSecondsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDeletionGracePeriodSeconds.RLock()
	calls = mock.calls.GetDeletionGracePeriodSeconds
	mock.lockGetDeletionGracePeriodSeconds.RUnlock()
	return calls
}

// GetDeletionTimestamp calls GetDeletionTimestampFunc.
func (mock *PolicyMock) GetDeletionTimestamp() *v1.Time {
	if mock.GetDeletionTimestampFunc == nil {
		panic("PolicyMock.GetDeletionTimestampFunc: method is nil but Policy.GetDeletionTimestamp was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDeletionTimestamp.Lock()
	mock.calls.GetDeletionTimestamp = append(mock.calls.GetDeletionTimestamp, callInfo)
	mock.lockGetDeletionTimestamp.Unlock()
	return mock.GetDeletionTimestampFunc()
}

// GetDeletionTimestampCalls gets all the calls that were made to GetDeletionTimestamp.
// Check the length with:
//
//	len(mockedPolicy.GetDeletionTimestampCalls())
func (mock *PolicyMock) GetDeletionTimestampCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDeletionTimestamp.RLock()
	calls = mock.calls.GetDeletionTimestamp
	mock.lockGetDeletionTimestamp.RUnlock()
	return calls
}

// GetFinalizers calls GetFinalizersFunc.
func (mock *PolicyMock) GetFinalizers() []string {
	if mock.GetFinalizersFunc == nil {
		panic("PolicyMock.GetFinalizersFunc: method is nil but Policy.GetFinalizers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetFinalizers.Lock()
	mock.calls.GetFinalizers = append(mock.calls.GetFinalizers, callInfo)
	mock.lockGetFinalizers.Unlock()
	return mock.GetFinalizersFunc()
}

// GetFinalizersCalls gets all the calls that were made to GetFinalizers.
// Check the length with:
//
//	len(mockedPolicy.GetFinalizersCalls())
func (mock *PolicyMock) GetFinalizersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetFinalizers.RLock()
	calls = mock.calls.GetFinalizers
	mock.lockGetFinalizers.RUnlock()
	return calls
}

// GetGenerateName calls GetGenerateNameFunc.
func (mock *PolicyMock) GetGenerateName() string {
	if mock.GetGenerateNameFunc == nil {
		panic("PolicyMock.GetGenerateNameFunc: method is nil but Policy.GetGenerateName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetGenerateName.Lock()
	mock.calls.GetGenerateName = append(mock.calls.GetGenerateName, callInfo)
	mock.lockGetGenerateName.Unlock()
	return mock.GetGenerateNameFunc()
}

// GetGenerateNameCalls gets all the calls that were made to GetGenerateName.
// Check the length with:
//
//	len(mockedPolicy.GetGenerateNameCalls())
func (mock *PolicyMock) GetGenerateNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetGenerateName.RLock()
	calls = mock.calls.GetGenerateName
	mock.lockGetGenerateName.RUnlock()
	return calls
}

// GetGeneration calls GetGenerationFunc.
func (mock *PolicyMock) GetGeneration() int64 {
	if mock.GetGenerationFunc == nil {
		panic("PolicyMock.GetGenerationFunc: method is nil but Policy.GetGeneration was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetGeneration.Lock()
	mock.calls.GetGeneration = append(mock.calls.GetGeneration, callInfo)
	mock.lockGetGeneration.Unlock()
	return mock.GetGenerationFunc()
}

// GetGenerationCalls gets all the calls that were made to GetGeneration.
// Check the length with:
//
//	len(mockedPolicy.GetGenerationCalls())
func (mock *PolicyMock) GetGenerationCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetGeneration.RLock()
	calls = mock.calls.GetGeneration
	mock.lockGetGeneration.RUnlock()
	return calls
}

// GetLabels calls GetLabelsFunc.
func (mock *PolicyMock) GetLabels() map[string]string {
	if mock.GetLabelsFunc == nil {
		panic("PolicyMock.GetLabelsFunc: method is nil but Policy.GetLabels was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLabels.Lock()
	mock.calls.GetLabels = append(mock.calls.GetLabels, callInfo)
	mock.lockGetLabels.Unlock()
	return mock.GetLabelsFunc()
}

// GetLabelsCalls gets all the calls that were made to GetLabels.
// Check the length with:
//
//	len(mockedPolicy.GetLabelsCalls())
func (mock *PolicyMock) GetLabelsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLabels.RLock()
	calls = mock.calls.GetLabels
	mock.lockGetLabels.RUnlock()
	return calls
}

// GetManagedFields calls GetManagedFieldsFunc.
func (mock *PolicyMock) GetManagedFields() []v1.ManagedFieldsEntry {
	if mock.GetManagedFieldsFunc == nil {
		panic("PolicyMock.GetManagedFieldsFunc: method is nil but Policy.GetManagedFields was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetManagedFields.Lock()
	mock.calls.GetManagedFields = append(mock.calls.GetManagedFields, callInfo)
	mock.lockGetManagedFields.Unlock()
	return mock.GetManagedFieldsFunc()
}

// GetManagedFieldsCalls gets all the calls that were made to GetManagedFields.
// Check the length with:
//
//	len(mockedPolicy.GetManagedFieldsCalls())
func (mock *PolicyMock) GetManagedFieldsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetManagedFields.RLock()
	calls = mock.calls.GetManagedFields
	mock.lockGetManagedFields.RUnlock()
	return calls
}

// GetName calls GetNameFunc.
func (mock *PolicyMock) GetName() string {
	if mock.GetNameFunc == nil {
		panic("PolicyMock.GetNameFunc: method is nil but Policy.GetName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetName.Lock()
	mock.calls.GetName = append(mock.calls.GetName, callInfo)
	mock.lockGetName.Unlock()
	return mock.GetNameFunc()
}

// GetNameCalls gets all the calls that were made to GetName.
// Check the length with:
//
//	len(mockedPolicy.GetNameCalls())
func (mock *PolicyMock) GetNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetName.RLock()
	calls = mock.calls.GetName
	mock.lockGetName.RUnlock()
	return calls
}

// GetNamespace calls GetNamespaceFunc.
func (mock *PolicyMock) GetNamespace() string {
	if mock.GetNamespaceFunc == nil {
		panic("PolicyMock.GetNamespaceFunc: method is nil but Policy.GetNamespace was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetNamespace.Lock()
	mock.calls.GetNamespace = append(mock.calls.GetNamespace, callInfo)
	mock.lockGetNamespace.Unlock()
	return mock.GetNamespaceFunc()
}

// GetNamespaceCalls gets all the calls that were made to GetNamespace.
// Check the length with:
//
//	len(mockedPolicy.GetNamespaceCalls())
func (mock *PolicyMock) GetNamespaceCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetNamespace.RLock()
	calls = mock.calls.GetNamespace
	mock.lockGetNamespace.RUnlock()
	return calls
}

// GetObjectKind calls GetObjectKindFunc.
func (mock *PolicyMock) GetObjectKind() schema.ObjectKind {
	if mock.GetObjectKindFunc == nil {
		panic("PolicyMock.GetObjectKindFunc: method is nil but Policy.GetObjectKind was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetObjectKind.Lock()
	mock.calls.GetObjectKind = append(mock.calls.GetObjectKind, callInfo)
	mock.lockGetObjectKind.Unlock()
	return mock.GetObjectKindFunc()
}

// GetObjectKindCalls gets all the calls that were made to GetObjectKind.
// Check the length with:
//
//	len(mockedPolicy.GetObjectKindCalls())
func (mock *PolicyMock) GetObjectKindCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetObjectKind.RLock()
	calls = mock.calls.GetObjectKind
	mock.lockGetObjectKind.RUnlock()
	return calls
}

// GetOwnerReferences calls GetOwnerReferencesFunc.
func (mock *PolicyMock) GetOwnerReferences() []v1.OwnerReference {
	if mock.GetOwnerReferencesFunc == nil {
		panic("PolicyMock.GetOwnerReferencesFunc: method is nil but Policy.GetOwnerReferences was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetOwnerReferences.Lock()
	mock.calls.GetOwnerReferences = append(mock.calls.GetOwnerReferences, callInfo)
	mock.lockGetOwnerReferences.Unlock()
	return mock.GetOwnerReferencesFunc()
}

// GetOwnerReferencesCalls gets all the calls that were made to GetOwnerReferences.
// Check the length with:
//
//	len(mockedPolicy.GetOwnerReferencesCalls())
func (mock *PolicyMock) GetOwnerReferencesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetOwnerReferences.RLock()
	calls = mock.calls.GetOwnerReferences
	mock.lockGetOwnerReferences.RUnlock()
	return calls
}

// GetPolicyStatus calls GetPolicyStatusFunc.
func (mock *PolicyMock) GetPolicyStatus() gatewayv1.PolicyStatus {
	if mock.GetPolicyStatusFunc == nil {
		panic("PolicyMock.GetPolicyStatusFunc: method is nil but Policy.GetPolicyStatus was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPolicyStatus.Lock()
	mock.calls.GetPolicyStatus = append(mock.calls.GetPolicyStatus, callInfo)
	mock.lockGetPolicyStatus.Unlock()
	return mock.GetPolicyStatusFunc()
}

// GetPolicyStatusCalls gets all the calls that were made to GetPolicyStatus.
// Check the length with:
//
//	len(mockedPolicy.GetPolicyStatusCalls())
func (mock *PolicyMock) GetPolicyStatusCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPolicyStatus.RLock()
	calls = mock.calls.GetPolicyStatus
	mock.lockGetPolicyStatus.RUnlock()
	return calls
}

// GetResourceVersion calls GetResourceVersionFunc.
func (mock *PolicyMock) GetResourceVersion() string {
	if mock.GetResourceVersionFunc == nil {
		panic("PolicyMock.GetResourceVersionFunc: method is nil but Policy.GetResourceVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetResourceVersion.Lock()
	mock.calls.GetResourceVersion = append(mock.calls.GetResourceVersion, callInfo)
	mock.lockGetResourceVersion.Unlock()
	return mock.GetResourceVersionFunc()
}

// GetResourceVersionCalls gets all the calls that were made to GetResourceVersion.
// Check the length with:
//
//	len(mockedPolicy.GetResourceVersionCalls())
func (mock *PolicyMock) GetResourceVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetResourceVersion.RLock()
	calls = mock.calls.GetResourceVersion
	mock.lockGetResourceVersion.RUnlock()
	return calls
}

// GetSelfLink calls GetSelfLinkFunc.
func (mock *PolicyMock) GetSelfLink() string {
	if mock.GetSelfLinkFunc == nil {
		panic("PolicyMock.GetSelfLinkFunc: method is nil but Policy.GetSelfLink was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSelfLink.Lock()
	mock.calls.GetSelfLink = append(mock.calls.GetSelfLink, callInfo)
	mock.lockGetSelfLink.Unlock()
	return mock.GetSelfLinkFunc()
}

// GetSelfLinkCalls gets all the calls that were made to GetSelfLink.
// Check the length with:
//
//	len(mockedPolicy.GetSelfLinkCalls())
func (mock *PolicyMock) GetSelfLinkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSelfLink.RLock()
	calls = mock.calls.GetSelfLink
	mock.lockGetSelfLink.RUnlock()
	return calls
}

// GetTargetRefs calls GetTargetRefsFunc.
func (mock *PolicyMock) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	if mock.GetTargetRefsFunc == nil {
		panic("PolicyMock.GetTargetRefsFunc: method is nil but Policy.GetTargetRefs was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTargetRefs.Lock()
	mock.calls.GetTargetRefs = append(mock.calls.GetTargetRefs, callInfo)
	mock.lockGetTargetRefs.Unlock()
	return mock.GetTargetRefsFunc()
}

// GetTargetRefsCalls gets all the calls that were made to GetTargetRefs.
// Check the length with:
//
//	len(mockedPolicy.GetTargetRefsCalls())
func (mock *PolicyMock) GetTargetRefsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTargetRefs.RLock()
	calls = mock.calls.GetTargetRefs
	mock.lockGetTargetRefs.RUnlock()
	return calls
}

// GetUID calls GetUIDFunc.
func (mock *PolicyMock) GetUID() types.UID {
	if mock.GetUIDFunc == nil {
		panic("PolicyMock.GetUIDFunc: method is nil but Policy.GetUID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetUID.Lock()
	mock.calls.GetUID = append(mock.calls.GetUID, callInfo)
	mock.lockGetUID.Unlock()
	return mock.GetUIDFunc()
}

// GetUIDCalls gets all the calls that were made to GetUID.
// Check the length with:
//
//	len(mockedPolicy.GetUIDCalls())
func (mock *PolicyMock) GetUIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetUID.RLock()
	calls = mock.calls.GetUID
	mock.lockGetUID.RUnlock()
	return calls
}

// SetAnnotations calls SetAnnotationsFunc.
func (mock *PolicyMock) SetAnnotations(annotations map[string]string) {
	if mock.SetAnnotationsFunc == nil {
		panic("PolicyMock.SetAnnotationsFunc: method is nil but Policy.SetAnnotations was just called")
	}
	callInfo := struct {
		Annotations map[string]string
	}{
		Annotations: annotations,
	}
	mock.lockSetAnnotations.Lock()
	mock.calls.SetAnnotations = append(mock.calls.SetAnnotations, callInfo)
	mock.lockSetAnnotations.Unlock()
	mock.SetAnnotationsFunc(annotations)
}

// SetAnnotationsCalls gets all the calls that were made to SetAnnotations.
// Check the length with:
//
//	len(mockedPolicy.SetAnnotationsCalls())
func (mock *PolicyMock) SetAnnotationsCalls() []struct {
	Annotations map[string]string
} {
	var calls []struct {
		Annotations map[string]string
	}
	mock.lockSetAnnotations.RLock()
	calls = mock.calls.SetAnnotations
	mock.lockSetAnnotations.RUnlock()
	return calls
}

// SetCreationTimestamp calls SetCreationTimestampFunc.
func (mock *PolicyMock) SetCreationTimestamp(timestamp v1.Time) {
	if mock.SetCreationTimestampFunc == nil {
		panic("PolicyMock.SetCreationTimestampFunc: method is nil but Policy.SetCreationTimestamp was just called")
	}
	callInfo := struct {
		Timestamp v1.Time
	}{
		Timestamp: timestamp,
	}
	mock.lockSetCreationTimestamp.Lock()
	mock.calls.SetCreationTimestamp = append(mock.calls.SetCreationTimestamp, callInfo)
	mock.lockSetCreationTimestamp.Unlock()
	mock.SetCreationTimestampFunc(timestamp)
}

// SetCreationTimestampCalls gets all the calls that were made to SetCreationTimestamp.
// Check the length with:
//
//	len(mockedPolicy.SetCreationTimestampCalls())
func (mock *PolicyMock) SetCreationTimestampCalls() []struct {
	Timestamp v1.Time
} {
	var calls []struct {
		Timestamp v1.Time
	}
	mock.lockSetCreationTimestamp.RLock()
	calls = mock.calls.SetCreationTimestamp
	mock.lockSetCreationTimestamp.RUnlock()
	return calls
}

// SetDeletionGracePeriodSeconds calls SetDeletionGracePeriodSecondsFunc.
func (mock *PolicyMock) SetDeletionGracePeriodSeconds(n *int64) {
	if mock.SetDeletionGracePeriodSecondsFunc == nil {
		panic("PolicyMock.SetDeletionGracePeriodSecondsFunc: method is nil but Policy.SetDeletionGracePeriodSeconds was just called")
	}
	callInfo := struct {
		N *int64
	}{
		N: n,
	}
	mock.lockSetDeletionGracePeriodSeconds.Lock()
	mock.calls.SetDeletionGracePeriodSeconds = append(mock.calls.SetDeletionGracePeriodSeconds, callInfo)
	mock.lockSetDeletionGracePeriodSeconds.Unlock()
	mock.SetDeletionGracePeriodSecondsFunc(n)
}

// SetDeletionGracePeriodSecondsCalls gets all the calls that were made to SetDeletionGracePeriodSeconds.
// Check the length with:
//
//	len(mockedPolicy.SetDeletionGracePeriodSecondsCalls())
func (mock *PolicyMock) SetDeletionGracePeriodSecondsCalls() []struct {
	N *int64
} {
	var calls []struct {
		N *int64
	}
	mock.lockSetDeletionGracePeriodSeconds.RLock()
	calls = mock.calls.SetDeletionGracePeriodSeconds
	mock.lockSetDeletionGracePeriodSeconds.RUnlock()
	return calls
}

// SetDeletionTimestamp calls SetDeletionTimestampFunc.
func (mock *PolicyMock) SetDeletionTimestamp(timestamp *v1.Time) {
	if mock.SetDeletionTimestampFunc == nil {
		panic("PolicyMock.SetDeletionTimestampFunc: method is nil but Policy.SetDeletionTimestamp was just called")
	}
	callInfo := struct {
		Timestamp *v1.Time
	}{
		Timestamp: timestamp,
	}
	mock.lockSetDeletionTimestamp.Lock()
	mock.calls.SetDeletionTimestamp = append(mock.calls.SetDeletionTimestamp, callInfo)
	mock.lockSetDeletionTimestamp.Unlock()
	mock.SetDeletionTimestampFunc(timestamp)
}

// SetDeletionTimestampCalls gets all the calls that were made to SetDeletionTimestamp.
// Check the length with:
//
//	len(mockedPolicy.SetDeletionTimestampCalls())
func (mock *PolicyMock) SetDeletionTimestampCalls() []struct {
	Timestamp *v1.Time
} {
	var calls []struct {
		Timestamp *v1.Time
	}
	mock.lockSetDeletionTimestamp.RLock()
	calls = mock.calls.SetDeletionTimestamp
	mock.lockSetDeletionTimestamp.RUnlock()
	return calls
}

// SetFinalizers calls SetFinalizersFunc.
func (mock *PolicyMock) SetFinalizers(finalizers []string) {
	if mock.SetFinalizersFunc == nil {
		panic("PolicyMock.SetFinalizersFunc: method is nil but Policy.SetFinalizers was just called")
	}
	callInfo := struct {
		Finalizers []string
	}{
		Finalizers: finalizers,
	}
	mock.lockSetFinalizers.Lock()
	mock.calls.SetFinalizers = append(mock.calls.SetFinalizers, callInfo)
	mock.lockSetFinalizers.Unlock()
	mock.SetFinalizersFunc(finalizers)
}

// SetFinalizersCalls gets all the calls that were made to SetFinalizers.
// Check the length with:
//
//	len(mockedPolicy.SetFinalizersCalls())
func (mock *PolicyMock) SetFinalizersCalls() []struct {
	Finalizers []string
} {
	var calls []struct {
		Finalizers []string
	}
	mock.lockSetFinalizers.RLock()
	calls = mock.calls.SetFinalizers
	mock.lockSetFinalizers.RUnlock()
	return calls
}

// SetGenerateName calls SetGenerateNameFunc.
func (mock *PolicyMock) SetGenerateName(name string) {
	if mock.SetGenerateNameFunc == nil {
		panic("PolicyMock.SetGenerateNameFunc: method is nil but Policy.SetGenerateName was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockSetGenerateName.Lock()
	mock.calls.SetGenerateName = append(mock.calls.SetGenerateName, callInfo)
	mock.lockSetGenerateName.Unlock()
	mock.SetGenerateNameFunc(name)
}

// SetGenerateNameCalls gets all the calls that were made to SetGenerateName.
// Check the length with:
//
//	len(mockedPolicy.SetGenerateNameCalls())
func (mock *PolicyMock) SetGenerateNameCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockSetGenerateName.RLock()
	calls = mock.calls.SetGenerateName
	mock.lockSetGenerateName.RUnlock()
	return calls
}

// SetGeneration calls SetGenerationFunc.
func (mock *PolicyMock) SetGeneration(generation int64) {
	if mock.SetGenerationFunc == nil {
		panic("PolicyMock.SetGenerationFunc: method is nil but Policy.SetGeneration was just called")
	}
	callInfo := struct {
		Generation int64
	}{
		Generation: generation,
	}
	mock.lockSetGeneration.Lock()
	mock.calls.SetGeneration = append(mock.calls.SetGeneration, callInfo)
	mock.lockSetGeneration.Unlock()
	mock.SetGenerationFunc(generation)
}

// SetGenerationCalls gets all the calls that were made to SetGeneration.
// Check the length with:
//
//	len(mockedPolicy.SetGenerationCalls())
func (mock *PolicyMock) SetGenerationCalls() []struct {
	Generation int64
} {
	var calls []struct {
		Generation int64
	}
	mock.lockSetGeneration.RLock()
	calls = mock.calls.SetGeneration
	mock.lockSetGeneration.RUnlock()
	return calls
}

// SetLabels calls SetLabelsFunc.
func (mock *PolicyMock) SetLabels(labels map[string]string) {
	if mock.SetLabelsFunc == nil {
		panic("PolicyMock.SetLabelsFunc: method is nil but Policy.SetLabels was just called")
	}
	callInfo := struct {
		Labels map[string]string
	}{
		Labels: labels,
	}
	mock.lockSetLabels.Lock()
	mock.calls.SetLabels = append(mock.calls.SetLabels, callInfo)
	mock.lockSetLabels.Unlock()
	mock.SetLabelsFunc(labels)
}

// SetLabelsCalls gets all the calls that were made to SetLabels.
// Check the length with:
//
//	len(mockedPolicy.SetLabelsCalls())
func (mock *PolicyMock) SetLabelsCalls() []struct {
	Labels map[string]string
} {
	var calls []struct {
		Labels map[string]string
	}
	mock.lockSetLabels.RLock()
	calls = mock.calls.SetLabels
	mock.lockSetLabels.RUnlock()
	return calls
}

// SetManagedFields calls SetManagedFieldsFunc.
func (mock *PolicyMock) SetManagedFields(managedFields []v1.ManagedFieldsEntry) {
	if mock.SetManagedFieldsFunc == nil {
		panic("PolicyMock.SetManagedFieldsFunc: method is nil but Policy.SetManagedFields was just called")
	}
	callInfo := struct {
		ManagedFields []v1.ManagedFieldsEntry
	}{
		ManagedFields: managedFields,
	}
	mock.lockSetManagedFields.Lock()
	mock.calls.SetManagedFields = append(mock.calls.SetManagedFields, callInfo)
	mock.lockSetManagedFields.Unlock()
	mock.SetManagedFieldsFunc(managedFields)
}

// SetManagedFieldsCalls gets all the calls that were made to SetManagedFields.
// Check the length with:
//
//	len(mockedPolicy.SetManagedFieldsCalls())
func (mock *PolicyMock) SetManagedFieldsCalls() []struct {
	ManagedFields []v1.ManagedFieldsEntry
} {
	var calls []struct {
		ManagedFields []v1.ManagedFieldsEntry
	}
	mock.lockSetManagedFields.RLock()
	calls = mock.calls.SetManagedFields
	mock.lockSetManagedFields.RUnlock()
	return calls
}

// SetName calls SetNameFunc.
func (mock *PolicyMock) SetName(name string) {
	if mock.SetNameFunc == nil {
		panic("PolicyMock.SetNameFunc: method is nil but Policy.SetName was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockSetName.Lock()
	mock.calls.SetName = append(mock.calls.SetName, callInfo)
	mock.lockSetName.Unlock()
	mock.SetNameFunc(name)
}

// SetNameCalls gets all the calls that were made to SetName.
// Check the length with:
//
//	len(mockedPolicy.SetNameCalls())
func (mock *PolicyMock) SetNameCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockSetName.RLock()
	calls = mock.calls.SetName
	mock.lockSetName.RUnlock()
	return calls
}

// SetNamespace calls SetNamespaceFunc.
func (mock *PolicyMock) SetNamespace(namespace string) {
	if mock.SetNamespaceFunc == nil {
		panic("PolicyMock.SetNamespaceFunc: method is nil but Policy.SetNamespace was just called")
	}
	callInfo := struct {
		Namespace string
	}{
		Namespace: namespace,
	}
	mock.lockSetNamespace.Lock()
	mock.calls.SetNamespace = append(mock.calls.SetNamespace, callInfo)
	mock.lockSetNamespace.Unlock()
	mock.SetNamespaceFunc(namespace)
}

// SetNamespaceCalls gets all the calls that were made to SetNamespace.
// Check the length with:
//
//	len(mockedPolicy.SetNamespaceCalls())
func (mock *PolicyMock) SetNamespaceCalls() []struct {
	Namespace string
} {
	var calls []struct {
		Namespace string
	}
	mock.lockSetNamespace.RLock()
	calls = mock.calls.SetNamespace
	mock.lockSetNamespace.RUnlock()
	return calls
}

// SetOwnerReferences calls SetOwnerReferencesFunc.
func (mock *PolicyMock) SetOwnerReferences(ownerReferences []v1.OwnerReference) {
	if mock.SetOwnerReferencesFunc == nil {
		panic("PolicyMock.SetOwnerReferencesFunc: method is nil but Policy.SetOwnerReferences was just called")
	}
	callInfo := struct {
		OwnerReferences []v1.OwnerReference
	}{
		OwnerReferences: ownerReferences,
	}
	mock.lockSetOwnerReferences.Lock()
	mock.calls.SetOwnerReferences = append(mock.calls.SetOwnerReferences, callInfo)
	mock.lockSetOwnerReferences.Unlock()
	mock.SetOwnerReferencesFunc(ownerReferences)
}

// SetOwnerReferencesCalls gets all the calls that were made to SetOwnerReferences.
// Check the length with:
//
//	len(mockedPolicy.SetOwnerReferencesCalls())
func (mock *PolicyMock) SetOwnerReferencesCalls() []struct {
	OwnerReferences []v1.OwnerReference
} {
	var calls []struct {
		OwnerReferences []v1.OwnerReference
	}
	mock.lockSetOwnerReferences.RLock()
	calls = mock.calls.SetOwnerReferences
	mock.lockSetOwnerReferences.RUnlock()
	return calls
}

// SetPolicyStatus calls SetPolicyStatusFunc.
func (mock *PolicyMock) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	if mock.SetPolicyStatusFunc == nil {
		panic("PolicyMock.SetPolicyStatusFunc: method is nil but Policy.SetPolicyStatus was just called")
	}
	callInfo := struct {
		Status gatewayv1.PolicyStatus
	}{
		Status: status,
	}
	mock.lockSetPolicyStatus.Lock()
	mock.calls.SetPolicyStatus = append(mock.calls.SetPolicyStatus, callInfo)
	mock.lockSetPolicyStatus.Unlock()
	mock.SetPolicyStatusFunc(status)
}

// SetPolicyStatusCalls gets all the calls that were made to SetPolicyStatus.
// Check the length with:
//
//	len(mockedPolicy.SetPolicyStatusCalls())
func (mock *PolicyMock) SetPolicyStatusCalls() []struct {
	Status gatewayv1.PolicyStatus
} {
	var calls []struct {
		Status gatewayv1.PolicyStatus
	}
	mock.lockSetPolicyStatus.RLock()
	calls = mock.calls.SetPolicyStatus
	mock.lockSetPolicyStatus.RUnlock()
	return calls
}

// SetResourceVersion calls SetResourceVersionFunc.
func (mock *PolicyMock) SetResourceVersion(version string) {
	if mock.SetResourceVersionFunc == nil {
		panic("PolicyMock.SetResourceVersionFunc: method is nil but Policy.SetResourceVersion was just called")
	}
	callInfo := struct {
		Version string
	}{
		Version: version,
	}
	mock.lockSetResourceVersion.Lock()
	mock.calls.SetResourceVersion = append(mock.calls.SetResourceVersion, callInfo)
	mock.lockSetResourceVersion.Unlock()
	mock.SetResourceVersionFunc(version)
}

// SetResourceVersionCalls gets all the calls that were made to SetResourceVersion.
// Check the length with:
//
//	len(mockedPolicy.SetResourceVersionCalls())
func (mock *PolicyMock) SetResourceVersionCalls() []struct {
	Version string
} {
	var calls []struct {
		Version string
	}
	mock.lockSetResourceVersion.RLock()
	calls = mock.calls.SetResourceVersion
	mock.lockSetResourceVersion.RUnlock()
	return calls
}

// SetSelfLink calls SetSelfLinkFunc.
func (mock *PolicyMock) SetSelfLink(selfLink string) {
	if mock.SetSelfLinkFunc == nil {
		panic("PolicyMock.SetSelfLinkFunc: method is nil but Policy.SetSelfLink was just called")
	}
	callInfo := struct {
		SelfLink string
	}{
		SelfLink: selfLink,
	}
	mock.lockSetSelfLink.Lock()
	mock.calls.SetSelfLink = append(mock.calls.SetSelfLink, callInfo)
	mock.lockSetSelfLink.Unlock()
	mock.SetSelfLinkFunc(selfLink)
}

// SetSelfLinkCalls gets all the calls that were made to SetSelfLink.
// Check the length with:
//
//	len(mockedPolicy.SetSelfLinkCalls())
func (mock *PolicyMock) SetSelfLinkCalls() []struct {
	SelfLink string
} {
	var calls []struct {
		SelfLink string
	}
	mock.lockSetSelfLink.RLock()
	calls = mock.calls.SetSelfLink
	mock.lockSetSelfLink.RUnlock()
	return calls
}

// SetUID calls SetUIDFunc.
func (mock *PolicyMock) SetUID(uid types.UID) {
	if mock.SetUIDFunc == nil {
		panic("PolicyMock.SetUIDFunc: method is nil but Policy.SetUID was just called")
	}
	callInfo := struct {
		UID types.UID
	}{
		UID: uid,
	}
	mock.lockSetUID.Lock()
	mock.calls.SetUID = append(mock.calls.SetUID, callInfo)
	mock.lockSetUID.Unlock()
	mock.SetUIDFunc(uid)
}

// SetUIDCalls gets all the calls that were made to SetUID.
// Check the length with:
//
//	len(mockedPolicy.SetUIDCalls())
func (mock *PolicyMock) SetUIDCalls() []struct {
	UID types.UID
} {
	var calls []struct {
		UID types.UID
	}
	mock.lockSetUID.RLock()
	calls = mock.calls.SetUID
	mock.lockSetUID.RUnlock()
	return calls
}
