// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package validationfakes

import (
	"sync"
)

// HTTPFieldsValidatorMock is a mock implementation of validation.HTTPFieldsValidator.
//
//	func TestSomethingThatUsesHTTPFieldsValidator(t *testing.T) {
//
//		// make and configure a mocked validation.HTTPFieldsValidator
//		mockedHTTPFieldsValidator := &HTTPFieldsValidatorMock{
//			SkipValidationFunc: func() bool {
//				panic("mock out the SkipValidation method")
//			},
//			ValidateDurationFunc: func(duration string) (string, error) {
//				panic("mock out the ValidateDuration method")
//			},
//			ValidateFilterHeaderNameFunc: func(name string) error {
//				panic("mock out the ValidateFilterHeaderName method")
//			},
//			ValidateFilterHeaderValueFunc: func(value string) error {
//				panic("mock out the ValidateFilterHeaderValue method")
//			},
//			ValidateHeaderNameInMatchFunc: func(name string) error {
//				panic("mock out the ValidateHeaderNameInMatch method")
//			},
//			ValidateHeaderValueInMatchFunc: func(value string) error {
//				panic("mock out the ValidateHeaderValueInMatch method")
//			},
//			ValidateHostnameFunc: func(hostname string) error {
//				panic("mock out the ValidateHostname method")
//			},
//			ValidateMethodInMatchFunc: func(method string) (bool, []string) {
//				panic("mock out the ValidateMethodInMatch method")
//			},
//			ValidatePathFunc: func(path string) error {
//				panic("mock out the ValidatePath method")
//			},
//			ValidatePathInMatchFunc: func(path string) error {
//				panic("mock out the ValidatePathInMatch method")
//			},
//			ValidatePathInRegexMatchFunc: func(path string) error {
//				panic("mock out the ValidatePathInRegexMatch method")
//			},
//			ValidateQueryParamNameInMatchFunc: func(name string) error {
//				panic("mock out the ValidateQueryParamNameInMatch method")
//			},
//			ValidateQueryParamValueInMatchFunc: func(name string) error {
//				panic("mock out the ValidateQueryParamValueInMatch method")
//			},
//			ValidateRedirectPortFunc: func(port int32) error {
//				panic("mock out the ValidateRedirectPort method")
//			},
//			ValidateRedirectSchemeFunc: func(scheme string) (bool, []string) {
//				panic("mock out the ValidateRedirectScheme method")
//			},
//		}
//
//		// use mockedHTTPFieldsValidator in code that requires validation.HTTPFieldsValidator
//		// and then make assertions.
//
//	}
type HTTPFieldsValidatorMock struct {
	// SkipValidationFunc mocks the SkipValidation method.
	SkipValidationFunc func() bool

	// ValidateDurationFunc mocks the ValidateDuration method.
	ValidateDurationFunc func(duration string) (string, error)

	// ValidateFilterHeaderNameFunc mocks the ValidateFilterHeaderName method.
	ValidateFilterHeaderNameFunc func(name string) error

	// ValidateFilterHeaderValueFunc mocks the ValidateFilterHeaderValue method.
	ValidateFilterHeaderValueFunc func(value string) error

	// ValidateHeaderNameInMatchFunc mocks the ValidateHeaderNameInMatch method.
	ValidateHeaderNameInMatchFunc func(name string) error

	// ValidateHeaderValueInMatchFunc mocks the ValidateHeaderValueInMatch method.
	ValidateHeaderValueInMatchFunc func(value string) error

	// ValidateHostnameFunc mocks the ValidateHostname method.
	ValidateHostnameFunc func(hostname string) error

	// ValidateMethodInMatchFunc mocks the ValidateMethodInMatch method.
	ValidateMethodInMatchFunc func(method string) (bool, []string)

	// ValidatePathFunc mocks the ValidatePath method.
	ValidatePathFunc func(path string) error

	// ValidatePathInMatchFunc mocks the ValidatePathInMatch method.
	ValidatePathInMatchFunc func(path string) error

	// ValidatePathInRegexMatchFunc mocks the ValidatePathInRegexMatch method.
	ValidatePathInRegexMatchFunc func(path string) error

	// ValidateQueryParamNameInMatchFunc mocks the ValidateQueryParamNameInMatch method.
	ValidateQueryParamNameInMatchFunc func(name string) error

	// ValidateQueryParamValueInMatchFunc mocks the ValidateQueryParamValueInMatch method.
	ValidateQueryParamValueInMatchFunc func(name string) error

	// ValidateRedirectPortFunc mocks the ValidateRedirectPort method.
	ValidateRedirectPortFunc func(port int32) error

	// ValidateRedirectSchemeFunc mocks the ValidateRedirectScheme method.
	ValidateRedirectSchemeFunc func(scheme string) (bool, []string)

	// calls tracks calls to the methods.
	calls struct {
		// SkipValidation holds details about calls to the SkipValidation method.
		SkipValidation []struct {
		}
		// ValidateDuration holds details about calls to the ValidateDuration method.
		ValidateDuration []struct {
			// Duration is the duration argument value.
			Duration string
		}
		// ValidateFilterHeaderName holds details about calls to the ValidateFilterHeaderName method.
		ValidateFilterHeaderName []struct {
			// Name is the name argument value.
			Name string
		}
		// ValidateFilterHeaderValue holds details about calls to the ValidateFilterHeaderValue method.
		ValidateFilterHeaderValue []struct {
			// Value is the value argument value.
			Value string
		}
		// ValidateHeaderNameInMatch holds details about calls to the ValidateHeaderNameInMatch method.
		ValidateHeaderNameInMatch []struct {
			// Name is the name argument value.
			Name string
		}
		// ValidateHeaderValueInMatch holds details about calls to the ValidateHeaderValueInMatch method.
		ValidateHeaderValueInMatch []struct {
			// Value is the value argument value.
			Value string
		}
		// ValidateHostname holds details about calls to the ValidateHostname method.
		ValidateHostname []struct {
			// Hostname is the hostname argument value.
			Hostname string
		}
		// ValidateMethodInMatch holds details about calls to the ValidateMethodInMatch method.
		ValidateMethodInMatch []struct {
			// Method is the method argument value.
			Method string
		}
		// ValidatePath holds details about calls to the ValidatePath method.
		ValidatePath []struct {
			// Path is the path argument value.
			Path string
		}
		// ValidatePathInMatch holds details about calls to the ValidatePathInMatch method.
		ValidatePathInMatch []struct {
			// Path is the path argument value.
			Path string
		}
		// ValidatePathInRegexMatch holds details about calls to the ValidatePathInRegexMatch method.
		ValidatePathInRegexMatch []struct {
			// Path is the path argument value.
			Path string
		}
		// ValidateQueryParamNameInMatch holds details about calls to the ValidateQueryParamNameInMatch method.
		ValidateQueryParamNameInMatch []struct {
			// Name is the name argument value.
			Name string
		}
		// ValidateQueryParamValueInMatch holds details about calls to the ValidateQueryParamValueInMatch method.
		ValidateQueryParamValueInMatch []struct {
			// Name is the name argument value.
			Name string
		}
		// ValidateRedirectPort holds details about calls to the ValidateRedirectPort method.
		ValidateRedirectPort []struct {
			// Port is the port argument value.
			Port int32
		}
		// ValidateRedirectScheme holds details about calls to the ValidateRedirectScheme method.
		ValidateRedirectScheme []struct {
			// Scheme is the scheme argument value.
			Scheme string
		}
	}
	lockSkipValidation                 sync.RWMutex
	lockValidateDuration               sync.RWMutex
	lockValidateFilterHeaderName       sync.RWMutex
	lockValidateFilterHeaderValue      sync.RWMutex
	lockValidateHeaderNameInMatch      sync.RWMutex
	lockValidateHeaderValueInMatch     sync.RWMutex
	lockValidateHostname               sync.RWMutex
	lockValidateMethodInMatch          sync.RWMutex
	lockValidatePath                   sync.RWMutex
	lockValidatePathInMatch            sync.RWMutex
	lockValidatePathInRegexMatch       sync.RWMutex
	lockValidateQueryParamNameInMatch  sync.RWMutex
	lockValidateQueryParamValueInMatch sync.RWMutex
	lockValidateRedirectPort           sync.RWMutex
	lockValidateRedirectScheme         sync.RWMutex
}

// SkipValidation calls SkipValidationFunc.
func (mock *HTTPFieldsValidatorMock) SkipValidation() bool {
	if mock.SkipValidationFunc == nil {
		panic("HTTPFieldsValidatorMock.SkipValidationFunc: method is nil but HTTPFieldsValidator.SkipValidation was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSkipValidation.Lock()
	mock.calls.SkipValidation = append(mock.calls.SkipValidation, callInfo)
	mock.lockSkipValidation.Unlock()
	return mock.SkipValidationFunc()
}

// SkipValidationCalls gets all the calls that were made to SkipValidation.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.SkipValidationCalls())
func (mock *HTTPFieldsValidatorMock) SkipValidationCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSkipValidation.RLock()
	calls = mock.calls.SkipValidation
	mock.lockSkipValidation.RUnlock()
	return calls
}

// ValidateDuration calls ValidateDurationFunc.
func (mock *HTTPFieldsValidatorMock) ValidateDuration(duration string) (string, error) {
	if mock.ValidateDurationFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateDurationFunc: method is nil but HTTPFieldsValidator.ValidateDuration was just called")
	}
	callInfo := struct {
		Duration string
	}{
		Duration: duration,
	}
	mock.lockValidateDuration.Lock()
	mock.calls.ValidateDuration = append(mock.calls.ValidateDuration, callInfo)
	mock.lockValidateDuration.Unlock()
	return mock.ValidateDurationFunc(duration)
}

// ValidateDurationCalls gets all the calls that were made to ValidateDuration.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateDurationCalls())
func (mock *HTTPFieldsValidatorMock) ValidateDurationCalls() []struct {
	Duration string
} {
	var calls []struct {
		Duration string
	}
	mock.lockValidateDuration.RLock()
	calls = mock.calls.ValidateDuration
	mock.lockValidateDuration.RUnlock()
	return calls
}

// ValidateFilterHeaderName calls ValidateFilterHeaderNameFunc.
func (mock *HTTPFieldsValidatorMock) ValidateFilterHeaderName(name string) error {
	if mock.ValidateFilterHeaderNameFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateFilterHeaderNameFunc: method is nil but HTTPFieldsValidator.ValidateFilterHeaderName was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockValidateFilterHeaderName.Lock()
	mock.calls.ValidateFilterHeaderName = append(mock.calls.ValidateFilterHeaderName, callInfo)
	mock.lockValidateFilterHeaderName.Unlock()
	return mock.ValidateFilterHeaderNameFunc(name)
}

// ValidateFilterHeaderNameCalls gets all the calls that were made to ValidateFilterHeaderName.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateFilterHeaderNameCalls())
func (mock *HTTPFieldsValidatorMock) ValidateFilterHeaderNameCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockValidateFilterHeaderName.RLock()
	calls = mock.calls.ValidateFilterHeaderName
	mock.lockValidateFilterHeaderName.RUnlock()
	return calls
}

// ValidateFilterHeaderValue calls ValidateFilterHeaderValueFunc.
func (mock *HTTPFieldsValidatorMock) ValidateFilterHeaderValue(value string) error {
	if mock.ValidateFilterHeaderValueFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateFilterHeaderValueFunc: method is nil but HTTPFieldsValidator.ValidateFilterHeaderValue was just called")
	}
	callInfo := struct {
		Value string
	}{
		Value: value,
	}
	mock.lockValidateFilterHeaderValue.Lock()
	mock.calls.ValidateFilterHeaderValue = append(mock.calls.ValidateFilterHeaderValue, callInfo)
	mock.lockValidateFilterHeaderValue.Unlock()
	return mock.ValidateFilterHeaderValueFunc(value)
}

// ValidateFilterHeaderValueCalls gets all the calls that were made to ValidateFilterHeaderValue.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateFilterHeaderValueCalls())
func (mock *HTTPFieldsValidatorMock) ValidateFilterHeaderValueCalls() []struct {
	Value string
} {
	var calls []struct {
		Value string
	}
	mock.lockValidateFilterHeaderValue.RLock()
	calls = mock.calls.ValidateFilterHeaderValue
	mock.lockValidateFilterHeaderValue.RUnlock()
	return calls
}

// ValidateHeaderNameInMatch calls ValidateHeaderNameInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidateHeaderNameInMatch(name string) error {
	if mock.ValidateHeaderNameInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateHeaderNameInMatchFunc: method is nil but HTTPFieldsValidator.ValidateHeaderNameInMatch was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockValidateHeaderNameInMatch.Lock()
	mock.calls.ValidateHeaderNameInMatch = append(mock.calls.ValidateHeaderNameInMatch, callInfo)
	mock.lockValidateHeaderNameInMatch.Unlock()
	return mock.ValidateHeaderNameInMatchFunc(name)
}

// ValidateHeaderNameInMatchCalls gets all the calls that were made to ValidateHeaderNameInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateHeaderNameInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidateHeaderNameInMatchCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockValidateHeaderNameInMatch.RLock()
	calls = mock.calls.ValidateHeaderNameInMatch
	mock.lockValidateHeaderNameInMatch.RUnlock()
	return calls
}

// ValidateHeaderValueInMatch calls ValidateHeaderValueInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidateHeaderValueInMatch(value string) error {
	if mock.ValidateHeaderValueInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateHeaderValueInMatchFunc: method is nil but HTTPFieldsValidator.ValidateHeaderValueInMatch was just called")
	}
	callInfo := struct {
		Value string
	}{
		Value: value,
	}
	mock.lockValidateHeaderValueInMatch.Lock()
	mock.calls.ValidateHeaderValueInMatch = append(mock.calls.ValidateHeaderValueInMatch, callInfo)
	mock.lockValidateHeaderValueInMatch.Unlock()
	return mock.ValidateHeaderValueInMatchFunc(value)
}

// ValidateHeaderValueInMatchCalls gets all the calls that were made to ValidateHeaderValueInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateHeaderValueInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidateHeaderValueInMatchCalls() []struct {
	Value string
} {
	var calls []struct {
		Value string
	}
	mock.lockValidateHeaderValueInMatch.RLock()
	calls = mock.calls.ValidateHeaderValueInMatch
	mock.lockValidateHeaderValueInMatch.RUnlock()
	return calls
}

// ValidateHostname calls ValidateHostnameFunc.
func (mock *HTTPFieldsValidatorMock) ValidateHostname(hostname string) error {
	if mock.ValidateHostnameFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateHostnameFunc: method is nil but HTTPFieldsValidator.ValidateHostname was just called")
	}
	callInfo := struct {
		Hostname string
	}{
		Hostname: hostname,
	}
	mock.lockValidateHostname.Lock()
	mock.calls.ValidateHostname = append(mock.calls.ValidateHostname, callInfo)
	mock.lockValidateHostname.Unlock()
	return mock.ValidateHostnameFunc(hostname)
}

// ValidateHostnameCalls gets all the calls that were made to ValidateHostname.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateHostnameCalls())
func (mock *HTTPFieldsValidatorMock) ValidateHostnameCalls() []struct {
	Hostname string
} {
	var calls []struct {
		Hostname string
	}
	mock.lockValidateHostname.RLock()
	calls = mock.calls.ValidateHostname
	mock.lockValidateHostname.RUnlock()
	return calls
}

// ValidateMethodInMatch calls ValidateMethodInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidateMethodInMatch(method string) (bool, []string) {
	if mock.ValidateMethodInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateMethodInMatchFunc: method is nil but HTTPFieldsValidator.ValidateMethodInMatch was just called")
	}
	callInfo := struct {
		Method string
	}{
		Method: method,
	}
	mock.lockValidateMethodInMatch.Lock()
	mock.calls.ValidateMethodInMatch = append(mock.calls.ValidateMethodInMatch, callInfo)
	mock.lockValidateMethodInMatch.Unlock()
	return mock.ValidateMethodInMatchFunc(method)
}

// ValidateMethodInMatchCalls gets all the calls that were made to ValidateMethodInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateMethodInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidateMethodInMatchCalls() []struct {
	Method string
} {
	var calls []struct {
		Method string
	}
	mock.lockValidateMethodInMatch.RLock()
	calls = mock.calls.ValidateMethodInMatch
	mock.lockValidateMethodInMatch.RUnlock()
	return calls
}

// ValidatePath calls ValidatePathFunc.
func (mock *HTTPFieldsValidatorMock) ValidatePath(path string) error {
	if mock.ValidatePathFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidatePathFunc: method is nil but HTTPFieldsValidator.ValidatePath was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockValidatePath.Lock()
	mock.calls.ValidatePath = append(mock.calls.ValidatePath, callInfo)
	mock.lockValidatePath.Unlock()
	return mock.ValidatePathFunc(path)
}

// ValidatePathCalls gets all the calls that were made to ValidatePath.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidatePathCalls())
func (mock *HTTPFieldsValidatorMock) ValidatePathCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockValidatePath.RLock()
	calls = mock.calls.ValidatePath
	mock.lockValidatePath.RUnlock()
	return calls
}

// ValidatePathInMatch calls ValidatePathInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidatePathInMatch(path string) error {
	if mock.ValidatePathInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidatePathInMatchFunc: method is nil but HTTPFieldsValidator.ValidatePathInMatch was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockValidatePathInMatch.Lock()
	mock.calls.ValidatePathInMatch = append(mock.calls.ValidatePathInMatch, callInfo)
	mock.lockValidatePathInMatch.Unlock()
	return mock.ValidatePathInMatchFunc(path)
}

// ValidatePathInMatchCalls gets all the calls that were made to ValidatePathInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidatePathInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidatePathInMatchCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockValidatePathInMatch.RLock()
	calls = mock.calls.ValidatePathInMatch
	mock.lockValidatePathInMatch.RUnlock()
	return calls
}

// ValidatePathInRegexMatch calls ValidatePathInRegexMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidatePathInRegexMatch(path string) error {
	if mock.ValidatePathInRegexMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidatePathInRegexMatchFunc: method is nil but HTTPFieldsValidator.ValidatePathInRegexMatch was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockValidatePathInRegexMatch.Lock()
	mock.calls.ValidatePathInRegexMatch = append(mock.calls.ValidatePathInRegexMatch, callInfo)
	mock.lockValidatePathInRegexMatch.Unlock()
	return mock.ValidatePathInRegexMatchFunc(path)
}

// ValidatePathInRegexMatchCalls gets all the calls that were made to ValidatePathInRegexMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidatePathInRegexMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidatePathInRegexMatchCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockValidatePathInRegexMatch.RLock()
	calls = mock.calls.ValidatePathInRegexMatch
	mock.lockValidatePathInRegexMatch.RUnlock()
	return calls
}

// ValidateQueryParamNameInMatch calls ValidateQueryParamNameInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidateQueryParamNameInMatch(name string) error {
	if mock.ValidateQueryParamNameInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateQueryParamNameInMatchFunc: method is nil but HTTPFieldsValidator.ValidateQueryParamNameInMatch was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockValidateQueryParamNameInMatch.Lock()
	mock.calls.ValidateQueryParamNameInMatch = append(mock.calls.ValidateQueryParamNameInMatch, callInfo)
	mock.lockValidateQueryParamNameInMatch.Unlock()
	return mock.ValidateQueryParamNameInMatchFunc(name)
}

// ValidateQueryParamNameInMatchCalls gets all the calls that were made to ValidateQueryParamNameInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateQueryParamNameInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidateQueryParamNameInMatchCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockValidateQueryParamNameInMatch.RLock()
	calls = mock.calls.ValidateQueryParamNameInMatch
	mock.lockValidateQueryParamNameInMatch.RUnlock()
	return calls
}

// ValidateQueryParamValueInMatch calls ValidateQueryParamValueInMatchFunc.
func (mock *HTTPFieldsValidatorMock) ValidateQueryParamValueInMatch(name string) error {
	if mock.ValidateQueryParamValueInMatchFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateQueryParamValueInMatchFunc: method is nil but HTTPFieldsValidator.ValidateQueryParamValueInMatch was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockValidateQueryParamValueInMatch.Lock()
	mock.calls.ValidateQueryParamValueInMatch = append(mock.calls.ValidateQueryParamValueInMatch, callInfo)
	mock.lockValidateQueryParamValueInMatch.Unlock()
	return mock.ValidateQueryParamValueInMatchFunc(name)
}

// ValidateQueryParamValueInMatchCalls gets all the calls that were made to ValidateQueryParamValueInMatch.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateQueryParamValueInMatchCalls())
func (mock *HTTPFieldsValidatorMock) ValidateQueryParamValueInMatchCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockValidateQueryParamValueInMatch.RLock()
	calls = mock.calls.ValidateQueryParamValueInMatch
	mock.lockValidateQueryParamValueInMatch.RUnlock()
	return calls
}

// ValidateRedirectPort calls ValidateRedirectPortFunc.
func (mock *HTTPFieldsValidatorMock) ValidateRedirectPort(port int32) error {
	if mock.ValidateRedirectPortFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateRedirectPortFunc: method is nil but HTTPFieldsValidator.ValidateRedirectPort was just called")
	}
	callInfo := struct {
		Port int32
	}{
		Port: port,
	}
	mock.lockValidateRedirectPort.Lock()
	mock.calls.ValidateRedirectPort = append(mock.calls.ValidateRedirectPort, callInfo)
	mock.lockValidateRedirectPort.Unlock()
	return mock.ValidateRedirectPortFunc(port)
}

// ValidateRedirectPortCalls gets all the calls that were made to ValidateRedirectPort.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateRedirectPortCalls())
func (mock *HTTPFieldsValidatorMock) ValidateRedirectPortCalls() []struct {
	Port int32
} {
	var calls []struct {
		Port int32
	}
	mock.lockValidateRedirectPort.RLock()
	calls = mock.calls.ValidateRedirectPort
	mock.lockValidateRedirectPort.RUnlock()
	return calls
}

// ValidateRedirectScheme calls ValidateRedirectSchemeFunc.
func (mock *HTTPFieldsValidatorMock) ValidateRedirectScheme(scheme string) (bool, []string) {
	if mock.ValidateRedirectSchemeFunc == nil {
		panic("HTTPFieldsValidatorMock.ValidateRedirectSchemeFunc: method is nil but HTTPFieldsValidator.ValidateRedirectScheme was just called")
	}
	callInfo := struct {
		Scheme string
	}{
		Scheme: scheme,
	}
	mock.lockValidateRedirectScheme.Lock()
	mock.calls.ValidateRedirectScheme = append(mock.calls.ValidateRedirectScheme, callInfo)
	mock.lockValidateRedirectScheme.Unlock()
	return mock.ValidateRedirectSchemeFunc(scheme)
}

// ValidateRedirectSchemeCalls gets all the calls that were made to ValidateRedirectScheme.
// Check the length with:
//
//	len(mockedHTTPFieldsValidator.ValidateRedirectSchemeCalls())
func (mock *HTTPFieldsValidatorMock) ValidateRedirectSchemeCalls() []struct {
	Scheme string
} {
	var calls []struct {
		Scheme string
	}
	mock.lockValidateRedirectScheme.RLock()
	calls = mock.calls.ValidateRedirectScheme
	mock.lockValidateRedirectScheme.RUnlock()
	return calls
}
