// Code generated by counterfeiter. DO NOT EDIT.
package validationfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/validation"
)

type FakeAuthFieldsValidator struct {
	ValidateOIDCIssuerStub        func(string) error
	validateOIDCIssuerMutex       sync.RWMutex
	validateOIDCIssuerArgsForCall []struct {
		arg1 string
	}
	validateOIDCIssuerReturns struct {
		result1 error
	}
	validateOIDCIssuerReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCRedirectURIStub        func(string) error
	validateOIDCRedirectURIMutex       sync.RWMutex
	validateOIDCRedirectURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCRedirectURIReturns struct {
		result1 error
	}
	validateOIDCRedirectURIReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCLogoutURIStub        func(string) error
	validateOIDCLogoutURIMutex       sync.RWMutex
	validateOIDCLogoutURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCLogoutURIReturns struct {
		result1 error
	}
	validateOIDCLogoutURIReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuer(arg1 string) error {
	fake.validateOIDCIssuerMutex.Lock()
	ret, specificReturn := fake.validateOIDCIssuerReturnsOnCall[len(fake.validateOIDCIssuerArgsForCall)]
	fake.validateOIDCIssuerArgsForCall = append(fake.validateOIDCIssuerArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCIssuerStub
	fakeReturns := fake.validateOIDCIssuerReturns
	fake.recordInvocation("ValidateOIDCIssuer", []interface{}{arg1})
	fake.validateOIDCIssuerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerCallCount() int {
	fake.validateOIDCIssuerMutex.RLock()
	defer fake.validateOIDCIssuerMutex.RUnlock()
	return len(fake.validateOIDCIssuerArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerCalls(stub func(string) error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerArgsForCall(i int) string {
	fake.validateOIDCIssuerMutex.RLock()
	defer fake.validateOIDCIssuerMutex.RUnlock()
	argsForCall := fake.validateOIDCIssuerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerReturns(result1 error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = nil
	fake.validateOIDCIssuerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerReturnsOnCall(i int, result1 error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = nil
	if fake.validateOIDCIssuerReturnsOnCall == nil {
		fake.validateOIDCIssuerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCIssuerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURI(arg1 string) error {
	fake.validateOIDCRedirectURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCRedirectURIReturnsOnCall[len(fake.validateOIDCRedirectURIArgsForCall)]
	fake.validateOIDCRedirectURIArgsForCall = append(fake.validateOIDCRedirectURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCRedirectURIStub
	fakeReturns := fake.validateOIDCRedirectURIReturns
	fake.recordInvocation("ValidateOIDCRedirectURI", []interface{}{arg1})
	fake.validateOIDCRedirectURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURICallCount() int {
	fake.validateOIDCRedirectURIMutex.RLock()
	defer fake.validateOIDCRedirectURIMutex.RUnlock()
	return len(fake.validateOIDCRedirectURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURICalls(stub func(string) error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIArgsForCall(i int) string {
	fake.validateOIDCRedirectURIMutex.RLock()
	defer fake.validateOIDCRedirectURIMutex.RUnlock()
	argsForCall := fake.validateOIDCRedirectURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIReturns(result1 error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = nil
	fake.validateOIDCRedirectURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = nil
	if fake.validateOIDCRedirectURIReturnsOnCall == nil {
		fake.validateOIDCRedirectURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCRedirectURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURI(arg1 string) error {
	fake.validateOIDCLogoutURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCLogoutURIReturnsOnCall[len(fake.validateOIDCLogoutURIArgsForCall)]
	fake.validateOIDCLogoutURIArgsForCall = append(fake.validateOIDCLogoutURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCLogoutURIStub
	fakeReturns := fake.validateOIDCLogoutURIReturns
	fake.recordInvocation("ValidateOIDCLogoutURI", []interface{}{arg1})
	fake.validateOIDCLogoutURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURICallCount() int {
	fake.validateOIDCLogoutURIMutex.RLock()
	defer fake.validateOIDCLogoutURIMutex.RUnlock()
	return len(fake.validateOIDCLogoutURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURICalls(stub func(string) error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIArgsForCall(i int) string {
	fake.validateOIDCLogoutURIMutex.RLock()
	defer fake.validateOIDCLogoutURIMutex.RUnlock()
	argsForCall := fake.validateOIDCLogoutURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIReturns(result1 error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = nil
	fake.validateOIDCLogoutURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = nil
	if fake.validateOIDCLogoutURIReturnsOnCall == nil {
		fake.validateOIDCLogoutURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCLogoutURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthFieldsValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validation.AuthFieldsValidator = new(FakeAuthFieldsValidator)
