// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package validationfakes

import (
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/nginx/config/policies"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/conditions"
	"sync"
)

// PolicyValidatorMock is a mock implementation of validation.PolicyValidator.
//
//	func TestSomethingThatUsesPolicyValidator(t *testing.T) {
//
//		// make and configure a mocked validation.PolicyValidator
//		mockedPolicyValidator := &PolicyValidatorMock{
//			ConflictsFunc: func(a policies.Policy, b policies.Policy) bool {
//				panic("mock out the Conflicts method")
//			},
//			ValidateFunc: func(policy policies.Policy) []conditions.Condition {
//				panic("mock out the Validate method")
//			},
//			ValidateGlobalSettingsFunc: func(policy policies.Policy, globalSettings *policies.GlobalSettings) []conditions.Condition {
//				panic("mock out the ValidateGlobalSettings method")
//			},
//		}
//
//		// use mockedPolicyValidator in code that requires validation.PolicyValidator
//		// and then make assertions.
//
//	}
type PolicyValidatorMock struct {
	// ConflictsFunc mocks the Conflicts method.
	ConflictsFunc func(a policies.Policy, b policies.Policy) bool

	// ValidateFunc mocks the Validate method.
	ValidateFunc func(policy policies.Policy) []conditions.Condition

	// ValidateGlobalSettingsFunc mocks the ValidateGlobalSettings method.
	ValidateGlobalSettingsFunc func(policy policies.Policy, globalSettings *policies.GlobalSettings) []conditions.Condition

	// calls tracks calls to the methods.
	calls struct {
		// Conflicts holds details about calls to the Conflicts method.
		Conflicts []struct {
			// A is the a argument value.
			A policies.Policy
			// B is the b argument value.
			B policies.Policy
		}
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// Policy is the policy argument value.
			Policy policies.Policy
		}
		// ValidateGlobalSettings holds details about calls to the ValidateGlobalSettings method.
		ValidateGlobalSettings []struct {
			// Policy is the policy argument value.
			Policy policies.Policy
			// GlobalSettings is the globalSettings argument value.
			GlobalSettings *policies.GlobalSettings
		}
	}
	lockConflicts              sync.RWMutex
	lockValidate               sync.RWMutex
	lockValidateGlobalSettings sync.RWMutex
}

// Conflicts calls ConflictsFunc.
func (mock *PolicyValidatorMock) Conflicts(a policies.Policy, b policies.Policy) bool {
	if mock.ConflictsFunc == nil {
		panic("PolicyValidatorMock.ConflictsFunc: method is nil but PolicyValidator.Conflicts was just called")
	}
	callInfo := struct {
		A policies.Policy
		B policies.Policy
	}{
		A: a,
		B: b,
	}
	mock.lockConflicts.Lock()
	mock.calls.Conflicts = append(mock.calls.Conflicts, callInfo)
	mock.lockConflicts.Unlock()
	return mock.ConflictsFunc(a, b)
}

// ConflictsCalls gets all the calls that were made to Conflicts.
// Check the length with:
//
//	len(mockedPolicyValidator.ConflictsCalls())
func (mock *PolicyValidatorMock) ConflictsCalls() []struct {
	A policies.Policy
	B policies.Policy
} {
	var calls []struct {
		A policies.Policy
		B policies.Policy
	}
	mock.lockConflicts.RLock()
	calls = mock.calls.Conflicts
	mock.lockConflicts.RUnlock()
	return calls
}

// Validate calls ValidateFunc.
func (mock *PolicyValidatorMock) Validate(policy policies.Policy) []conditions.Condition {
	if mock.ValidateFunc == nil {
		panic("PolicyValidatorMock.ValidateFunc: method is nil but PolicyValidator.Validate was just called")
	}
	callInfo := struct {
		Policy policies.Policy
	}{
		Policy: policy,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc(policy)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockedPolicyValidator.ValidateCalls())
func (mock *PolicyValidatorMock) ValidateCalls() []struct {
	Policy policies.Policy
} {
	var calls []struct {
		Policy policies.Policy
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}

// ValidateGlobalSettings calls ValidateGlobalSettingsFunc.
func (mock *PolicyValidatorMock) ValidateGlobalSettings(policy policies.Policy, globalSettings *policies.GlobalSettings) []conditions.Condition {
	if mock.ValidateGlobalSettingsFunc == nil {
		panic("PolicyValidatorMock.ValidateGlobalSettingsFunc: method is nil but PolicyValidator.ValidateGlobalSettings was just called")
	}
	callInfo := struct {
		Policy         policies.Policy
		GlobalSettings *policies.GlobalSettings
	}{
		Policy:         policy,
		GlobalSettings: globalSettings,
	}
	mock.lockValidateGlobalSettings.Lock()
	mock.calls.ValidateGlobalSettings = append(mock.calls.ValidateGlobalSettings, callInfo)
	mock.lockValidateGlobalSettings.Unlock()
	return mock.ValidateGlobalSettingsFunc(policy, globalSettings)
}

// ValidateGlobalSettingsCalls gets all the calls that were made to ValidateGlobalSettings.
// Check the length with:
//
//	len(mockedPolicyValidator.ValidateGlobalSettingsCalls())
func (mock *PolicyValidatorMock) ValidateGlobalSettingsCalls() []struct {
	Policy         policies.Policy
	GlobalSettings *policies.GlobalSettings
} {
	var calls []struct {
		Policy         policies.Policy
		GlobalSettings *policies.GlobalSettings
	}
	mock.lockValidateGlobalSettings.RLock()
	calls = mock.calls.ValidateGlobalSettings
	mock.lockValidateGlobalSettings.RUnlock()
	return calls
}
