package main

import (
	"log"
	"os"
	"text/template"
)

//go:generate go run gen_policies.go

// Define policy types
var policies = []struct {
	Name         string
	HasSingleRef bool // true if it uses a single TargetRef, false if it uses TargetRefs
}{
	{"ClientSettingsPolicy", true},
	{"ObservabilityPolicy", false},
	{"UpstreamSettingsPolicy", false},
}

// Template for generating policy methods
const tmpl = `// Code generated by gen_policies.go; DO NOT EDIT.

package v1alpha1

import "sigs.k8s.io/gateway-api/apis/v1alpha2"

{{- range . }}

func (p *{{ .Name }}) GetTargetRefs() []v1alpha2.LocalPolicyTargetReference {
    {{- if .HasSingleRef }}
    return []v1alpha2.LocalPolicyTargetReference{p.Spec.TargetRef}
    {{- else }}
    return p.Spec.TargetRefs
    {{- end }}
}

func (p *{{ .Name }}) GetPolicyStatus() v1alpha2.PolicyStatus {
    return p.Status
}

func (p *{{ .Name }}) SetPolicyStatus(status v1alpha2.PolicyStatus) {
    p.Status = status
}

{{- end }}
`

func main() {
	// Ensure the output directory exists
	outputDir := "../apis/v1alpha1"
	if err := os.MkdirAll(outputDir, os.ModePerm); err != nil {
		log.Fatalf("failed to create directory: %v", err)
	}

	// Open the output file
	file, err := os.Create("../policy_methods.go")
	if err != nil {
		log.Fatalf("failed to create file: %v", err)
	}
	defer file.Close()

	// Create a template and execute it with the policy list
	t := template.Must(template.New("policy").Parse(tmpl))
	if err := t.Execute(file, policies); err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}

	log.Printf("Writing PolicyMethods to %s... Done\n", "policy_methods.go")
}
