// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package provisionerfakes

import (
	"context"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	"sync"
)

// ProvisionerMock is a mock implementation of provisioner.Provisioner.
//
//	func TestSomethingThatUsesProvisioner(t *testing.T) {
//
//		// make and configure a mocked provisioner.Provisioner
//		mockedProvisioner := &ProvisionerMock{
//			RegisterGatewayFunc: func(ctx context.Context, gateway *graph.Gateway, resourceName string) error {
//				panic("mock out the RegisterGateway method")
//			},
//		}
//
//		// use mockedProvisioner in code that requires provisioner.Provisioner
//		// and then make assertions.
//
//	}
type ProvisionerMock struct {
	// RegisterGatewayFunc mocks the RegisterGateway method.
	RegisterGatewayFunc func(ctx context.Context, gateway *graph.Gateway, resourceName string) error

	// calls tracks calls to the methods.
	calls struct {
		// RegisterGateway holds details about calls to the RegisterGateway method.
		RegisterGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gateway is the gateway argument value.
			Gateway *graph.Gateway
			// ResourceName is the resourceName argument value.
			ResourceName string
		}
	}
	lockRegisterGateway sync.RWMutex
}

// RegisterGateway calls RegisterGatewayFunc.
func (mock *ProvisionerMock) RegisterGateway(ctx context.Context, gateway *graph.Gateway, resourceName string) error {
	if mock.RegisterGatewayFunc == nil {
		panic("ProvisionerMock.RegisterGatewayFunc: method is nil but Provisioner.RegisterGateway was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Gateway      *graph.Gateway
		ResourceName string
	}{
		Ctx:          ctx,
		Gateway:      gateway,
		ResourceName: resourceName,
	}
	mock.lockRegisterGateway.Lock()
	mock.calls.RegisterGateway = append(mock.calls.RegisterGateway, callInfo)
	mock.lockRegisterGateway.Unlock()
	return mock.RegisterGatewayFunc(ctx, gateway, resourceName)
}

// RegisterGatewayCalls gets all the calls that were made to RegisterGateway.
// Check the length with:
//
//	len(mockedProvisioner.RegisterGatewayCalls())
func (mock *ProvisionerMock) RegisterGatewayCalls() []struct {
	Ctx          context.Context
	Gateway      *graph.Gateway
	ResourceName string
} {
	var calls []struct {
		Ctx          context.Context
		Gateway      *graph.Gateway
		ResourceName string
	}
	mock.lockRegisterGateway.RLock()
	calls = mock.calls.RegisterGateway
	mock.lockRegisterGateway.RUnlock()
	return calls
}
