// Code generated by counterfeiter. DO NOT EDIT.
package fetchfakes

import (
	"context"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/fetch"
)

type FakeFetcher struct {
	FetchLogProfileBundleStub        func(context.Context, fetch.Request) ([]byte, string, error)
	fetchLogProfileBundleMutex       sync.RWMutex
	fetchLogProfileBundleArgsForCall []struct {
		arg1 context.Context
		arg2 fetch.Request
	}
	fetchLogProfileBundleReturns struct {
		result1 []byte
		result2 string
		result3 error
	}
	fetchLogProfileBundleReturnsOnCall map[int]struct {
		result1 []byte
		result2 string
		result3 error
	}
	FetchPolicyBundleStub        func(context.Context, fetch.Request) ([]byte, string, error)
	fetchPolicyBundleMutex       sync.RWMutex
	fetchPolicyBundleArgsForCall []struct {
		arg1 context.Context
		arg2 fetch.Request
	}
	fetchPolicyBundleReturns struct {
		result1 []byte
		result2 string
		result3 error
	}
	fetchPolicyBundleReturnsOnCall map[int]struct {
		result1 []byte
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcher) FetchLogProfileBundle(arg1 context.Context, arg2 fetch.Request) ([]byte, string, error) {
	fake.fetchLogProfileBundleMutex.Lock()
	ret, specificReturn := fake.fetchLogProfileBundleReturnsOnCall[len(fake.fetchLogProfileBundleArgsForCall)]
	fake.fetchLogProfileBundleArgsForCall = append(fake.fetchLogProfileBundleArgsForCall, struct {
		arg1 context.Context
		arg2 fetch.Request
	}{arg1, arg2})
	stub := fake.FetchLogProfileBundleStub
	fakeReturns := fake.fetchLogProfileBundleReturns
	fake.recordInvocation("FetchLogProfileBundle", []interface{}{arg1, arg2})
	fake.fetchLogProfileBundleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeFetcher) FetchLogProfileBundleCallCount() int {
	fake.fetchLogProfileBundleMutex.RLock()
	defer fake.fetchLogProfileBundleMutex.RUnlock()
	return len(fake.fetchLogProfileBundleArgsForCall)
}

func (fake *FakeFetcher) FetchLogProfileBundleCalls(stub func(context.Context, fetch.Request) ([]byte, string, error)) {
	fake.fetchLogProfileBundleMutex.Lock()
	defer fake.fetchLogProfileBundleMutex.Unlock()
	fake.FetchLogProfileBundleStub = stub
}

func (fake *FakeFetcher) FetchLogProfileBundleArgsForCall(i int) (context.Context, fetch.Request) {
	fake.fetchLogProfileBundleMutex.RLock()
	defer fake.fetchLogProfileBundleMutex.RUnlock()
	argsForCall := fake.fetchLogProfileBundleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFetcher) FetchLogProfileBundleReturns(result1 []byte, result2 string, result3 error) {
	fake.fetchLogProfileBundleMutex.Lock()
	defer fake.fetchLogProfileBundleMutex.Unlock()
	fake.FetchLogProfileBundleStub = nil
	fake.fetchLogProfileBundleReturns = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFetcher) FetchLogProfileBundleReturnsOnCall(i int, result1 []byte, result2 string, result3 error) {
	fake.fetchLogProfileBundleMutex.Lock()
	defer fake.fetchLogProfileBundleMutex.Unlock()
	fake.FetchLogProfileBundleStub = nil
	if fake.fetchLogProfileBundleReturnsOnCall == nil {
		fake.fetchLogProfileBundleReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 string
			result3 error
		})
	}
	fake.fetchLogProfileBundleReturnsOnCall[i] = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFetcher) FetchPolicyBundle(arg1 context.Context, arg2 fetch.Request) ([]byte, string, error) {
	fake.fetchPolicyBundleMutex.Lock()
	ret, specificReturn := fake.fetchPolicyBundleReturnsOnCall[len(fake.fetchPolicyBundleArgsForCall)]
	fake.fetchPolicyBundleArgsForCall = append(fake.fetchPolicyBundleArgsForCall, struct {
		arg1 context.Context
		arg2 fetch.Request
	}{arg1, arg2})
	stub := fake.FetchPolicyBundleStub
	fakeReturns := fake.fetchPolicyBundleReturns
	fake.recordInvocation("FetchPolicyBundle", []interface{}{arg1, arg2})
	fake.fetchPolicyBundleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeFetcher) FetchPolicyBundleCallCount() int {
	fake.fetchPolicyBundleMutex.RLock()
	defer fake.fetchPolicyBundleMutex.RUnlock()
	return len(fake.fetchPolicyBundleArgsForCall)
}

func (fake *FakeFetcher) FetchPolicyBundleCalls(stub func(context.Context, fetch.Request) ([]byte, string, error)) {
	fake.fetchPolicyBundleMutex.Lock()
	defer fake.fetchPolicyBundleMutex.Unlock()
	fake.FetchPolicyBundleStub = stub
}

func (fake *FakeFetcher) FetchPolicyBundleArgsForCall(i int) (context.Context, fetch.Request) {
	fake.fetchPolicyBundleMutex.RLock()
	defer fake.fetchPolicyBundleMutex.RUnlock()
	argsForCall := fake.fetchPolicyBundleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFetcher) FetchPolicyBundleReturns(result1 []byte, result2 string, result3 error) {
	fake.fetchPolicyBundleMutex.Lock()
	defer fake.fetchPolicyBundleMutex.Unlock()
	fake.FetchPolicyBundleStub = nil
	fake.fetchPolicyBundleReturns = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFetcher) FetchPolicyBundleReturnsOnCall(i int, result1 []byte, result2 string, result3 error) {
	fake.fetchPolicyBundleMutex.Lock()
	defer fake.fetchPolicyBundleMutex.Unlock()
	fake.FetchPolicyBundleStub = nil
	if fake.fetchPolicyBundleReturnsOnCall == nil {
		fake.fetchPolicyBundleReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 string
			result3 error
		})
	}
	fake.fetchPolicyBundleReturnsOnCall[i] = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fetch.Fetcher = new(FakeFetcher)
