// Code generated by counterfeiter. DO NOT EDIT.
package fetchfakes

import (
	"context"
	"crypto/tls"
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/fetch"
)

type FakeFetcher struct {
	GetObjectStub        func(context.Context, string, string) ([]byte, error)
	getObjectMutex       sync.RWMutex
	getObjectArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getObjectReturns struct {
		result1 []byte
		result2 error
	}
	getObjectReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	UpdateTLSConfigStub        func(*tls.Config) error
	updateTLSConfigMutex       sync.RWMutex
	updateTLSConfigArgsForCall []struct {
		arg1 *tls.Config
	}
	updateTLSConfigReturns struct {
		result1 error
	}
	updateTLSConfigReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcher) GetObject(arg1 context.Context, arg2 string, arg3 string) ([]byte, error) {
	fake.getObjectMutex.Lock()
	ret, specificReturn := fake.getObjectReturnsOnCall[len(fake.getObjectArgsForCall)]
	fake.getObjectArgsForCall = append(fake.getObjectArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetObjectStub
	fakeReturns := fake.getObjectReturns
	fake.recordInvocation("GetObject", []interface{}{arg1, arg2, arg3})
	fake.getObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFetcher) GetObjectCallCount() int {
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	return len(fake.getObjectArgsForCall)
}

func (fake *FakeFetcher) GetObjectCalls(stub func(context.Context, string, string) ([]byte, error)) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = stub
}

func (fake *FakeFetcher) GetObjectArgsForCall(i int) (context.Context, string, string) {
	fake.getObjectMutex.RLock()
	defer fake.getObjectMutex.RUnlock()
	argsForCall := fake.getObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeFetcher) GetObjectReturns(result1 []byte, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	fake.getObjectReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) GetObjectReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getObjectMutex.Lock()
	defer fake.getObjectMutex.Unlock()
	fake.GetObjectStub = nil
	if fake.getObjectReturnsOnCall == nil {
		fake.getObjectReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getObjectReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) UpdateTLSConfig(arg1 *tls.Config) error {
	fake.updateTLSConfigMutex.Lock()
	ret, specificReturn := fake.updateTLSConfigReturnsOnCall[len(fake.updateTLSConfigArgsForCall)]
	fake.updateTLSConfigArgsForCall = append(fake.updateTLSConfigArgsForCall, struct {
		arg1 *tls.Config
	}{arg1})
	stub := fake.UpdateTLSConfigStub
	fakeReturns := fake.updateTLSConfigReturns
	fake.recordInvocation("UpdateTLSConfig", []interface{}{arg1})
	fake.updateTLSConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFetcher) UpdateTLSConfigCallCount() int {
	fake.updateTLSConfigMutex.RLock()
	defer fake.updateTLSConfigMutex.RUnlock()
	return len(fake.updateTLSConfigArgsForCall)
}

func (fake *FakeFetcher) UpdateTLSConfigCalls(stub func(*tls.Config) error) {
	fake.updateTLSConfigMutex.Lock()
	defer fake.updateTLSConfigMutex.Unlock()
	fake.UpdateTLSConfigStub = stub
}

func (fake *FakeFetcher) UpdateTLSConfigArgsForCall(i int) *tls.Config {
	fake.updateTLSConfigMutex.RLock()
	defer fake.updateTLSConfigMutex.RUnlock()
	argsForCall := fake.updateTLSConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFetcher) UpdateTLSConfigReturns(result1 error) {
	fake.updateTLSConfigMutex.Lock()
	defer fake.updateTLSConfigMutex.Unlock()
	fake.UpdateTLSConfigStub = nil
	fake.updateTLSConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFetcher) UpdateTLSConfigReturnsOnCall(i int, result1 error) {
	fake.updateTLSConfigMutex.Lock()
	defer fake.updateTLSConfigMutex.Unlock()
	fake.UpdateTLSConfigStub = nil
	if fake.updateTLSConfigReturnsOnCall == nil {
		fake.updateTLSConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateTLSConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fetch.Fetcher = new(FakeFetcher)
