// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package statefakes

import (
	"context"
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	frameworkevents "github.com/nginx/nginx-gateway-fabric/v2/internal/framework/events"
	"sync"
)

// ChangeProcessorMock is a mock implementation of state.ChangeProcessor.
//
//	func TestSomethingThatUsesChangeProcessor(t *testing.T) {
//
//		// make and configure a mocked state.ChangeProcessor
//		mockedChangeProcessor := &ChangeProcessorMock{
//			ForceRebuildFunc: func()  {
//				panic("mock out the ForceRebuild method")
//			},
//			GetLatestGraphFunc: func() *graph.Graph {
//				panic("mock out the GetLatestGraph method")
//			},
//			ProcessFunc: func(ctx context.Context, logger logr.Logger, batch frameworkevents.EventBatch) *graph.Graph {
//				panic("mock out the Process method")
//			},
//		}
//
//		// use mockedChangeProcessor in code that requires state.ChangeProcessor
//		// and then make assertions.
//
//	}
type ChangeProcessorMock struct {
	// ForceRebuildFunc mocks the ForceRebuild method.
	ForceRebuildFunc func()

	// GetLatestGraphFunc mocks the GetLatestGraph method.
	GetLatestGraphFunc func() *graph.Graph

	// ProcessFunc mocks the Process method.
	ProcessFunc func(ctx context.Context, logger logr.Logger, batch frameworkevents.EventBatch) *graph.Graph

	// calls tracks calls to the methods.
	calls struct {
		// ForceRebuild holds details about calls to the ForceRebuild method.
		ForceRebuild []struct {
		}
		// GetLatestGraph holds details about calls to the GetLatestGraph method.
		GetLatestGraph []struct {
		}
		// Process holds details about calls to the Process method.
		Process []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Logger is the logger argument value.
			Logger logr.Logger
			// Batch is the batch argument value.
			Batch frameworkevents.EventBatch
		}
	}
	lockForceRebuild   sync.RWMutex
	lockGetLatestGraph sync.RWMutex
	lockProcess        sync.RWMutex
}

// ForceRebuild calls ForceRebuildFunc.
func (mock *ChangeProcessorMock) ForceRebuild() {
	if mock.ForceRebuildFunc == nil {
		panic("ChangeProcessorMock.ForceRebuildFunc: method is nil but ChangeProcessor.ForceRebuild was just called")
	}
	callInfo := struct {
	}{}
	mock.lockForceRebuild.Lock()
	mock.calls.ForceRebuild = append(mock.calls.ForceRebuild, callInfo)
	mock.lockForceRebuild.Unlock()
	mock.ForceRebuildFunc()
}

// ForceRebuildCalls gets all the calls that were made to ForceRebuild.
// Check the length with:
//
//	len(mockedChangeProcessor.ForceRebuildCalls())
func (mock *ChangeProcessorMock) ForceRebuildCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockForceRebuild.RLock()
	calls = mock.calls.ForceRebuild
	mock.lockForceRebuild.RUnlock()
	return calls
}

// GetLatestGraph calls GetLatestGraphFunc.
func (mock *ChangeProcessorMock) GetLatestGraph() *graph.Graph {
	if mock.GetLatestGraphFunc == nil {
		panic("ChangeProcessorMock.GetLatestGraphFunc: method is nil but ChangeProcessor.GetLatestGraph was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLatestGraph.Lock()
	mock.calls.GetLatestGraph = append(mock.calls.GetLatestGraph, callInfo)
	mock.lockGetLatestGraph.Unlock()
	return mock.GetLatestGraphFunc()
}

// GetLatestGraphCalls gets all the calls that were made to GetLatestGraph.
// Check the length with:
//
//	len(mockedChangeProcessor.GetLatestGraphCalls())
func (mock *ChangeProcessorMock) GetLatestGraphCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLatestGraph.RLock()
	calls = mock.calls.GetLatestGraph
	mock.lockGetLatestGraph.RUnlock()
	return calls
}

// Process calls ProcessFunc.
func (mock *ChangeProcessorMock) Process(ctx context.Context, logger logr.Logger, batch frameworkevents.EventBatch) *graph.Graph {
	if mock.ProcessFunc == nil {
		panic("ChangeProcessorMock.ProcessFunc: method is nil but ChangeProcessor.Process was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Logger logr.Logger
		Batch  frameworkevents.EventBatch
	}{
		Ctx:    ctx,
		Logger: logger,
		Batch:  batch,
	}
	mock.lockProcess.Lock()
	mock.calls.Process = append(mock.calls.Process, callInfo)
	mock.lockProcess.Unlock()
	return mock.ProcessFunc(ctx, logger, batch)
}

// ProcessCalls gets all the calls that were made to Process.
// Check the length with:
//
//	len(mockedChangeProcessor.ProcessCalls())
func (mock *ChangeProcessorMock) ProcessCalls() []struct {
	Ctx    context.Context
	Logger logr.Logger
	Batch  frameworkevents.EventBatch
} {
	var calls []struct {
		Ctx    context.Context
		Logger logr.Logger
		Batch  frameworkevents.EventBatch
	}
	mock.lockProcess.RLock()
	calls = mock.calls.Process
	mock.lockProcess.RUnlock()
	return calls
}
