// Code generated by counterfeiter. DO NOT EDIT.
package statefakes

import (
	"context"
	"sync"

	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/framework/events"
)

type FakeChangeProcessor struct {
	ForceRebuildStub        func()
	forceRebuildMutex       sync.RWMutex
	forceRebuildArgsForCall []struct {
	}
	GetLatestGraphStub        func() *graph.Graph
	getLatestGraphMutex       sync.RWMutex
	getLatestGraphArgsForCall []struct {
	}
	getLatestGraphReturns struct {
		result1 *graph.Graph
	}
	getLatestGraphReturnsOnCall map[int]struct {
		result1 *graph.Graph
	}
	ProcessStub        func(context.Context, logr.Logger, events.EventBatch) *graph.Graph
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 events.EventBatch
	}
	processReturns struct {
		result1 *graph.Graph
	}
	processReturnsOnCall map[int]struct {
		result1 *graph.Graph
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChangeProcessor) ForceRebuild() {
	fake.forceRebuildMutex.Lock()
	fake.forceRebuildArgsForCall = append(fake.forceRebuildArgsForCall, struct {
	}{})
	stub := fake.ForceRebuildStub
	fake.recordInvocation("ForceRebuild", []interface{}{})
	fake.forceRebuildMutex.Unlock()
	if stub != nil {
		fake.ForceRebuildStub()
	}
}

func (fake *FakeChangeProcessor) ForceRebuildCallCount() int {
	fake.forceRebuildMutex.RLock()
	defer fake.forceRebuildMutex.RUnlock()
	return len(fake.forceRebuildArgsForCall)
}

func (fake *FakeChangeProcessor) ForceRebuildCalls(stub func()) {
	fake.forceRebuildMutex.Lock()
	defer fake.forceRebuildMutex.Unlock()
	fake.ForceRebuildStub = stub
}

func (fake *FakeChangeProcessor) GetLatestGraph() *graph.Graph {
	fake.getLatestGraphMutex.Lock()
	ret, specificReturn := fake.getLatestGraphReturnsOnCall[len(fake.getLatestGraphArgsForCall)]
	fake.getLatestGraphArgsForCall = append(fake.getLatestGraphArgsForCall, struct {
	}{})
	stub := fake.GetLatestGraphStub
	fakeReturns := fake.getLatestGraphReturns
	fake.recordInvocation("GetLatestGraph", []interface{}{})
	fake.getLatestGraphMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChangeProcessor) GetLatestGraphCallCount() int {
	fake.getLatestGraphMutex.RLock()
	defer fake.getLatestGraphMutex.RUnlock()
	return len(fake.getLatestGraphArgsForCall)
}

func (fake *FakeChangeProcessor) GetLatestGraphCalls(stub func() *graph.Graph) {
	fake.getLatestGraphMutex.Lock()
	defer fake.getLatestGraphMutex.Unlock()
	fake.GetLatestGraphStub = stub
}

func (fake *FakeChangeProcessor) GetLatestGraphReturns(result1 *graph.Graph) {
	fake.getLatestGraphMutex.Lock()
	defer fake.getLatestGraphMutex.Unlock()
	fake.GetLatestGraphStub = nil
	fake.getLatestGraphReturns = struct {
		result1 *graph.Graph
	}{result1}
}

func (fake *FakeChangeProcessor) GetLatestGraphReturnsOnCall(i int, result1 *graph.Graph) {
	fake.getLatestGraphMutex.Lock()
	defer fake.getLatestGraphMutex.Unlock()
	fake.GetLatestGraphStub = nil
	if fake.getLatestGraphReturnsOnCall == nil {
		fake.getLatestGraphReturnsOnCall = make(map[int]struct {
			result1 *graph.Graph
		})
	}
	fake.getLatestGraphReturnsOnCall[i] = struct {
		result1 *graph.Graph
	}{result1}
}

func (fake *FakeChangeProcessor) Process(arg1 context.Context, arg2 logr.Logger, arg3 events.EventBatch) *graph.Graph {
	fake.processMutex.Lock()
	ret, specificReturn := fake.processReturnsOnCall[len(fake.processArgsForCall)]
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 events.EventBatch
	}{arg1, arg2, arg3})
	stub := fake.ProcessStub
	fakeReturns := fake.processReturns
	fake.recordInvocation("Process", []interface{}{arg1, arg2, arg3})
	fake.processMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChangeProcessor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *FakeChangeProcessor) ProcessCalls(stub func(context.Context, logr.Logger, events.EventBatch) *graph.Graph) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = stub
}

func (fake *FakeChangeProcessor) ProcessArgsForCall(i int) (context.Context, logr.Logger, events.EventBatch) {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	argsForCall := fake.processArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeChangeProcessor) ProcessReturns(result1 *graph.Graph) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	fake.processReturns = struct {
		result1 *graph.Graph
	}{result1}
}

func (fake *FakeChangeProcessor) ProcessReturnsOnCall(i int, result1 *graph.Graph) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	if fake.processReturnsOnCall == nil {
		fake.processReturnsOnCall = make(map[int]struct {
			result1 *graph.Graph
		})
	}
	fake.processReturnsOnCall[i] = struct {
		result1 *graph.Graph
	}{result1}
}

func (fake *FakeChangeProcessor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChangeProcessor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ state.ChangeProcessor = new(FakeChangeProcessor)
