//go:build !ignore_autogenerated

// Code generated by policygen. DO NOT EDIT.

package v1alpha1

import (
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// GetTargetRefs implements the policies.Policy interface for ClientSettingsPolicy.
func (p *ClientSettingsPolicy) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	return []gatewayv1.LocalPolicyTargetReference{p.Spec.TargetRef}
}

// GetPolicyStatus implements the policies.Policy interface for ClientSettingsPolicy.
func (p *ClientSettingsPolicy) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

// SetPolicyStatus implements the policies.Policy interface for ClientSettingsPolicy.
func (p *ClientSettingsPolicy) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}

// GetTargetRefs implements the policies.Policy interface for UpstreamSettingsPolicy.
func (p *UpstreamSettingsPolicy) GetTargetRefs() []gatewayv1.LocalPolicyTargetReference {
	return p.Spec.TargetRefs
}

// GetPolicyStatus implements the policies.Policy interface for UpstreamSettingsPolicy.
func (p *UpstreamSettingsPolicy) GetPolicyStatus() gatewayv1.PolicyStatus {
	return p.Status
}

// SetPolicyStatus implements the policies.Policy interface for UpstreamSettingsPolicy.
func (p *UpstreamSettingsPolicy) SetPolicyStatus(status gatewayv1.PolicyStatus) {
	p.Status = status
}
