apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFGjCCAwKgAwIBAgIUUP0aVmEyZXwOr7tz8e7wx5Tx+egwDQYJKoZIhvcNAQEL
    BQAwEjEQMA4GA1UEAwwHTG9jYWxDQTAeFw0yNjAzMTAxMDA0MzhaFw0yNzAzMTAx
    MDA0MzhaMBsxGTAXBgNVBAMMEGNhZmUuZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3
    DQEBAQUAA4ICDwAwggIKAoICAQC+QvY1ZdXdhn34rL05gz9AB+SzekdScWxn2m9t
    rZblhHgtFxLBzSRCCKgTAm9DU8I3D535oIdbdFCNQHFS5ZBXKT09Or8ELDJs5Mqb
    ZmrXwE95jRUR+Sn4V/27uOeZIvZFeQ5Z64OQWNO0O2dtvF7v8TnndwyAODGTjoQg
    Rf7kJPMoGqCS8KpH+e94QbB+igZLBvcNoYXJrh+u69izY/5oxPzP5VvXjYBToqyO
    slBtaPvjQWSZHj3xK7oJ8SQ/JyHwA1500viU/8xs5HlseGmPi+LPuByirMqqtAHy
    eHVK0aoTF3wnwjICTLYKlT3qLYFtUBxHEnOFJyLL6Vm2ql/BGelSRmgMcBh/W9oH
    PQwKVVd9SpjPYO3n8U1ras8+TopFJy8jbMICtnFqdhlb9Dz48BcLA0Nl8Pdv9mka
    4LjVQiysfJdxyqR4WOate+XIbebATPeStPaReOGSCD35lk4+NDl4zMUVw/iRV0st
    Tl7sb9HuBz3dgRfKbhgWThNTHJ08+B3SfsKTtibMIdqrr15lHqG5QOkC0sUOwY+w
    fKv/F++YrP933M4XqPaMrSXd6yqJ3ft1JOwEarbv4l21mkxW//5BMq96EfAU0A/J
    7y7uTujFEkACd9PLC3w75he1tOEmmzHGpB+AsUEWIuYCXmpAlqFTKiPL994qMqV5
    OzlabwIDAQABo18wXTAbBgNVHREEFDASghBjYWZlLmV4YW1wbGUuY29tMB0GA1Ud
    DgQWBBQLCt+cxxptUeeZxIsb8BzZ5/rVJjAfBgNVHSMEGDAWgBQnBpa1ZSOcv1Mz
    /est/sZKZw7rBDANBgkqhkiG9w0BAQsFAAOCAgEAJ/XU0Ftu4QLw+OQo9Bv3kCYI
    OSmNRZSBrurSZ7s7+4T5vzuu4MciPpXV+RM5fwuIT6n6fTLlZJfwCwZf1qWExnTv
    S4BQNxJsmP3TwpuvYJorjcZ5ojBzifK74NOdRfVV/mFocairvkv50swoks5niVkS
    NarzC9CpszE/6DOsxqa5K0q5Gl/T655rUhvEJRPuOYC13yCbDN/fssMmJyr3HySL
    D0rKydUIi+tf3eUo5BTpZ7nsSx/o0NGXeMCfFn/z5kgFlwITp+IgxehiLFnyo3Bi
    vnkKdasPdUFRyxLMye8mRO9M9xZqJFqlqHLdxQCYchr2ir/VEA9M6tM6rF+R8LW1
    k/Enm8xX2YluJRy7lI66mN0PVt6v0nuSpHpM+AlP4V8fHqcDstSlYHZlogOtBg46
    4C02qfd6jGPJtwHFa/c692fLlq66U+mCQCqsgEnPeqns9qalyjd0bJNnDom/OWZD
    AzmP4KH7+ysdTc0S9hQpyP2kf+MlBTT6kRHqidEXy3wF4b7b/3J0KOycunFdALbi
    q5zEUwYhmHvfSKN6tph9IhWolNTowSz2Lq/ng2YkDVkch3HkFVQhdbb59P1CJVzV
    4O2pdwf3p+F8AwZG1MiecQqMwAQmu7caBMVjwbfRjKaWRfK3jrfX1r8nzkiOScUX
    idp5WWf3v2Hx1KOTbPU=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC+QvY1ZdXdhn34
    rL05gz9AB+SzekdScWxn2m9trZblhHgtFxLBzSRCCKgTAm9DU8I3D535oIdbdFCN
    QHFS5ZBXKT09Or8ELDJs5MqbZmrXwE95jRUR+Sn4V/27uOeZIvZFeQ5Z64OQWNO0
    O2dtvF7v8TnndwyAODGTjoQgRf7kJPMoGqCS8KpH+e94QbB+igZLBvcNoYXJrh+u
    69izY/5oxPzP5VvXjYBToqyOslBtaPvjQWSZHj3xK7oJ8SQ/JyHwA1500viU/8xs
    5HlseGmPi+LPuByirMqqtAHyeHVK0aoTF3wnwjICTLYKlT3qLYFtUBxHEnOFJyLL
    6Vm2ql/BGelSRmgMcBh/W9oHPQwKVVd9SpjPYO3n8U1ras8+TopFJy8jbMICtnFq
    dhlb9Dz48BcLA0Nl8Pdv9mka4LjVQiysfJdxyqR4WOate+XIbebATPeStPaReOGS
    CD35lk4+NDl4zMUVw/iRV0stTl7sb9HuBz3dgRfKbhgWThNTHJ08+B3SfsKTtibM
    Idqrr15lHqG5QOkC0sUOwY+wfKv/F++YrP933M4XqPaMrSXd6yqJ3ft1JOwEarbv
    4l21mkxW//5BMq96EfAU0A/J7y7uTujFEkACd9PLC3w75he1tOEmmzHGpB+AsUEW
    IuYCXmpAlqFTKiPL994qMqV5OzlabwIDAQABAoICAFiOglrIU4sQloGwpUKnvEDp
    a6G+QIQ3FuYf3c2HBr09s1IJc0mRWlcCAHkYoQENc1B9jGIsPdRrhzK31Adpoo1v
    PHnLZi1jBPV6aHN8cC6L7HH/INeEyew1yHwfzGySwV4EwpFH9ayyK5ewLqv9CZNV
    DEaYOtFTVn//za/X5JP8PtFj02mRazClPLkUmjnLtLInQ8asb8E3sreQPwUAfeH2
    DlYVw3HJAvnqtbaVeKn0O4nDXjeGw/4FBEqsWtqqNDmq18Q4jkuL5HKqxXmfckLG
    MYPNhkaRdqONtXpOZwm0HR1VyQwYb35yhijW3kKpe5yNtRu/ktVfKesPahqDop1H
    OaX1uQnEr657ZeIqEbFLw8k1TVckVsLltW16YXOuar967H9ifoHl8tfrs0cY+gzH
    cA3/pFrGxTV3qYARzcL/0j5CJi5r4XkqvKR82e6/GKwBp0Nhc1rDEvSSgXYfqlZS
    Gw/faHigccvVM7GGbOrMNeaih2qG1qPJMqXY0yH/kgBDwNjVOWi8h7x9BIWDK8xA
    61UEoDHpHIn2Cqq7BpQzTsj26sK+xrYrqWj7bP17uWeHMuMjjQkPwXQwH5pvsI+r
    SdVqaPQhLYZZ/WVAwK6nJ4LCJ6Is5GLJiOHAHoeqBKmGJpvThF+s6PQ2EmfWDf+h
    eq8bnvD/ay6kuQ81OJvBAoIBAQD9FUWGoJxR2D5JDHMvHfgvxu1N/d4mUNBn6//Z
    8Kf7l/F56IXZ+eMa/I7jXwZqHqERgzrGkrn+p5il38M+2NqFb5pZTwcHP4KdGNX6
    rIFz30CmZ7ebuVZ9RKG1JqvSaSn0htMhETN2D66OViAaoMIehFKBUMUsLjAacP2N
    8gPXzi7jX+B6KWAnjqo/EJhIcCU1FYF3pOqA45pi3YnCoJhr5O68V0avyO80ssM1
    TuItGWK+LeTprzv48MMLIRKw9vQU4+PeH4EFJ3jiVxPdUU7n/Z7jk77oUSR3GVxi
    /WAG4IM6mbf5kH0mGfLvv4KouGx14PBK6A/+e7s0dtSopWA9AoIBAQDAdFVmBeGa
    Cutg6nfsdmbDTE7JMGxHuSmPOAk1kd0oDuDjn/UyqCDpoiCJb5XSnmVI4nRTob8f
    OlI0af2jgSOlIP1Jt1NQhVh1mGfoXLJBeEQDDTqQWpoQgykT/0NIOK8IkLm5dpYG
    7Hm4pYC65/uDLm5m/dZZVXkG/lFi7u6Q+ksyNOBxnOlAcNkAHtnMs7WiUSc0CjvT
    RSE7AaMWSDw5eljJ4v3edKJKgg2Bl4eWIPhj/uQInQVu7uUwxKNR+kjWE3GA4zy1
    OIiHknLP8+rvOcCnkdeQQs3wvQNJ5ffh3UsiJ2HEIwcohVLgYUNH8OQtsJqLU4ee
    pR5cLc3gmEQbAoIBADhiadgBpnIRlGbf8DWaHrY+QpZyrfCpZpUQnjLnC/Xgtzrq
    1A9pPfDAPfFoNVylMEtfilO9UtTqb/bcsHorBBxgbenh0nYJ70aixuGPV1QCdDve
    tahrFVrZVJGwaO164o8JDra6R1XRTpmFlKd6E2WLI3qODS+3pp3teIAMYFDPLeEY
    dkGhQDvv6/wa7WKOIav++5Y1Vs2aZ8YJB20mLG81VP7/Ds+RG8II5bbVuUxE8Jvg
    S7TIhrsCoOG0354vltekohrVt//2+FatAc74E3VaKvEW9Jx7n30tWEjxnFhL4tDG
    eJeQWmGHvHkvmKOQWxG0KLT3mMCgvmeE5gIgvh0CggEAPoLK5kuMvsNDNwSRlV3T
    /SWBBbpTwWw0Qo+59gt94TAL/gOL2jtgDWMa3GlBKdtHHMhpbmzALn18DAhNWVlt
    4Yn4m4QPbL0TQYcSYRgS0k8lEDSwzAiRuEFSC2vDR+cZe1e+663IB1GyK7aePJdz
    S2W+eHeEsxmfKRVcDB19oduapyEjseN8o/DDm1Vp+yJ4IdPoPvAABJyUsZzTgz5N
    SYIi6thvC12pBTh++JPmd24YICq/mMif5it0iEWmos7/74D7QhkNM/O77QU1g7Q/
    oBqLKCKn+PSp/cL3GX636EY/zEUsbU/PWGsNw1H0T57ADtMpL44fI/mQBfLex0/N
    9wKCAQEAjg7QDKAHKjeYH/7eTsBR/Qerm2ccbQnc2MD25vCgopQ4hPSETAkLyyZy
    h8CcSIpv7KYY0qV+gTQPl5p+5yfBdlvezWVfD4d7uoSRGc8+It8LILsnkj9ZtyQP
    jMaI4o3GqfU9tmr4Fnq5BTllYS60l57wKzgwZ36rAEBJvcteULG0tfvQA4PeWPky
    E9QKS4kstaaCksUmppivFiL/yAQEEZV/CmMBh4oYcLCjqUZSSkxt+KNe4HQ8sDb+
    NnwlmA6EkaY4y941iXOnbJo2d52RGMIU2tGJO4s1g3V4fMuBj4bovIrxk5gJMKdS
    oOUTdsIlgOH1hYA3JZSHId1wLI+Tjw==
    -----END PRIVATE KEY-----
