apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  # base64 encoded placeholder; replace with your own Keycloak client secret
  client-secret: azJQS3RXbEFKU0FRREJNckUxQjdrOUlJTHFaNXIyOEo=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-ca
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFBTCCAu2gAwIBAgIUUKjfEzHyQCmPo+hFFw3iEPSPfEgwDQYJKoZIhvcNAQEL
    BQAwEjEQMA4GA1UEAwwHTG9jYWxDQTAeFw0yNjAzMTAxMDAyNTRaFw0yNzAzMTAx
    MDAyNTRaMBIxEDAOBgNVBAMMB0xvY2FsQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDL7/jNIJVUDnJ4nfUeESXoH9RPem0qgjtqZ/BHD1dlQrQtG/rl
    JGNgNQY3XNX6NBDr4nULOGJi6jbV8v3d9ovuZKvlcO92q4IV7Y5Xtx1yjYBmGlQT
    WKwvbzxjw4obISRr+p+MkeXaoSEEazekpLSV7XgNIGyh6JuwcHQ9qDJX9nH5dAR4
    CLhsf79ofuoMB5JP3Kbbayck7qwr37c5oubRC6Fh7q9YZmHHZ7sSXVW0nMKuc0vS
    U5pYukfGBm0UTRtIOX4nrsu5HD1gIP0/+GtdX+7oH+b+Ia0gis5MPpbejMjk+HKY
    ulhuX1J/pQnF0QYW2rbGt3o22QT5KqJAiKwUTBbeA1Ms3d+yjRmyo0IFaVd4T+3U
    ee4w8qscypIKrj0h+Xg51e0ynMKzdOYQ6yzhl/MT0zuMCuyuPzDKZGBkHMTVGpDF
    fvBzex5DJqpl2pHrVKoUbRUcaKZhOg4O7DqDhmH/aV9O2vxwueapFqCsjewQ6DzO
    XdcU4uNwSWzSiEcV53r4SCpIGEmahEXZ0EeqATEyG6ZrNhGGSeB7gIQqI3CNTAJJ
    0qyH+eWReTB9RT/9PSS9TSfye7H8YE33fD3SgGDgvzymHL89fz/4N8ydODyGQc3B
    j7ra4utIO2WD6/0QV1j4f8u/emwX6MCyK5KlmydDqVcbxMvDROjhdqVnEQIDAQAB
    o1MwUTAdBgNVHQ4EFgQUJwaWtWUjnL9TM/3rLf7GSmcO6wQwHwYDVR0jBBgwFoAU
    JwaWtWUjnL9TM/3rLf7GSmcO6wQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAgEABPgRvLyHPjcAJ1bC7QMu80JDUOd29lcIqCzeoOzChmeEq2v6STWa
    RmT5SIVy5MSNBWIzRjq0qz9GD2BfDQ/KTTlh/tm9oz1P34FTMGXgVopLKEZQw5Hq
    4JNI+WWXF6pHHj4VVpcfnxUbgmV56itO4CK9cyQk9jZPHP6EoxnNitva3cCTqsYU
    kyuzTprWhfkRVo7CnDexbzR2Lx8mGhoIdzvpNK6dOMjdtEaYhgHhaFB5VE8aQ0hZ
    quTAuHWbngdexPQmsD8UPtIOHDS+Y7RAMnonG3aOmNZ4hu2b5WWE+a8BhdcbhIWF
    /XI3WR1BwMSgJ1eMDCpP+3nqBH6hnD9lhT5emkwxtwnuIn9JAAYt1HroWFV5csKw
    bTS6sr51UotwQx3N5xAlQ65uGNAYBF6Ak8wGQV8Pcyd5g5OQdy4KaHZxwOAvYBL4
    Ep6jtRJxfHJxnNA6JItb1QHGaT3HM21h6TvwqereXYiEy6DXmEkrBLcI/iEcFJs4
    hH1wGuPdD9NobHd/+0RqkedDIsVBZv5UFSH6qmuojrl/JylAPMWlG1MBVlCRnAn2
    bJmmliuzyHHkhdS6MAji0kYT+EsAKdKslN+10hElm8NKRb6LknoHpI9dz20qsf4P
    unQo/qGHOS9UEaW2DaZThuxpy6Dddk8BT1o30YzfHUWkOZicmGbyjmM=
    -----END CERTIFICATE-----
