apiVersion: gateway.nginx.org/v1alpha1
kind: AuthenticationFilter
metadata:
  name: oidc-nginx-gateway
spec:
  type: OIDC
  oidc:
    clientSecretRef:
      name: keycloak-dual-secret
    clientID: nginx-gateway
    issuer: https://host.docker.internal:8443/realms/nginx-gateway
    caCertificateRefs:
      - name: keycloak-dual-secret
---
apiVersion: gateway.nginx.org/v1alpha1
kind: AuthenticationFilter
metadata:
  name: oidc-user-service
spec:
  type: OIDC
  oidc:
    clientSecretRef:
      name: keycloak-dual-secret
    clientID: user-service
    issuer: https://host.docker.internal:8443/realms/user-service
    caCertificateRefs:
      - name: keycloak-dual-secret
