// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package crdfakes

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/rest"
	"sync"
)

// CheckerMock is a mock implementation of crd.Checker.
//
//	func TestSomethingThatUsesChecker(t *testing.T) {
//
//		// make and configure a mocked crd.Checker
//		mockedChecker := &CheckerMock{
//			CheckCRDsExistFunc: func(config *rest.Config, gvks []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error) {
//				panic("mock out the CheckCRDsExist method")
//			},
//		}
//
//		// use mockedChecker in code that requires crd.Checker
//		// and then make assertions.
//
//	}
type CheckerMock struct {
	// CheckCRDsExistFunc mocks the CheckCRDsExist method.
	CheckCRDsExistFunc func(config *rest.Config, gvks []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckCRDsExist holds details about calls to the CheckCRDsExist method.
		CheckCRDsExist []struct {
			// Config is the config argument value.
			Config *rest.Config
			// Gvks is the gvks argument value.
			Gvks []schema.GroupVersionKind
		}
	}
	lockCheckCRDsExist sync.RWMutex
}

// CheckCRDsExist calls CheckCRDsExistFunc.
func (mock *CheckerMock) CheckCRDsExist(config *rest.Config, gvks []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error) {
	if mock.CheckCRDsExistFunc == nil {
		panic("CheckerMock.CheckCRDsExistFunc: method is nil but Checker.CheckCRDsExist was just called")
	}
	callInfo := struct {
		Config *rest.Config
		Gvks   []schema.GroupVersionKind
	}{
		Config: config,
		Gvks:   gvks,
	}
	mock.lockCheckCRDsExist.Lock()
	mock.calls.CheckCRDsExist = append(mock.calls.CheckCRDsExist, callInfo)
	mock.lockCheckCRDsExist.Unlock()
	return mock.CheckCRDsExistFunc(config, gvks)
}

// CheckCRDsExistCalls gets all the calls that were made to CheckCRDsExist.
// Check the length with:
//
//	len(mockedChecker.CheckCRDsExistCalls())
func (mock *CheckerMock) CheckCRDsExistCalls() []struct {
	Config *rest.Config
	Gvks   []schema.GroupVersionKind
} {
	var calls []struct {
		Config *rest.Config
		Gvks   []schema.GroupVersionKind
	}
	mock.lockCheckCRDsExist.RLock()
	calls = mock.calls.CheckCRDsExist
	mock.lockCheckCRDsExist.RUnlock()
	return calls
}
