---
# Source: nginx-kubernetes-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/version: "edge"
spec:
  # We only support a single replica for now
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway
      app.kubernetes.io/instance: nginx-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-gateway
        app.kubernetes.io/instance: nginx-gateway
    spec:
      containers:
      - args:
        - static-mode
        - --gateway-ctlr-name=k8s-gateway.nginx.org/nginx-gateway-controller
        - --gatewayclass=nginx
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: ghcr.io/nginxinc/nginx-kubernetes-gateway:edge
        imagePullPolicy: Always
        name: nginx-gateway
        securityContext:
          capabilities:
            add:
            - KILL
            drop:
            - ALL
          runAsUser: 1001
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx
      - image: nginx:1.25
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        securityContext:
          capabilities:
            add:
            - CHOWN
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /var/lib/nginx
          name: var-lib-nginx
        - mountPath: /usr/lib/nginx/modules/njs
          name: njs-modules
      initContainers:
      - command:
        - sh
        - -c
        - rm -r /etc/nginx/conf.d /etc/nginx/secrets; mkdir /etc/nginx/conf.d /etc/nginx/secrets
          && chown 1001:0 /etc/nginx/conf.d /etc/nginx/secrets
        image: busybox:1.36
        name: set-permissions
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx
      serviceAccountName: nginx-gateway
      shareProcessNamespace: true
      volumes:
      - emptyDir: {}
        name: nginx
      - configMap:
          name: nginx-gateway-conf
        name: nginx-conf
      - emptyDir: {}
        name: var-lib-nginx
      - configMap:
          name: nginx-gateway-njs-modules
        name: njs-modules
