name: Cherry-pick to Latest Release Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  cherry-pick:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'needs cherry pick') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      id-token: write # for get-from-vault to authenticate with Azure
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Get secrets from common vault
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@refs/heads/main
        with:
          client-id: ${{ secrets.AZ_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_VAULT_TENANT_ID }}
          vault-name: ${{ secrets.AZ_COMMON_VAULT_NAME }}
          secret-names: "nginx-bot-pat"
          env-names: "NGINX_PAT"

      - name: Set release branch variable
        id: branch
        run: |
          branch=$(git branch -a | egrep '^\s+remotes/origin/release' | awk '{print $1}' | sort -u | tail -n 1)
          release_branch=$(basename ${branch})
          echo "branch=${release_branch}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Cherry pick into ${{ steps.branch.outputs.branch }}
        uses: carloscastrojumo/github-cherry-pick-action@503773289f4a459069c832dc628826685b75b4b3 # v1.0.10
        with:
          branch: ${{ steps.branch.outputs.branch }}
          token: ${{ env.NGINX_PAT }}
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          cherry-pick-branch: ${{ github.event.pull_request.head.ref }}-cherrypick
