name: Generate

on:
  pull_request:
    branches:
    - main
    - release-*
    types:
    - opened
    - reopened
    - synchronize

jobs:
  generate-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        ref: ${{ github.head_ref }}
    - name: Generate Code
      run: make generate
    - name: Commit Changed Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update generated files
