name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: joshdales/labeler@1c9c27e128ed99ff80daecc98205c6292ea29a5b # if https://github.com/actions/labeler/pull/203 is merged, use the official action actions/labeler
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
