name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Lint Code
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --timeout 10m0s
          only-new-issues: true

  njs-lint:
    name: NJS Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Prettier on NJS code
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ${{ github.workspace }}/internal/nginx/modules/.prettierrc
          file_pattern: ${{ github.workspace }}/internal/nginx/modules/**/*.js
          prettier_version: 2.6.2
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
          echo "Run \"make njs-fmt\" locally to format the code"
