name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        directory: [., tests] # we need to run golangci-lint for every module https://github.com/golangci/golangci-lint/issues/828
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Golang Environment
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: stable

      - name: Lint Go
        uses: golangci/golangci-lint-action@e60da84bfae8c7920a47be973d75e15710aa8bd7 # v6.3.0
        with:
          working-directory: ${{ matrix.directory }}
          version: v1.63.4 # renovate: datasource=github-tags depName=golangci/golangci-lint

  njs-lint:
    name: NJS Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js Environment
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .nvmrc

      - name: Run Prettier on NJS code
        id: prettier-run
        uses: rutajdash/prettier-cli-action@d42c4325a3b344f3bd4be482bc34de521998d557 # v1.0.2
        with:
          config_path: ${{ github.workspace }}/internal/mode/static/nginx/modules/.prettierrc
          file_pattern: ${{ github.workspace }}/internal/mode/static/nginx/modules/**/*.js
          prettier_version: 3.3.3 # renovate: datasource=npm depName=prettier

      - name: Prettier Output
        if: failure()
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{steps.prettier-run.outputs.prettier_output}}"
          echo "Run \"make njs-fmt\" locally to format the code"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint Actions
        uses: reviewdog/action-actionlint@abd537417cf4991e1ba8e21a67b1119f4f53b8e0 # v1.64.1
        with:
          actionlint_flags: -shellcheck ""

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
        with:
          config: .markdownlint-cli2.yaml
          globs: "**/*.md"
          fix: false

  chart-lint:
    name: Chart Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
        with:
          version: 3.12.0 # renovate: datasource=github-tags depName=helm/chart-testing

      - name: Run chart-testing
        run: ct lint --print-config --config .ct.yaml

  yaml-lint:
    name: YAML lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint YAML
        uses: reviewdog/action-yamllint@1dca3ad811867be18fbe293a9818d715a6c2cd46 # v1.20.0
