name: Mend

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - design/**
      - deploy**
      - docs/**
      - examples/**
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - design/**
      - deploy**
      - docs/**
      - examples/**

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  mend:
    if: ${{ github.event.repository.fork == false }}
    uses: nginxinc/compliance-rules/.github/workflows/mend.yml@c903bfe6c668eaba362cde6a7882278bc1564401 # v0.1
    secrets: inherit
    with:
      product_name: nginx-gateway-fabric_${{ github.ref_name }}
      project_name: nginx-gateway-fabric
