name: Mend

on:
  push:
    branches:
      - main
    paths-ignore:
      - design/**
      - deploy**
      - docs/**
      - examples/**

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Mend
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Download agent
        run: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
      - name: Verify JAR
        run: jarsigner -verify wss-unified-agent.jar
      - name: Scan and upload
        env:
          PRODUCT_NAME: nginx-gateway-fabric_${{ github.ref_name }}
          PROJECT_NAME: nginx-gateway-fabric
        run: java -jar wss-unified-agent.jar -noConfig true -wss.url ${{ secrets.WSS_URL }} -apiKey ${{ secrets.WSS_NGINX_TOKEN }} -product $PRODUCT_NAME -project $PROJECT_NAME -d .
