name: OpenShift Certification

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: 'ubuntu-24.04'
      image:
        required: true
        type: string
      image_version:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: ''
      dry_run:
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  preflight:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ (inputs.tag != '' && !inputs.dry_run ) && format('refs/tags/v{0}', inputs.tag) || github.ref }}

    - name: Login to Quay.io
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      if: ${{ ! inputs.dry_run }}

    - name: Download preflight binary
      run: |
        curl -LO https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/latest/download/preflight-linux-amd64
        chmod +x preflight-linux-amd64
        sudo mv preflight-linux-amd64 /usr/local/bin/preflight

    - name: Run preflight
      env:
        PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
      run: preflight check container quay.io/${{ github.repository_owner }}/nginx-gateway-fabric/${{ inputs.image_version }} > preflight-result.json

    - name: Check preflight results
      run: |
        failed_count=$(jq '.results.failed | length' preflight-result.json)
        if [ "$failed_count" -ne 0 ]; then
        echo "Preflight checks failed: $failed_count failed checks"
        echo "Results for preflight-result.json:"
        jq '.results.failed' preflight-result.json
        exit 1
        fi
