name: Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Branch
        id: branch
        run: |
          version=${{ github.event.inputs.version }}
          version=${version%.*}
          echo "branch=release-$version" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ steps.branch.outputs.branch }}

      - name: Get Release Notes
        id: notes
        uses: lucacome/draft-release@8a63d32c79a171ae6048e614a8988f0ac3ed56d4 # v1.1.0
        with:
          config-path: .github/release-notes.yml
          dry-run: true

      - name: Vars
        id: vars
        run: |
          # TODO(lucacome): improve this and maybe use appVersion instead of version if we switch to tags
          echo "current_version=$(yq '.version' <charts/nginx-gateway-fabric/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: ${{ steps.vars.outputs.current_version }}
          replace: ${{ inputs.version }}
          include: "site/content/**/*.md"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "edge"
          replace: ${{ inputs.version }}
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: ${{ steps.vars.outputs.current_version }}
          replace: ${{ inputs.version }}
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "Always"
          replace: "IfNotPresent"
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Generate manifests and changelog
        run: |
          sed -i -e "s/v${{ steps.vars.outputs.current_version }}/v${{ inputs.version }}/g" README.md
          sed -i -e "s/\[${{ steps.vars.outputs.current_version }}\]/\[${{ inputs.version }}\]/g" README.md
          sed -i -e "s/VERSION = edge/VERSION = ${{ inputs.version }}/g" Makefile
          sed -i "6r .github/CHANGELOG_TEMPLATE.md" CHANGELOG.md
          sed -i -e "s/%%VERSION%%/${{ inputs.version }}/g" CHANGELOG.md
          sed -i "8a ${{ join(fromJson(steps.notes.outputs.release-sections).release-notes, '\n') }}\n" CHANGELOG.md
          make generate-manifests

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Release ${{ inputs.version }}
          title: Release ${{ inputs.version }}
          draft: true
          branch: docs/release-${{ inputs.version }}
          author: nginx-bot <integrations@nginx.com>
          committer: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates all the necessary files for ${{ inputs.version }} release.
