name: Run build for renovate PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-renovate
  cancel-in-progress: true

jobs:
  check:
    name: Check for changes
    runs-on: ubuntu-24.04
    outputs:
      generate: ${{ steps.filter.outputs.generate }}
    permissions:
      pull-requests: read
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check for changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            generate:
            - go.mod
            - go.sum
            - Makefile
  build:
    name: Build for renovate PRs
    runs-on: ubuntu-24.04
    needs: check
    permissions:
      contents: write
    if: ${{ needs.check.outputs.generate == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Golang Environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          cache-dependency-path: |
            go.sum
            .github/.cache/buster-for-generate

      # go mod tidy can be removed once https://github.com/renovatebot/renovate/issues/12999 is implemented
      - name: Update files for renovate
        run: |
          make generate-all
          cd tests && go mod tidy && go mod verify

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: "Update files for renovate"
          commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
