// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package licensingfakes

import (
	"context"
	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/dataplane"
	"sync"
)

// CollectorMock is a mock implementation of licensing.Collector.
//
//	func TestSomethingThatUsesCollector(t *testing.T) {
//
//		// make and configure a mocked licensing.Collector
//		mockedCollector := &CollectorMock{
//			CollectFunc: func(ctx context.Context, logger logr.Logger) (dataplane.DeploymentContext, error) {
//				panic("mock out the Collect method")
//			},
//		}
//
//		// use mockedCollector in code that requires licensing.Collector
//		// and then make assertions.
//
//	}
type CollectorMock struct {
	// CollectFunc mocks the Collect method.
	CollectFunc func(ctx context.Context, logger logr.Logger) (dataplane.DeploymentContext, error)

	// calls tracks calls to the methods.
	calls struct {
		// Collect holds details about calls to the Collect method.
		Collect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Logger is the logger argument value.
			Logger logr.Logger
		}
	}
	lockCollect sync.RWMutex
}

// Collect calls CollectFunc.
func (mock *CollectorMock) Collect(ctx context.Context, logger logr.Logger) (dataplane.DeploymentContext, error) {
	if mock.CollectFunc == nil {
		panic("CollectorMock.CollectFunc: method is nil but Collector.Collect was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Logger logr.Logger
	}{
		Ctx:    ctx,
		Logger: logger,
	}
	mock.lockCollect.Lock()
	mock.calls.Collect = append(mock.calls.Collect, callInfo)
	mock.lockCollect.Unlock()
	return mock.CollectFunc(ctx, logger)
}

// CollectCalls gets all the calls that were made to Collect.
// Check the length with:
//
//	len(mockedCollector.CollectCalls())
func (mock *CollectorMock) CollectCalls() []struct {
	Ctx    context.Context
	Logger logr.Logger
} {
	var calls []struct {
		Ctx    context.Context
		Logger logr.Logger
	}
	mock.lockCollect.RLock()
	calls = mock.calls.Collect
	mock.lockCollect.RUnlock()
	return calls
}
